### ISSUE TITLE
Pro-active interact with users on Twitter that have requests/complaints about Bisq or other exchanges

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#1]
## Learning Goal
To find out, if an increased interaction on twitter will have a significant impact on app downloads.

## Hypothesis
More interactions with twitter users on the topic of cryptocurrency exchanges and increased references of @bisq_network will increase the social traffic share by 5%

## Metric
The current traffic share from social channels is 7% and the share within social of twitter is 9%. 
We could measure the session increase and download numbers from twitter referrals in Google Analytics.

To improve analytics we could use download links that encode twitter as the source, which would work better for desktop client clicks. Unfortunately as Twitter is used mainly on mobile it will not be very easy to measure the exact impact of the experiment.

## Experiment
Setup keyword monitoring of competitors within a tool like mention.io and interact on each of the discussions where people are complaining about competitors or are talking about @bisq_network. If it makes sense within the conversation add an encoded link that contains a twitter source tracking.

## Result
> _- What happened?_
> _- What data did we collect?_
> _- Anything unexpected?_

## Next Step
> _- Pivot or persevere?_
> _- Another experiment for this goal?_
> _- Do we need to clean up?_

**Comment by m52go** [comment]
This is already happening as a part of the [community management role](https://github.com/bisq-network/roles/issues/95) (through Twitter and reddit in particular) and on the #pulse channel on Keybase. Often the community itself will suggest Bisq when someone is frustrated with a competitor :)
