### ISSUE TITLE
Make short video series for the DAO called "Bisq DAO in Brief"

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#102]
This is a short, to-the-point, 'what, why, and how' video series to explain the DAO and BSQ token. It is intended as a general-purpose resource and pays no special attention to maximalists. I would like to link to this playlist on the bottom of the DAO landing page.

The idea of creating this kind of a video series has already come up a couple times, so I won't wait for approval to do this, but I'm making this issue in case anyone has any specific feedback on the proposed plan.

All videos will be in the 2-5 minute range, easily digestible, and the hope is they'll be the go-to video resource we can point people to.

**Video 1. What is the Bisq DAO? Why is it needed? (conceptual overview)**

Core principles: along with high degree of privacy and security...is high degree of resistance to censorship.
Mechanism to decentralize Bisq's governance, its control structure, the way it makes decisions and collects revenue.
<show before/after diagram to illustrate>
At the moment, revenue collection and decision-making are concentrated in 1 place.

**Video 2. How does it work? (practical example)**

DAO replaces centralized, hierarchical decision-making with collective decision-making.
BSQ token replaces central wallets to facilitate value transfer from traders to contributors.
Walk through example of compensation request and BSQ issuance.

**Video 3. What does the DAO mean for users? What about contributors?**

Changes in trading process (very little, and BSQ is optional)
Benefits of using BSQ, show how BSQ pays contributors and sustains project.
Contributors: do work, get paid (now is a great time to start contributing to Bisq)

**Video 4. High-level technical overview**

Runs on bitcoin network
How is data stored? What is stored on-chain?
What does a BSQ transaction look like?

**Comment by ManfredKarrer** [comment]
> Video 3. What does the DAO mean for users? What about contributors?

Maybe its worth to break that into 2 videos?

**Comment by ManfredKarrer** [comment]
> How is data stored? What is stored on-chain?

I think it is important to point out here that we use the blockchain for notarisation purpuse only not as data carrier (as most colored coin and smart contract projects do). We use the Bisqw P2P network as second layer network and combine that with the BTC network for creating a consensus sytem.

**Comment by m52go** [comment]
Closing as complete ([link](https://www.youtube.com/playlist?list=PLFH5SztL5cYPAXWFz-IMB4dBZ0MEZEG_e)).
