### ISSUE TITLE
Reach out to existing contributors (DAO launch)

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#108]
## Learning Goal/Objective
> _- What do we need to learn?_
> _- What is our riskiest assumption?_
> _- What is our one priority?_
> _e.g. "To understand the homepage messaging and design theme that drives the most conversions to activated users"_

To understand what communication channels and documentation material work best to activate existing contributors again.

## Hypothesis
> _- Is it Relevant to the learning goal?_
> _- Is it falsifiable and specific?_
> _- Is it causal? e.g. if X then Y._
> _e.g. "If the experiment is successful, I predict that we will create 250 new downloads per week because of a +7% increase in the View > Download conversion rate."_

If the experiment is successful, we predict that 25% (~55 of 218 contributors) try out the Bisq DAO at least on time on DAO Testnet or Testnet.

## Experiment Design
> _- Is it Specific?_
> _- Is it Achievable?_
> _- How will you collect the data?_

By communicating via different channels and creating educational material we want to engage and educate existing contributors. We will look at the proposals created on DAO Testnet and Testnet.

## Resource Estimation and Probability
> _- How much development effort is required?_
> _- How much people are required to run this experiment?_
> _- How is the Probability of this experiment to succeed? Low -20%, Medium - 50% or High - 80%_

Development effort is low, effort for creating marketing material is High.
The probability of success for this experiment is Medium.

## Results
> _- What happened?_
> _- Did we succeed or fail?_
> _- What data did we collect?_
> _- Anything unexpected?_
> _- How close have we been to our prediction?_
> _- Why did we see the result that we did?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by ripcurlx** [comment]
@m52go @ManfredKarrer Unfortunately I completely forgot to create our goals for our marketing/communication efforts back then, so I'm not 100% sure about the concrete numbers anymore. How many existing contributors did we want to reach?

**Comment by m52go** [comment]
My impression was always that email was the way to do this. Manfred and I discussed earlier and I think we decided that he'll reach out to them when the time is right.

**Comment by ManfredKarrer** [comment]
I would suggest a goal is to reach at least 70% of our active users.

**Comment by m52go** [comment]
Closing, as the DAO is now launched.
