### ISSUE TITLE
Reach out to traders (DAO launch)

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#109]
## Learning Goal/Objective
> _- What do we need to learn?_
> _- What is our riskiest assumption?_
> _- What is our one priority?_
> _e.g. "To understand the homepage messaging and design theme that drives the most conversions to activated users"_

To understand what communication channels and documentation material work best to activate traders to be aware of and try out the DAO.

## Hypothesis
> _- Is it Relevant to the learning goal?_
> _- Is it falsifiable and specific?_
> _- Is it causal? e.g. if X then Y._
> _e.g. "If the experiment is successful, I predict that we will create 250 new downloads per week because of a +7% increase in the View > Download conversion rate."_

If the experiment is successful, we predict that 10% of our monthly active traders (1,000 of 10,000) will purchase BSQ token on the DAO launch.

## Experiment Design
> _- Is it Specific?_
> _- Is it Achievable?_
> _- How will you collect the data?_
By communicating via different channels and creating educational material we want to engage and educate existing contributors. We are going to collect the data by looking at the webpage/doc opens that have the desktop-client as referral. After the launch date we'll look at the number of trades per month.

## Resource Estimation and Probability
> _- How much development effort is required?_
> _- How much people are required to run this experiment?_
> _- How is the Probability of this experiment to succeed? Low -20%, Medium - 50%of High - 80%_
Development effort is low (some in-app screens), effort for creating marketing material is High.
The probability of success for this experiment is Medium.

## Results
> _- What happened?_
> _- Did we succeed or fail?_
> _- What data did we collect?_
> _- Anything unexpected?_
> _- How close have we been to our prediction?_
> _- Why did we see the result that we did?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by ripcurlx** [comment]
@m52go @ManfredKarrer Unfortunately I completely forgot to create our goals for our marketing/communication efforts back then, so I'm not 100% sure about the concrete numbers anymore. How many of our existing traders did we want to reach?

**Comment by ManfredKarrer** [comment]
Not sure either....
I would say we want to reach 70% of our active traders. Might be hard to meassure as some prefer to be passive and anonymous so might not repsond to requests for feedback, etc.

**Comment by ripcurlx** [comment]
Yes, I guess we need to put as much information within the client as possible and highlight it with a *new* badge or similar.

**Comment by m52go** [comment]
In my opinion there was already too much information. For example, I don't think there's a need to outline the steps of testing the DAO if we already describe it elsewhere.

In my opinion, the DAO page in the client should have minimal text and bold calls to action.

I don't think there's any need to try reaching old contributors there...it's proven to be ineffective (and many users are confused into thinking that address is their testnet BSQ address). Email is a better bet for that anyway.

Rough idea of what I have in mind:

![dao-screen-new](https://user-images.githubusercontent.com/735155/53740192-a6a39900-3e61-11e9-9a4f-10f495ef8fab.png)

**Comment by ManfredKarrer** [comment]
@m52go Agree!

**Comment by m52go** [comment]
Closing, as the DAO is now launched.
