### ISSUE TITLE
Add feedback form into app

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/growth#11]
## Learning Goal/Objective
We want to see if users are using a feedback form and what the feedback is from their trade experience (specially after a completed trade and dispute).
This can provide a valuable information for us for improving Bisq as well as can satisfy the user emotionally if they see that we are interested in what their experienced with Bisq was. 
It has to be implemented in a way which protects users privacy and to not annoy user who do not want to do it.

## Hypothesis
We can compare the nr. of received feedback with trade volume and other metrics to see which percentage of users are engaging in that.
It might be hard to quantify a direct success from it but will deliver us high value data from the users directly. This will have impact on future improvements and therefore have leveraged effects.

## Experiment Design
It would require a concept how to present the feedback form and what we ask as well as how we make sure that privacy is protected.
We could make the data completely public similar to the trade statistics. Though we should avoid to over-use the P2P network for not core-use-cases. So the implementation would be subject for more discussion.

## Resource Estimation and Probability
It might take considerable resources to implement that. Mainly on the conceptual and UI side.

> _- How is the Probability of this experiment to succeed? Low -20%, Medium - 50%of High - 80%_
High.

## Results
> _- What happened?_
> _- Did we succeed or fail?_
> _- What data did we collect?_
> _- Anything unexpected?_
> _- How close have we been to our prediction?_
> _- Why did we see the result that we did?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by m52go** [comment]
I believe this has been in place for a while (Google Form link upon completing a trade).
