### ISSUE TITLE
Developer Call - 2019.05.28 at 17:00 CET

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#132]
It's important that we talk through the proposed protection mechanisms and determine a way forward.

This call is scheduled at the same time as past calls, so hopefully most folks can join...a critical part of determining how to best proceed will require developer input.

### Day/Time
- Tuesday May 28 2019, 17 CET

### Agenda
- determine conceptual approach for protection mechanisms
    - strengthening account age as near-term measure (https://github.com/bisq-network/proposals/issues/93)
    - p2p chat feasibility
    - implementing p2p verification methods (https://github.com/bisq-network/proposals/issues/83)
        - possible to do "quick-and-dirty" to start?
        - fixed responses only or free-form?

_Feel free to suggest other topics you'd like to cover (preferably as they relate to protection mechanisms)._

### YouTube
- https://www.youtube.com/watch?v=3QHQxAh6aGk

### Hangout
- TBD

**Comment by mpolavieja** [comment]
> * strengthening account age as near-term measure ([bisq-network/proposals#93](https://github.com/bisq-network/proposals/issues/93))

Within this bullet point, I think it is important to have feedback from developers about the pre-trade step, as this would enable the possibility of any 2FA method the traders agree without having to end the trade in a dispute wasting mining fees in case they don´t come to an agreement.

**Comment by m52go** [comment]
Outcome: ripcurlx and other developers will evaluate the technical requirements for the proposed measures and convey findings this week. Next week, we'll work toward crafting a technical specification and wire-frames to implement soon after.
