### ISSUE TITLE
Move away from Google Hangouts for live events

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#133]
We were already fighting against their new interface for livestreaming, which changed unexpectedly a few times, but today it didn't work at all.

This was probably just a 1-time bug/snafu. But Google's product management doesn't inspire any confidence in me. They have demonstrated that they have no issues haphazardly breaking/debilitating/discontinuing any of their services at any time.

I suggest we look for a new livestreaming tool. 

We need:

- minimal setup for viewers (no browser extension or software required for viewers)
- ability to record (for eventual upload to youtube)
- ideally no time limits for group calls
- ability to have at least 10 people participating in a video call

Jitsi and Riot have been suggested so far. Please suggest others you like.

**Comment by devinbileck** [comment]
Anything that respects your privacy and doesn't require a public account is ideal and may allow more people to join.

**Comment by m52go** [comment]
Looks like Jitsi is the way to go. 

We could host our own instance, but their hosted version at https://meet.jit.si/ looks sufficient. The additional privacy we'd get with self-hosting would be nice, but not critical, since recordings will be posted on YouTube anyway. I'm not sure it would be worth the hassle.

Drawbacks people should be aware of:
* [a browser extension](https://chrome.google.com/webstore/detail/jitsi-meetings/kglhbbefdnlheedjiejgomgmfplipfeb) is needed for those doing screen-sharing, and it only works on Chrome/Chromium
    * usually people know ahead of time when they're going to share their screen during a call, so this shouldn't be a huge issue
* recording only works when connected to Dropbox (cannot store/download the file directly to local drive)
    * this sucks, but hopefully isn't a deal-breaker...we can create a dropbox account specifically for this purpose so no one's account has to be exposed

If there are no strong objections, I'll start using Jitsi for the next event.

In a perfect world, we'd go with [BigBlueButton](https://bigbluebutton.org/). They're intended for videoconferencing for classrooms, so there's lots of nifty features like polling, hand-raising, white-board drawing, etc but the server requirements for hosting are [extremely heavy](https://docs.bigbluebutton.org/install/install.html) so it's probably unreasonable for our light needs.

**Comment by reipichu** [comment]
Would be great to have a solution that doesn't require a Google account!

**Comment by HarryMacfinned** [comment]
@reipichu ,
it's generally possible to see youtube videos with torbrowser.
And for chating, you can use the slack.
So, there no google account needed.

**Comment by m52go** [comment]
Yeah the intention of this issue was in part to remove the need for anyone to need a Google account (or any account at all) to participate.

Today's experience indicated that the hosted version of Jitsi won't work for us.

It seems our only option then is to configure our own instance of a suitable tool with sufficient hardware resources. We could stick with Jitsi (requirements not clear), or configure something else like BigBlueButton (see requirements [here](https://docs.bigbluebutton.org/install/install.html)). 

It seems like a BBB instance will cost at least 100 USD/month, but I assume we could just "power down" the server while we're not using it to cut that bill down substantially. Or, perhaps costs could be made more justifiable if the same server could be used to host the Slack replacement and/or other infrastructure needs down the line (GitLab?). 

BB has the following requirement—"Port 80 is not in use by another application"—so I'm not sure if that's even possible.

Not sure...need more research, and/or feedback from anyone with devops chops...

**Comment by m52go** [comment]
Unless anyone has any better ideas, I'm inclined to use Zoom. We've used it in the past, and even with 20+ people on video, it tends to work fine.

Privacy of the content/video isn't an issue since videos will be uploaded to YouTube, but privacy of participants is an issue (i.e., those who prefer not to identify themselves as attendees). Zoom has a solution for that -- there's a view-only mode which does not require any account or any additional software.

Downside is calls will be limited to 40 minutes, but I think that's a good thing.

Like everyone here I would prefer a non-corporate open-source solution, but going that route means mean we must operate our own infrastructure, and infrastructure that can handle many concurrent video streams is not cheap, and probably a hassle to maintain...I don't see a pay-off.

**Comment by devinbileck** [comment]
Just curious, what was the issue encountered with Jitsi?

**Comment by m52go** [comment]
Their hosted solution (at https://meet.jit.si) seems to have limited resources.

I hosted a call on Monday with ~5 participants (2 on video) and it was okay.

Tuesday's call had 6 participants with 3-4 on video and the whole thing became dysfunctional.

**Comment by m52go** [comment]
We've now had our second growth call with Zoom. Today it became apparent that we will need to pay for a premium account (15 USD/month)..."internally" it's no big deal to end a call after 40 minutes and reconnect, but when on a call with a guest, it's embarrassing and inconvenient to start a new call every 40 minutes to carry on a conversation.

Not sure about the "correct" way of doing this from a governance perspective, as it's not a huge expense and there's no contract. A proposal seems like overkill.

Here is what I will do: I'll just get the membership and start requesting 15 USD/month in the _next_ DAO cycle.

If there are any suggestions otherwise, please voice them here before the start of DAO Cycle #3.

**Comment by m52go** [comment]
Looks like Zoom has worked well so far, so I will mark this as complete.
