### ISSUE TITLE
Bounties for translations

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/growth#141]
Several contributors suggested posting bounties to attract new translators and to do one-time, concrete tasks. We can post a bounty for Chinese translations, for instance, and share the links along with our monthly report, as @m52go has suggested. I thought to start a discussion here to get your thoughts on this and see what projects we can post bounties on.

**Comment by y3v63n** [comment]
We can use these for tasks that we are unable to do for any reason. These may include: 

- doing legal translations (if someone feels uncomfortable doing them),

- translating into languages we don't have translators for,

- doing an external review of an existing translation,

- doing linguistic testing of the app to point out overlays, truncations, concatenations or other visual issues in the Bisq software,

- doing one-off tasks (like writing a Style Guide).

**Comment by arunasurya** [comment]
Here are some more ideas from the translator call:
- A contributor can suggest specific bounties on the #transifex Slack channel, and one of the admins creates an actual bounty with a specific BSQ amount. The bounty can be posted on Bisq forum and other platforms.
- If someone responds to that bounty posting, they will need to do the work and upon completing the task, can submit a compensation request, linking the bounty in the request.
- Perhaps we can start with a bounty for Chinese translations and possibly for legal translations (for Terms and Conditions).

**Comment by jmaurice** [comment]
As part of promoting the JPY trading pair in Japan, I'm having trouble with the language barrier, and could really use a Japanese translation. I'd like to request a bounty be created for this and then I'll get a native speaker to work on it with me and send the pull-request :)
Thanks!

**Comment by flix1** [comment]
Great idea @arunasurya. 

To avoid being overwhelmed you could perhaps define a calendar of priorities and focus on 2-3 languages per month?

**Comment by y3v63n** [comment]
@jmaurice @flix1 Guys, I've published a proposal for the [Japanese translation bounty](https://github.com/bisq-network/proposals/issues/104). Your comments and suggestions are very welcome.

**Comment by jmaurice** [comment]
@y3v63n Thanks for creating this bounty, currently only English speakers can use Bisq in Japan, so this was really critical. I also think it's great that you split it into 2 parts, as one person can do the translation, and a native speaker can review the translations, or vice-versa. We can have it done pretty quickly once approved. Thank you

**Comment by m52go** [comment]
Translations are largely in maintenance mode now because of tight budget. New website translations are on hold, and documentation translations will be determined on a case-by-case basis based on market making efforts (further details to be posted [here](https://github.com/bisq-network/wiki/issues/37)).

I'm closing this issue since this discussion isn't relevant right now / being addressed in ways described above.
