### ISSUE TITLE
Nigeria NGN / BTC Market Maker Bounty 500 $BSQ

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#156]
### Nigeria NGN / BTC Market Maker Bounty

To claim this bounty the contributor must make a market in Bisq NGN/BTC for 1 month.
https://bisq.network/markets/?currency=btc_ngn

This will involve:

1. Keeping at least 2 BUY and 2 SELL offers live during 1 month.

2. Attracting other traders to the market through marketing, communication, social media...

3. Completing at least 5 trades.

4. Report with feedback here on the details of the trades (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

5. Attend at least 1 live Bisq Growth call to answer questions and provide feedback on the experience.

### Bounty: 500 $BSQ

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/63943501-15a82600-ca70-11e9-8085-d149fd8e3a6f.png)

For the record, there was some NGN/BTC activity back in 2018... but nothing since.

**Comment by flix1** [comment]
@takinbo @Olugbo @adibas03 you might be interested in moving onto this after you complete the 1st trade bounty #23

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/66309081-fb802400-e908-11e9-974b-bd3fdec63462.png)

Someone is definitely trying to create a market in NGN...

**Comment by niyid** [comment]
What is the status of this issue?

**Comment by flix1** [comment]
@niyid 

The bounty is still open. Nobody has claimed it. If you intend to go for it I recommend that you say something here.

**Comment by niyid** [comment]
@flix1 
> @niyid
> 
> The bounty is still open. Nobody has claimed it. If you intend to go for it I recommend that you say something here.
Yes, I do.

**Comment by flix1** [comment]
> Why do you think those you mentioned earlier could not achieve the targets?

I don't know, but I don't think they even tried.

**Comment by niyid** [comment]
> > Why do you think those you mentioned earlier could not achieve the targets?
> 
> I don't know, but I don't think they even tried.

Ah. That's all I need. Try, I will.

**Comment by flix1** [comment]
Given the recent ban on centralized exchanges in Nigeria...
https://www.dw.com/en/nigerias-cryptocurrency-crackdown-causes-confusion/a-56547374

It seems like a very good time to showcase Bisq's censorship resistance there. We should try to find a local market maker.

**Comment by m52go** [comment]
Agree, but might be good to reduce the value of the bounty though as BSQ is now over 2 USD.

**Comment by pazza83** [comment]
Just went to check out the NGN/BTC market on Bisq.

It has to be manually added.  It is therefore, not immediately obvious to new users based in Nigeria that their is a way to trade on Bisq.

@bisq-network/bisq-devs can NGN be added to the default currencies in the next Bisq release?

Would adding by default cause any problems? The app does a good way of sorting them by offers anyway so why make it so they need to be manually added if we are looking to increase usability / liquidity?

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/111129114-fbf90180-8575-11eb-8388-a310e273a33e.png)

It looks like we have somebody trying to make a market in NGN/BTC !

**Comment by niyid** [comment]
> > > Why do you think those you mentioned earlier could not achieve the targets?
> > 
> > 
> > I don't know, but I don't think they even tried.
> 
> Ah. That's all I need. Try, I will.

@flix1 

I will be actively working on this, this March. If there are any objections (or if the bounty is no longer active), please indicate.

Regards.

**Comment by niyid** [comment]
Join Zoom Meeting
[us05web.zoom.us/j/81051614935?](http://us05web.zoom.us/j/81051614935?)…

Meeting ID: 810 5161 4935
Passcode: QXw8G3

Meeting is scheduled for Thursday 16/03/2023 at 09:00am.

**Comment by flix1** [comment]
> > > > Why do you think those you mentioned earlier could not achieve the targets?
> > > 
> > > 
> > > I don't know, but I don't think they even tried.
> > 
> > 
> > Ah. That's all I need. Try, I will.
> 
> @flix1
> 
> I will be actively working on this, this March. If there are any objections (or if the bounty is no longer active), please indicate.
> 
> Regards.

Bounty was never closed, so it is still available. Welcome! You will not be alone in the NGN market, also check out this https://github.com/bisq-network/growth/issues/274

**Comment by niyid** [comment]
> > > > > Why do you think those you mentioned earlier could not achieve the targets?
> > > > 
> > > > 
> > > > I don't know, but I don't think they even tried.
> > > 
> > > 
> > > Ah. That's all I need. Try, I will.
> > 
> > 
> > @flix1
> > I will be actively working on this, this March. If there are any objections (or if the bounty is no longer active), please indicate.
> > Regards.
> 
> Bounty was never closed, so it is still available. Welcome! You will not be alone in the NGN market, also check out this #274
@flix1 

Great. I hereby claim the bounty.

See the attached below.

![Screenshot from 2023-03-13 04-40-55](https://user-images.githubusercontent.com/20237127/224603202-c033b7fb-95f0-4e6e-ba3f-a2fd3d508dee.png)

**Comment by flix1** [comment]
Please @niyid continue to market make at least until March 20th. On March 20 we have **Market Day** and it would be great to have NGN active then. The original conditions for the bounty are 1 month, but I suppose if you continue until March 20th it should be well earned.

**Comment by niyid** [comment]
Sure. Certainly.

**Comment by Jayboi23** [comment]
> > > > > > Why do you think those you mentioned earlier could not achieve the targets?
> > > > > 
> > > > > 
> > > > > I don't know, but I don't think they even tried.
> > > > 
> > > > 
> > > > Ah. That's all I need. Try, I will.
> > > 
> > > 
> > > @flix1
> > > I will be actively working on this, this March. If there are any objections (or if the bounty is no longer active), please indicate.
> > > Regards.
> > 
> > 
> > Bounty was never closed, so it is still available. Welcome! You will not be alone in the NGN market, also check out this #274
> > @flix1
> 
> Great. I hereby claim the bounty.
> 
> See the attached below.
> 
> ![Screenshot from 2023-03-13 04-40-55](https://user-images.githubusercontent.com/20237127/224603202-c033b7fb-95f0-4e6e-ba3f-a2fd3d508dee.png)

Great Niyid, But at this point I think our focus should be on how to get more exchangers to Bisq so as to get the market going. I was really impressed with the USD/BTC and EUR/BTC markets when I checked this afternoon, guess we can do more in the NGN/BTC market too.
It's never about the money but to make Bisq well known to the people and we are the ones that can convince them to trade here as early adopters. (My thoughts though)

**Comment by niyid** [comment]
> > > > > > > Why do you think those you mentioned earlier could not achieve the targets?
> > > > > > 
> > > > > > 
> > > > > > I don't know, but I don't think they even tried.
> > > > > 
> > > > > 
> > > > > Ah. That's all I need. Try, I will.
> > > > 
> > > > 
> > > > @flix1
> > > > I will be actively working on this, this March. If there are any objections (or if the bounty is no longer active), please indicate.
> > > > Regards.
> > > 
> > > 
> > > Bounty was never closed, so it is still available. Welcome! You will not be alone in the NGN market, also check out this #274
> > > @flix1
> > 
> > 
> > Great. I hereby claim the bounty.
> > See the attached below.
> > ![Screenshot from 2023-03-13 04-40-55](https://user-images.githubusercontent.com/20237127/224603202-c033b7fb-95f0-4e6e-ba3f-a2fd3d508dee.png)
> 
> Great Niyid, But at this point I think our focus should be on how to get more exchangers to Bisq so as to get the market going. I was really impressed with the USD/BTC and EUR/BTC markets when I checked this afternoon, guess we can do more in the NGN/BTC market too. It's never about the money but to make Bisq well known to the people and we are the ones that can convince them to trade here as early adopters. (My thoughts though)

@Jayboi23 
It is never about the money; but money can be quite an incentive. ;)

On a serious note, I have been working on the adoption of Bisq for 4 years; initially as a Developer by proposing the mobile (especially Android) version. And since that appeared to be going nowhere trying a bit of marketing. The push to create a Nigerian market did not start this March, 2023 I'm afraid.

Happy trading.

PS: If you code, you can take a look at the [Github issues](https://github.com/bisq-network/bisq/issues). You might be able to contribute as well. Also check the proposals.

**Comment by flix1** [comment]
I'm very happy to see that you can both work together on kickstarting the Nigeria market @Jayboi23 and @niyid ! I think there are also some other Bisq users from Nigeria from a few years ago as you can see in this issue: https://github.com/bisq-network/growth/issues/23 Maybe they can participate in Market Day! @takinbo @adibas03 @Olugbo 

Jayboi23 will be working as market maker on Market Day, there's a specific reward for that which I will be paying personally... see here: https://github.com/bisq-network/growth/issues/274   But it will be much easier to obtain that full reward if you both work together!

The market maker bounty in this issue will be paid by Bisq following the usual process: making a compensation request to the DAO, as is done by all contributors monthly here: https://github.com/bisq-network/compensation/issues

I also recommend that all 5 of you join the Bisq Matrix growth channel and discuss there how to really build the NGN/BTC market.

**Comment by niyid** [comment]
> 

@flix1 

Oh I see no problem here. I have simply staked a claim based on how bounties are supposed to work - the FIRST to achieve the goal (which is minimum of 5 trades - 2 buy and 2 sell trades); apart from others such as Social Media engagement etc (such as on nairaland.com, Twitter and Binance).

I will continue to contribute in other areas that will guarantee a lasting market; and not one that will fizzle out when the incentives end.

**Comment by niyid** [comment]
> Join Zoom Meeting [us05web.zoom.us/j/81051614935?](http://us05web.zoom.us/j/81051614935?)…
> 
> Meeting ID: 810 5161 4935 Passcode: QXw8G3
> 
> Meeting is scheduled for Thursday 16/03/2023 at 09:00am.


@adibas03

Thanks a lot for showing up for the Zoom meeting. I look forward to working with you. Send me a notice when you are done going through the [Bisq 2 Concept](https://github.com/bisq-network/bisq/discussions/6011) and [Bisq 2 code](https://github.com/bisq-network/bisq2) as discussed.

**Comment by niyid** [comment]
> Join Zoom Meeting [us05web.zoom.us/j/81051614935?](http://us05web.zoom.us/j/81051614935?)…
> 
> Meeting ID: 810 5161 4935 Passcode: QXw8G3
> 
> Meeting is scheduled for Thursday 16/03/2023 at 09:00am.
@adibas03

Thanks a lot for showing up for the Zoom meeting. I look forward to working with you.

**Comment by niyid** [comment]
Is there any link to join the Team Lead meeting?

**Comment by niyid** [comment]
> I'm very happy to see that you can both work together on kickstarting the Nigeria market @Jayboi23 and @niyid ! I think there are also some other Bisq users from Nigeria from a few years ago as you can see in this issue: #23 Maybe they can participate in Market Day! @takinbo @adibas03 @Olugbo
> 
> Jayboi23 will be working as market maker on Market Day, there's a specific reward for that which I will be paying personally... see here: #274 But it will be much easier to obtain that full reward if you both work together!
> 
> The market maker bounty in this issue will be paid by Bisq following the usual process: making a compensation request to the DAO, as is done by all contributors monthly here: https://github.com/bisq-network/compensation/issues
> 
> I also recommend that all 5 of you join the Bisq Matrix growth channel and discuss there how to really build the NGN/BTC market.

How do I join the Bisq Matrix growth channel? I went on YouTube and next Live event is on 20/03/2023. So no meeting for today (16/03/2023).

**Comment by Jayboi23** [comment]
@niyid 
Create a matrix account then use this link https://matrix.to/#/#bisq.growth:bitcoin.kyoto to join the growth channel

**Comment by niyid** [comment]
> > Join Zoom Meeting [us05web.zoom.us/j/81051614935?](http://us05web.zoom.us/j/81051614935?)…
> > Meeting ID: 810 5161 4935 Passcode: QXw8G3
> > Meeting is scheduled for Thursday 16/03/2023 at 09:00am.
> 
> @adibas03
> 
> Thanks a lot for showing up for the Zoom meeting. I look forward to working with you. Send me a notice when you are done going through the [Bisq 2 Concept](https://github.com/bisq-network/bisq/discussions/6011) and [Bisq 2 code](https://github.com/bisq-network/bisq2) as discussed.


@adibas03

How did it go with the study of Bisq 2? I could not find you on Matrix. I expect you will be on the [Matrix Channel](https://matrix.to/#/%23bisq:bitcoin.kyoto) for today's event?

**Comment by adibas03** [comment]
> 
@niyid Just seeing this.
I think I missed today's meeting too.
Looking for the info on the call, but can't seem to find it.
Wasn't able to make the Market day either, day was as s***show.
When can we reschedule the meeting.

**Comment by niyid** [comment]
> > 
> 
> @niyid Just seeing this. I think I missed today's meeting too. Looking for the info on the call, but can't seem to find it. Wasn't able to make the Market day either, day was as s***show. When can we reschedule the meeting.

Which meeting? I am not aware of any meeting scheduled for today. Anyway message me on Twitter (same username) so we can send private messages. I was waiting on you to get back to me as you planned to study Bisq 2 over last weekend.

**Comment by niyid** [comment]
Current score:

![my_trades](https://user-images.githubusercontent.com/20237127/228505114-04b1bf72-7004-485e-ba18-fd72378294b3.png)

**Comment by flix1** [comment]
Closing issue as completed. Bounty successfully claimed.
