### ISSUE TITLE
[Call] Strategies for Bootstrapping New Markets: Bisq BRIEF for September 5

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#157]
## Call details

- **Date:** Thursday September 05 2019
 - **Time:** 11:15a–12:15p Pacific (PDT) / 8:15p–9:15p Central European (CEST)
 - **Place:** Zoom (details below)

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Also join the #growth channel on our Slack workspace for more discussion on Bisq growth initiatives.

## About

Topic for this event is **bootstrapping new markets**.

Lately we've seen considerable interest in Bisq from folks in Brazil, Mexico, Nigeria, and other places. So far, we've found that the exact strategies to start and grow new markets varies on various factors on the ground.

On this call, we'll discuss:
* strategies that have worked in the past
* ideas and tactics for new markets
* how Bisq can help nurture new efforts with bounties, etc.

If you want to get a new market started on Bisq in your country/currency, but aren't sure how you can help (or you have ideas, but would like to discuss)—this call is for you.

## Call details

Zoom link:
https://zoom.us/j/322825254

You can also join without Zoom software or registration:
https://zoom.us/wc/join/322825254?pwd=

**Comment by FKrauss** [comment]
Part of the market bootstrap kit:

1. Research - what are the top payment methods in that country -> can be done online by checking LBTC or asking people on the ground what they use. If we find one that Bisq doesn't support we could consider adding it
2. Build a list of Youtube Channels & Podcasts that might be open to hearing from us - Contact and offer a local person or even a someone remote (that speaks their language) to talk to them about Bisq
3. Promotion - figure out some way to create time scarcity to the local users, so they download the app and try it. I.e. 4 weeks of reduced fees for BRL pairs. Coordinate with #2 so we don't have a market without buyers.
4. Optional - capitalize on local silly regulations to stay in the news cycle. i.e. Brazil just passed a law that every single crypto tx needs to be reported on a monthly basis to the extortion office. Or Portugal just reinforced that bitcoin arbitrage doesn't pay VAT nor Income tax on the individual level (although I don't think portugal is a target market for now)
5. I kinda forgot, but translations and presentations in the local language. Websites are not necessarily the best/easiest way to get information about something
6. we need a war chest of memes that we can recycle on a per language basis to be used on social media

**Comment by flix1** [comment]
Worth mentioning:

-Japan, especially issues #138 #139 and #140 (bounties successfully claimed).
-China #135 (bounty unclaimed)
-Nigeria #156 (bounty unclaimed)

**Comment by Olugbo** [comment]
👍

**Comment by flix1** [comment]
Today there are live offers in several new markets that we should tell people about:

China CNY  2 BUY offers
Nigeria NGN  1 SELL offer
Argentina ARS  1 BUY offer
Russia RUB  1 BUY offer
Vietnam VND  1 BUY offer
Romania RON  2 BUY offers
Georgia GEL  1 SELL offer

...there's a lot of new markets that just need a tiny push to get them started. It takes two to trade! So we should help these pioneers by letting more people know that they are there.

**Comment by wiz** [comment]
Suggested steps for Bisq entering new markets:

1) find solid ambassadors "on the ground"
2) localize bisq desktop app (translate, add local payment methods, etc.)
3) localize bisq website (translate, etc.)
4) localize youtube videos (translate, etc.)
5) begin education at meetup group using live trade demo, website, videos from above
6) only after everything is finalized, ready, etc. offer bounty for liquidity market makers in advance of actual liquidity party day
7) throw a big liquidity party for actual launch day
8) monitor bisq website analytics and bisq market data to get an idea of how it's going
9) hold additional educational sessions and further liquidity parties each month

**Comment by FKrauss** [comment]
For those interested, here are the slides I showed yesterday:
https://drive.google.com/open?id=11CH4sM0o3JFRylPzlHzwANMqT6g5HVtnc1jSoJP1wJ8

And if anyone is interested in discussing BR strategy in particular or even other markets that might be similar to it, hit me up on slack!

**Comment by m52go** [comment]
Recording is here:
https://youtu.be/MF7914AuyU0

Closing as complete.
