### ISSUE TITLE
Australia's New OSKO system.

### ISSUE THREAD

**Issue by aubits** [bisq-network/growth#159]
Suggest incorporating [OSKO](https://osko.com.au/about-osko) and [PayID](https://payid.com.au/) into Bisq

1) chargeback risk? 
_This is a new system however their byline reads: Osko is located within your online banking and backed by [BPAY](https://www.bpay.com.au/osko) so you know that it’s super safe. Less than or equal to current chargeback risk within current setup._ 

2) adoption rate? 
_Osko is available to all banks. So far 60 banks operate it and 3/4 of our "big four" have it available to their clients. As it operates inside most peoples banks ubiquitous adoption seems inevitable._ 

3) projections on how much volume will be used? 
_Impossible to tell, but nearly immediate payment opens a world of opportunity. Adopting this payment option should entice others who've been dissuaded by the up to 4 day length of trade._

4) how does it work, what information is required? 
_Users are required to register a [PayID](https://payid.com.au/) They can then send funds to any another using any of the following. Email, mobile phone #, [ABN](https://abr.business.gov.au/) or BSB with an account number._ 

5) what do you propose the per-trade risk limit should be, and why?
_Remain the same. Relatively new technology to the wilds of the internet and perhaps not all attack vectors have been explored._

6) what do you propose the per-trade time limit should be, and why
_Remain the same, with a review in 6 months_

7) what do you propose the GUI should look like to configure the account in Bisq (mockup would be best)
_Model on Japanese Zengin Furikomi whereby registering a BSB and Account number with additional fields for entering an optional email, mobile phone # , ABN as a direct transfer method._

**Comment by aubits** [comment]
Nuggets News on the NPP.
https://www.youtube.com/watch?v=NTQ_4iNFcgQ

**Comment by wiz** [comment]
@aubits can you please review this https://github.com/bisq-network/bisq/pull/4078

**Comment by m52go** [comment]
Closing as stalled.
