### ISSUE TITLE
Dec 13th growth call

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#16]
- **Date:** Wed Dec 13th 
 - **Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
 - **Place:** Zoom conferencing, see Call Details below

If you want to help Bisq grow, then this is the meeting to attend!

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Note also that you can subscribe to the Bisq DAO Google Calendar to get notifications about this call and other Bisq events. See https://bisq.network/calendar.

## Agenda

You'll find the general agenda of our growth calls here: https://github.com/bisq-network/growth/blob/master/docs/growth-meeting.md

As decided on last weeks growth call we will focus all our efforts for the next two months on increasing liquidity on the Bisq network.

Before we can grow the number of overall traders on the Bisq network, we first need to make sure that we have plenty of liquidity available in major trading pairs, esp. EUR and USD.
 
This means that anyone who considers themselves a potential 'market maker' or 'liquidity provider' is especially welcome on this call, to help us brainstorm ways to make Bisq an attractive place to be for you. We already have a number of ideas, and are looking to get your feedback.
 
Note that while we're happy to have pro and semi-pro traders serve as liquidity providers, we're also looking for anyone who simply has a need to sell BTC on a regular basis, e.g. for basic cash flow purposes.

This weeks growth call is all about the learnings of our first experiment (https://github.com/bisq-network/growth/issues/12)

## Call details

Join from PC, Mac, Linux, iOS or Android here: https://zoom.us/j/886127835

Or join with a touch on the iPhone : 
    US: +16699006833,,886127835#  or +16468769923,,886127835# 
Or join by phone： 
    Dial in： 
        US: +1 669 900 6833  or +1 646 876 9923 
    Meeting-ID: 886 127 835 
   International numbers available: https://zoom.us/zoomconference?m=5g8IvHLeIBIjeXlPhV3XWVE4cczQAtmu

## Comments welcome

Please add comments below with any questions you have or regarding any other topics you'd like to discuss on this call. See also the open issues in this repository.

Hope to see you there!

**Comment by ripcurlx** [comment]
Please review experiment pipeline and last weeks metrics to be up-to-date for today’s growth meeting.

- [Experiment Pipeline](https://github.com/bisq-network/growth/issues)
- [Trading volume of last week](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=1272392286?usp=sharing)

**Comment by cbeams** [comment]
Please also review the learnings from last week's experiment, starting with https://github.com/bisq-network/growth/issues/12#issuecomment-350995920

**Comment by cbeams** [comment]
Note to all, @csacher won't be on the call, but he plans to watch the recording later tonight and has offered to take notes while he does and then paste a link to / transcribe them here afterward.

**Comment by cbeams** [comment]
> Please also review the learnings from last week's experiment, starting with #12 (comment)

Actually, I just realized when reading the agenda for these meetings at https://github.com/bisq-network/growth/blob/master/docs/growth-meeting.md, that we will go through the learnings as part of the call, so no need to try to rush through reading them!

**Comment by cbeams** [comment]
## Additional agenda suggestions

In addition to the standard agenda, here are a few things I'd like to discuss, if we have time:

 - [ ] Should we continue doing open invites on Twitter to these calls? I did it last week, but I didn't do it this week
 - [ ] 5-minute timeboxed discussion of whether participating in this kind of liquidity experiments is something we want to submit and vote on BSQ compensation requests for (if it goes beyond 5 mins, we'll take it to Slack or elsewhere).

**Comment by csacher** [comment]
## Call notes
_(transcribed from the [GDoc](https://docs.google.com/document/d/1MKIOYAAqW9YP-Pv79InvXE_qrdhKtpxZ4iRY4m04oKo/edit?usp=sharing))_

**Date:** Wed Dec 13th
**Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
**Place:**   Zoom
**Recordings:** [Part 1](https://www.dropbox.com/s/u1ag90cj95d5jic/growth-call-%232-part1.mp4?dl=0) and [Part 2](https://www.dropbox.com/s/4gwfvnjo24508l8/growth-call-%232-part2.mp4?dl=0)

**Learnings from last week:**
https://github.com/bisq-network/growth/issues/12 

**Recap of last weeks experiment:** 
Outcome is not final (not included today), even without today: 64% increase EUR volume in the last 6 days compared to USD 16% growth. Still have to wait until the trades are settled. 

**Two factors that affected the result last week:** 
positively: the price, negatively: spam/congestion 

### Learnings

- When fees are high the use case for Bisq is limited
- In times of high fees → moving to other currencies is an option
- We need a better communication in times of spam attacks, high fees, congestion to notify users about the current situation
- Distribution of nodes has proved to cause difficulties (more than expected)
- Bisq is more like a future contract (traders make clear to agree on price and time)
- Manfred is working on fixing some issues (eg. timeouts), until this is done, rather don’t do another experiment 

### Ideas

- For people who are participating in the growth project it should be possible to submit compensation requests
- Bisq interface should give an overview over fees (mining and bisq), gains & losses 
Trades are also taken if the distance of price is high (2%)

### Outcome

- We will provide liquidity to the market. Everyone who committed in the call is putting two offers into Bisq (one on each side - buy/sell) - starting Thursday, 7/12/2017. Whenever there is an offer taken we put another one in. We do this for one week and see how it influenced the trading volume. **See issue #12 for details**.
- Add &quot;research for payment methods&quot; to issues in /growth repository.
- Attract traders from LocalBitcoins.com with a comprehensive pitch (approaching localbitcoins.com traders → easy to filter them through research on their website, get contact details and have maybe a short video chat)
