### ISSUE TITLE
Russia RUB / BTC Market Maker Bounty

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#160]
### Russia RUB / BTC Market Maker Bounty

To claim this bounty the contributor must make a market in Bisq RUB/BTC for 1 month.
https://bisq.network/markets/?currency=btc_rub

This will involve:

1. Keeping at least 2 BUY and 2 SELL offers live during 1 month.

2. Attracting other traders to the market through marketing, communication, social media...

3. Completing at least 5 trades.

4. Report with feedback here on the details of the trades (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

5. Attend at least 1 live Bisq Growth call to answer questions and provide feedback on the experience.

### **Bounty: 1000 $BSQ**

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/65142558-434f1200-da13-11e9-9ef6-17b66d39fed3.png)

Someone is trying to make a market in Russia. Hopefully this bounty will give them some extra encouragement and help them kick-start Bisq in Russia.

**Comment by wiz** [comment]
this is my bro @ifarnung - we're also talking about adding some payment methods and finishing the website in russian

**Comment by ifarnung** [comment]
@flix1 Yeah, I'll keep my markets up, and work on getting some trades going.  I can add a couple of other payment options, and narrow the spread to encourage someone to try Bisq.

**Comment by ifarnung** [comment]
I have completed 5 trades in the RUB / BTC market and plan to claim this bounty.

Report:
Dec 21, 2019 I sold .01 BTC for 4561 Rubles.  The customer also paid using Sberbank card online transfer.  The trade was completed very quickly as they sent the money as soon as the blockchain confirmation was received.
Nov 23, 2019 I sold .01 BTC for 4766 Rubles.  The customer also paid using a Sberbank card online transfer.
Oct 7, 2019  I bought .01 for 5449 Rubles.  I sent money to the seller using the Sberbank online app in combination with their Sberbank card number.  There was some confusion as his payment method was setup without any account numbers.  Instead he sent the payment info in trader chat, and also wanted me to send to another Name and account number different from the one that made the trade.  He was just trying to send some money to someone he owed it to.  In the end, I sent the money to his account and he forwarded it to the third party.  Just his first time using the software and didn't know the exact typical process. Less than 1 day to complete.
Sep 28, 2019 I sold .01 for 5357 Rubles.  They paid using the Sberbank card. No issues. Probably about 1-2 hours to complete.
Sep 21, 2019 I sold .01 for 6376 Rubles.  They paid using the Sberbank card. No issues. 1 hour to complete trade as the Rubles come instantly.


So it's a very quiet market and very very little interest for Russians using BISQ based on this experience.  I also had displayed F2F markets for Saint Petersberg (second biggest city) and never had any interest except for a recent email that was very vague about 'doing business together'.  I'm still not sure if they need to buy or sell or quantity or price.

I didn't have any trouble with the Sberbank card payment method though I hear from others on BISQ that it could be troublesome.  Certainly they can censor your payments if they want to, but at least in my experience it's the most common way of sending money around electronically.  Many stores even use Sberbank payments like they use Alipay in China.  Smartphone to smartphone.

In my Ruble experiment, I was offering to sell BTC at 1-2% BELOW the market rate, and I was simultaneously offering to buy BTC for 1-2% above the market rate, and yet still only 5 trades in 4 months.  So it isn't a question of price, but possibly a question of awareness or trust that keeps anyone from using BISQ in Russia.  I don't know.


@flix Please point me in the direction of the live call that I can participate in, I would be happy to discuss a little further, and answer any questions. Thanks.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/71347464-ba43fb80-256a-11ea-9b55-fcd958d52d00.png)


@ifarnung congratulations on an execellent job! I've been watching these past months and witnessing how you singlehandedly kickstarted the RUB/BTC market. Even keeping a negative spread  to encourage takers!

Don't worry that it goes very slowly at the beginning. It was the same for EUR and USD a few years ago! It was the same for BRL at the beginning of 2019. But once you attract a handful of regular users, they will stick around and bring more.

As for the call, just jump on the next Bisq Brief. I'm sure they'll be happy to dedicate a few minutes to your feedback on RUB/BTC. I guess it will be in the 2nd week of January.

**Comment by flix1** [comment]
@ifarnung to receive the bounty you will need to make a compensation request. 
Like this one:  https://github.com/bisq-network/compensation/issues/303

In https://github.com/bisq-network/compensation/issues

**Comment by ifarnung** [comment]
@flix1 Thanks for the positive feedback, I'm glad you found the contribution useful!  I will look for the Bisq Brief call in January.

**Comment by wiz** [comment]
> Don't worry that it goes very slowly at the beginning. It was the same for EUR and USD a few years ago! It was the same for BRL at the beginning of 2019. But once you attract a handful of regular users, they will stick around and bring more.

We had a few more trades on JPY recently, feels like this is really how it goes, extremely slow at first then slowly trickle in...

**Comment by chimp1984** [comment]
We should find better ways to bottstrap markets. A 1000 BSQ bounty for 2 small trades is a very expensive way.

<img width="1353" alt="Screen Shot 2020-01-08 at 22 37 55" src="https://user-images.githubusercontent.com/54558767/72018229-8d306200-3267-11ea-9b91-e2c01be51a15.png">

**Comment by flix1** [comment]
@chimp1984  I agree that there must be better ways. We have done many experiments and should continue to try new things. 

However I absolutely do not think you should focus on the trades, but rather on the fact that the market maker has kept live offers for more than a month and made efforts to attract users. Trades by themselves could be easily spoofed... but locking up funds for months in live offers and keeping Bisq running every day is a larger committment.

Also bear in mind that having earned 1000 BSQ that person is now incentivized to continue to use Bisq (if only to sell the BSQ) for a few months and normally will continue to attempt to start-up their local market as well as provide feedback on how to improve localisation efforts.

Is 1000 BSQ too much? should we ask for more work or more results? Maybe. I would still recommend that we honour this bounty and maybe change extant bounties as a result of this discussion.

I tend to think that it is better to ask for more work rather than reducing the bounty. We've tried smaller bounties before with little success.

**Comment by ifarnung** [comment]
@chimp1984  Totally reasonable criticism of the bounty, either the principle of the incentive or the amount of the bounty. I think it's good to look at the results and use that info. to decide where best to spend BSQ in the future.  Small counterpoint, it was 6 trades (of 7 lifetime) over 3 months while I worked on the bounty. Not much action, I agree, but better than the last trade being made in 2018, that really wouldn't inspire confidence in a new user.

If your main goal is to scrutinize the operating expenses more closely, I agree wholeheartedly with that spirit and it should be done aggressively.  I will post a critique that's been on my mind about the mediation costs in the relavent compensation request.

@flix1 I continue to make the market for Russia and Saint Petersburg at this time, so we will see what happens in that market.

**Comment by chimp1984** [comment]
@flix1 @ifarnung 
I agree to your response and did not argue to reject the promised bounty, just to try to improve our efficiency how we spend money, specially in times of low trade volume as it is the case over the past months.

**Comment by ifarnung** [comment]
@chimp1984 I took your comments not as a rejection of my bounty completion but more asking the question if this is a useful way to proceed in the first place.  And I'm completely fine with any criticism (general or directed) , I certainly won't get offended at any opposition to this or future bounties.  Some will find it a useful expenditure, others will prefer to conserve precious BSQ resources for another avenue, and we will see how the voters perceive it.

**Comment by flix1** [comment]
It's nice to see this market still up:

![image](https://user-images.githubusercontent.com/4233784/72250100-227e7e00-35fb-11ea-9fa8-95be2fc47b1d.png)

**Comment by flix1** [comment]
This bounty was claimed in this compensation request:
https://github.com/bisq-network/compensation/issues/454
