### ISSUE TITLE
[CALL] Bisq v1.2 - New Trade Protocol and Account Signing

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#163]
## Call details

- **Date:** Thursday November 07 2019
 - **Time:** 11:15pm–12:15pm Pacific (PDT) / 8:15pm–9:15pm Central European (CET)
 - **Place:** Zoom (details below)

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

## Topic / Agenda

**Bisq v1.2: New Trade Protocol and Account Signing**

The v1.2 release was a major one, bringing a new trade protocol with 2-of-2 multisig escrows and account signing to raise 0.01 BTC trade limits.

Lots of you have questions, and this call will be to address them.

See [this blog post](https://bisq.network/blog/bisq-v1-2-released/) for a summary of the changes as well as links to more detailed documentation.

## Call details

Zoom, links TBD.

**Comment by ripcurlx** [comment]
Issue discussing ideas how to generate seed accounts for smaller markets: https://github.com/bisq-network/bisq/issues/3576

**Comment by MwithM** [comment]
Is it possible to address this issue in the call? https://github.com/bisq-network/proposals/issues/135

**Comment by eigentsmis** [comment]
Will the call link be listed here at call time?

**Comment by m52go** [comment]
@eigentsmis yes.

**Comment by m52go** [comment]
Link (video and audio disabled by default):
https://zoom.us/j/355371585

Web link (no Zoom software required):
https://zoom.us/wc/join/355371585?pwd=

**Comment by FKrauss** [comment]
Is the video available already? I couldn't find it on Youtube

And thanks for addressing my questions, @m52go

**Comment by m52go** [comment]
Published here:
https://youtu.be/wkNBBgO5At8

Closing as complete.
