### ISSUE TITLE
[Call] Privacy-Protecting Growth Tactics - Bisq BRIEF for December 05

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#167]
## Call details

- **Date:** Thursday December 05 2019
 - **Time:** 11:15am–12:15pm Pacific (PDT) / 8:15pm–9:15pm Central European (CET)
 - **Place:** Zoom (details below)

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

## Topic / Agenda

**Privacy-Protecting Growth Tactics**

It's been a while since we talked about growth. As the network strengthens, and word spreads, the desire for more liquidity grows. What can be done to sustain and intensify Bisq's growth?

We'll discuss ideas to improve everything from traffic to the site, conversions, and approaches to improve liquidity such as referral links. 

Many traditional growth tactics are not viable with Bisq because of its strong stance on protecting user privacy, so more creativity is needed!

## Call details

Zoom:
https://zoom.us/j/322825254

Web (no Zoom software required):
https://zoom.us/wc/join/322825254?pwd=

**Comment by clearwater-trust** [comment]
Before recommending Bisq to new market makers I want to be certain the new 2 of 2 model can stay solvent, relevant, working.  (FULL DISCLOSURE: I don't know any market makers, I don't have any influence on social media or in the real world.) 

What will happen to the funds at the mysterious "[donation address](https://www.blockchain.com/btc/address/3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp)"?
Who is the cloak and dagger member @burning2019?
Are people getting repaid for failed trades?
What is the source of those funds?
What is the maximum amount of BTC we will allow at the "donation address" before we all freak out?
Is it insane to wonder all of these things?

Stay tuned! 2020 is going to be a pivotal Bisq timestamp.

**Comment by m52go** [comment]
Recording:
https://www.youtube.com/watch?v=MEEG8o5t3eg
