### ISSUE TITLE
Plan 2020 conferences

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/growth#168]
## Learning Goal/Objective
Next year is coming and I think we could plan/Aim to have Bisq represented on the stage at some of the major conferences. 

## Experiment Design
- map out conferences globally that are relevant for Bisq
- plan on topics to approach (talking about what is the DAO has been our talking point for a long time)
- check who do we have  on the ground that could make these presentations
- Collaborate on writing the materials and prepping the speakers

## Resource Estimation and Probability
- I believe some 4 Growth calls to nail all details and 1-on-1 discussions to get people more prepared to talk about Bisq on stage
- I would refrain from having the DAO "take" people to the conferences. This is experimental and should be done in a resource effective way

## Action Items
> Map conferences and dates
> Map Bisq contributors that are planning to attend these events
> Map and prepare interesting content / presentations to pitch organizers - given the above
> World domination

**Comment by m52go** [comment]
We could probably benefit from planning these things a bit further ahead. Let's have a preliminary discussion about this [on this week's call](https://github.com/bisq-network/growth/issues/167).

**Comment by sundaywar** [comment]
Great idea! Anyone else planning to be at Bitcoin 2020 in San Francisco? 

Bisq Happy Hour with P2P trading would be epic.

**Comment by FKrauss** [comment]
Btw, we continued the discussion on Keybase but here's the link to the spreadsheet.

https://docs.google.com/spreadsheets/d/1RZr5Fna98lTrNAEzlwxANT2_Hn5p9N0W9pIK7_gPAAM/edit#gid=0

It would be cool to have an idea of who could attend conferences on Bisq's behalf on late Q1 and Q2

**Comment by m52go** [comment]
Looks like the concept of meeting people in real life is all but annihilated for 2020. 

Maybe we should consider something similar, but for podcasts.
