### ISSUE TITLE
Proof of keys 2020

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/growth#169]
While all the exchanges are getting their ass kicked by people withdrawing their btc, we're chilled because every user already owns their private key.

Here are a few thoughts on things we could do for the celebration of the genesis block (aka proof of keys)

![Read more ](Https://proofofkeys.com)
(there is an episode of WBD podcast that just came out about it).

# add the pok support string in our twitter handle

It's that simple. Just go on trace meyers' twitter, copy and add it

# commemorative merch & sweepstakes
Get a designer to make some really cool bisq & pok t shirts, stickers, mugs and cap (preferably something that bitcoiners can wear without putting a target on their back for possible thieves, as it then has a much bigger appeal to the casual user)

In addition to it, give away a few of these items on twitter to spread it around and cause virality/word of mouth. It could also be based on cool comments or something more related to what will be happening on the day itself

# make a couple parody videos

I'm a bad script writer but something resembling a tutorial video where the character says "today we're gonna learn how to withdraw your bisq balance to private keys that you own" and then goes ahead making coffee and lazying around because that is already done.

Please note, I'm bad at writing humorous sketches :grin: but you get the point 

# meme arsenal

There will be tango downs all over the place. If we prepare a few meme templates we can react fast to these, make fun of the tangos and spread bisq along the way

# poke the big exchanges when they are getting Flak on twitter for delaying withdraws  

Reply each and every customer that complains with something that can succinctly explain bisq and not be called spam.... Memes work great for that :) 

# make the biggest prank ever and claim bisq got hacked 

And the attackers were only able to do something silly like lock themselves out of the p2p network :joy:... Maybe we leave this one for April first 

-------
Well... These are some ideas. I believe bisq is one of the only products in this space that has all it takes to capitalise massively on an event like this as we have the same ethos as bitcoin itself. Let's chat more about what else we could do and what resources we could leverage

**Comment by user718141** [comment]
You fools. No need to have keys on exchanges to buy Bitcoin. I moved from Bisq because it sucks.

https://safello.com/
https://bity.com

**Comment by m52go** [comment]
Lots of good ideas here too. Didn't have the bandwidth to do much with it this year, but by next year we should have more resources and talent to do something more special.
