### ISSUE TITLE
List Bisq on Coinmarketcap, Bitcoincharts. 

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#17]
## Learning Goal/Objective
> Are website visits impacted by being linked to and listed on Coinmarketcap, Bitcoincharts?

## Hypothesis
> Visits and downloads will increase 20% when Bisq is listed in these 2 high traffic reference websites .

## Experiment Design
> Compare weekly web views, downloads before and after. Track source of visits and measure % from sites.

## Resource Estimation and Probability
> This could probably be achieved in under a day.

## Results
> _- What happened?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> Is it worth it repeating with other key reference sites?

**Comment by flix1** [comment]
Request form submitted to include Bisq on Coinmarketcap

**Comment by flix1** [comment]
Bitcoincharts requirements are here:  https://bitcoincharts.com/about/exchanges/

**Comment by ripcurlx** [comment]
Not sure if our API supports `Accept-Encoding: gzip` or `ETag` header (@dan-da) which are both optional, but everything else should be available through our api: https://markets.bisq.network/api/

**Comment by ripcurlx** [comment]
I just checked the referrals for coinmarketcap.com in GA and saw that we are already listed there for some time: https://coinmarketcap.com/exchanges/bisq/
But traffic seems to pick up since December
![Traffic from coinmarketcap.com](https://user-images.githubusercontent.com/170962/34203474-86b1b82e-e57b-11e7-85ce-d66e791910fe.png)

I don't see any traffic from bitcoincharts.com yet.

**Comment by ripcurlx** [comment]
@flix1 Shall I contact bitcoincharts.com directly to add Bisq?

**Comment by flix1** [comment]
@ripcurlx sure. Go ahead.

**Comment by ripcurlx** [comment]
bitcoincharts.com responsed beginning of this year:

> I've already looked at your API in the past, but there are some differences to our requirements:
> Orderbook/Depth:
> JSON object containing two properties: bids and asks Both properties consist of an array of arrays where the first element is the price and the second element is the amount.
> And for the trades:
> - the trade_id has to be named tid and has to be a positive unique integer
> - the trade_date has to be named date and has to be in seconds
> 
> To be added, I would kindly ask you to provide us with an API according to these specs.
> We manage a large number of exchanges and every listed exchange currently uses our API.
> This gives us a big advantage in our further development.
> We hope for your understanding.
> 
> For further information and specifications please read our documentation here: https://bitcoincharts.com/about/exchanges/
> If you have any questions about this feel free to contact me again.

So if we want to get listed we need to provide them with a different API endpoint that matches their requirements on the response objects.

**Comment by flix1** [comment]
https://coinmarketcap.com/exchanges/bisq/
https://www.coingecko.com/en/exchanges/bisq
https://coinadviser.info/coin/BSQ-BSQ
