### ISSUE TITLE
Harcode Brazilian Banks to avoid mismatching

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/growth#170]
# Problem
I've been following the Brazilain support channel in Telegram and a recurring issue is people who have their fiat accounts mismatch the other side of trades which makes the "same bank transaction" feature a bit useless and risky.

Example: 
As the field is an string with no validation, when creating a fiat account, `Brandesco`  can appear as `Banco Bradesco`, `Bco Bradesco` and so on. Traders don't really know what their counterpart wrote, so they stay in the dark and we fragment the liquidity between `Same Bank Transfer` and `National Bank Transfer`

I propose that we hardcode all banks and names into the application so traders can avoid this ambiguity and the market can work much easier.

# More details
The Brazilian bank transfer systems is called COMPE, and the central Bank provides a list of all members. It even includes non retail banks 
The list can be found [here](https://docs.google.com/spreadsheets/d/1tjdzFNQrsV54A9N5z-tcBtC1wNp2W6tlOTk0EGb6nP8/edit#gid=0)

If we could add columns C and D to the app, similar to how Japan's bank transfers have their info. The market would function in a much smoother way.

**Comment by wiz** [comment]
We can just fork the Japan Bank Transfer payment method I made to create a new Brazil Bank Transfer payment method - all the banks can be hard-coded like this

<img width="433" alt="Screen Shot 2019-12-16 at 1 51 27" src="https://user-images.githubusercontent.com/232186/70865948-97cc4400-1fa6-11ea-97ba-e4439164bab8.png">

**Comment by FKrauss** [comment]
@wiz  and I discussed this on Keybase we'll make a diff proposal to make a Brazilian bank transfer payment method.

That is mainly to improve liquidity and simplicity:

- Spread across 4 payment methods, people need to have 4 accounts and makers and takers may not meet in the market.

- With one payment method, we can merge those 4 into 1 and add an extra field for preferred delivery (i.e. cash deposit vs bank transfer)

- Same bank transfer should be a choice of the taker, not the maker. The taker is the one paying the bank transaction fee (when there is one), so the maker should only care about someone wanting and willing to do the trade and not require people to have the same bank as he does


Anyways, a new issue will appear here where we outline the fields for Brazilian Bank Transfer
