### ISSUE TITLE
Implement smarter content strategy

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#171]
We generate a healthy amount of meaty content that almost no one watches. 

But it has a redeeming quality. In [Gary Vaynerchuk's lingo](https://www.youtube.com/watch?v=IwRfUJFpU3E), it's perfect "pillar" content that we can use for generating "micro" content for tweets and other shorter-form mediums. Growth/strategy calls, podcasts, event talks, etc are all 30-120 minute items that can be split up and spotlighted in numerous ways.

**This is a huge missing element of Bisq's approach to publicity.** Clever slogans and meming are not a marketing strategy...but they can be tools used as part of a broader content strategy.

We should make smarter use of the content we already produce by multiplying its utility to get Bisq more regular presence in the Bitcoin community and spark word-of-mouth, which is the strongest kind of publicity there is.

For example, one conference talk should result in at least 10-15 short videos posted on YouTube and Twitter, maybe 10-15 quote pictures, 2-3 adjacent blog posts, and maybe more. One growth call could result in a number of similar pieces too. And they're almost free! Meaning much of the creative initiative will already have been done...the remaining work is video editing, photo editing, etc.

Not only will this give us a higher volume of content to post (i.e., increasing presence and mindshare in the community), but we'll also learn more about what our followers care about (based on engagement), and be able to produce more content that addresses those specific topics.

Right now we just tweet/post a single link to a mammoth 1-hour call and call it quits. That's a huge amount of wasted potential.

**Comment by FKrauss** [comment]
I think we do need to start live tweeting the calls whenever a good quote comes up. But think the reason why we don't do this is because we simply never coordinated / assigned responsibilities for it. We now have some 3/4 people in the growth channel who are good in marketing. Let's try to operationalise that.

I would also add that for Proof of Keys on the 3rd we should have some of that content ready to be fired in replies and so on

**Comment by m52go** [comment]
I think it would be better to spread content out over time instead of bunching it all up at once while the call is happening...that's the whole point of the suggested approach.

But it's a big topic and needs more discussion...this is why I made the issue. Maybe we can make this the topic of a call early in the new year.

**Comment by m52go** [comment]
Supplanted by approach detailed [here](https://github.com/orgs/bisq-network/teams/growth/discussions/1) / [here](https://gist.github.com/m52go/4e0e5c5f8fef4d71e22ee4eaa742d141). Closing.
