### ISSUE TITLE
Translation Suggestion

### ISSUE THREAD

**Issue by doitsu232** [bisq-network/growth#183]
I suggest to complete the glossary for both, bisq-desktop and bisq-website.
currently we have about 250 strings in both glossaries and a total of 755 words to be reviewed, edited and translated.

time: ca. 2 days, could be finished in time to be added to cycle 10

costs:
755 x $0.07 = $52.85 /0.67 = ~79BSQ

**Comment by m52go** [comment]
Hi @doitsu232, appreciate the estimate. Sure, go ahead.

For what it's worth, this post was actually supposed to be a post on the Translations project board but apparently it's not publicly editable.
