### ISSUE TITLE
Mexico MXN/BTC Market Maker Bounty 1000 $BSQ

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#184]
### Mexico MXN/BTC Market Maker Bounty

To claim this bounty the contributor must make a market in Bisq MXN/BTC for 1 month.
https://bisq.network/markets/?currency=btc_mxn

This will involve:

1. Keeping at least 2 BUY and 2 SELL offers live during 1 month.

2. Attracting other traders to the market through marketing, communication, social media...

3. Completing at least 5 trades.

4. Report with feedback here on the details of the trades (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

5. Attend at least 1 live Bisq call to answer questions and provide feedback on the experience.

### Bounty: 1000 $BSQ

**Comment by flix1** [comment]
For examples of similar bounties that were successfully claimed please see #138 #160 #135

**Comment by luisantoniocrag** [comment]
Hello I'm from Mexico.

I am very interested in participating in this bounty.

My strategy plan is to make a video of how to exchange MXN for BTC and share it for all the BTC trading mexican groups in fb.
I will also create relevant content and tutorials that serve the community in Spanish.

**Comment by m52go** [comment]
@luisantoniocrag sounds great. Your past videos have been nice. To clarify, I want to make sure we agree that compensation for any content and tutorials you create are included in this bounty.

Are you aware of the [Bisq wiki](bisq.wiki/)? You can add content and tutorials there in Spanish without asking for anyone's permission.

Also, just so you know, there was another contributor `sundaywar` on Keybase who expressed interest in market-making for MXN. Perhaps it would be useful to consider collaborating? Up to you.

**Comment by MwithM** [comment]
@luisantoniocrag Do you already know what amount are the orders and amounts are going to be? Are they going to be available 24/7?

**Comment by luisantoniocrag** [comment]
The total orders I would place are 0.1 BTC.

and I have a server to have operations available.

**Comment by luisantoniocrag** [comment]
@m52go Yes, I would like to release documentation in Spanish. I think it's a good idea.

**Comment by m52go** [comment]
@luisantoniocrag making a Spanish version of the wiki might be more challenging than initially thought because the wiki software makes [supporting new languages clunky](https://www.mediawiki.org/wiki/Multilingual_MediaWiki), but we can figure something out. 

Please let us know what you'd like to create before making new wiki pages and we'll figure out the best way to post it.

@MwithM @flix1 any other concerns to cover before giving luisantoniocrag the go-ahead?

**Comment by luisantoniocrag** [comment]
How can i start?
I am very interested in the MXN market.

**Comment by m52go** [comment]
@luisantoniocrag looks like there's consensus for you to go ahead (sorry, I had missed the thumbs-up on my last post). 

Please feel free to begin, and keep us updated!

**Comment by luisantoniocrag** [comment]
Today I start with the 4  orders, in the following days I will change the size or number of orders. It also started with the promotion of BSQ in the MXN market. Wish me the best success haha

![2020-03-09_1938](https://user-images.githubusercontent.com/42625753/76271308-b5274c00-623d-11ea-8aee-0c2dbbd0578d.png)
![2020-03-09_1938_001](https://user-images.githubusercontent.com/42625753/76271312-b6587900-623d-11ea-8759-245e6cc1ee92.png)

**Comment by luisantoniocrag** [comment]
![Inked6vzy8_LI](https://user-images.githubusercontent.com/42625753/76710453-3e6ed080-66cd-11ea-9a9d-0ed05994b1a9.jpg)


I performed the first operation on Thursday, March 12.

The operation lasted about a day and there was no problem.

The funny thing is that I had not yet started with the promotion of the MXN market and there was a buyer. 


This is good.

**Comment by luisantoniocrag** [comment]
Second trade: ompzjs-2e5d1fb9-40c9-44cb-a2ec-ee78f1a6fafb-125
started : Mar 11.

A moment ago I just  finished the second one.

There was a problem, it took a day to confirm on the blockchain, then he mentioned that the "Payment started" had been frozen. 

After almost 4 days it was completed.

**Comment by luisantoniocrag** [comment]
Third trade: 052319-9601dc73-67c7-412d-a500-77492b8f228b-127
started: Mar 16.
The trade lasted 30 min.

For this trade there was no problem, it was very fast for both.

**Comment by luisantoniocrag** [comment]
At this moment I am waiting for a blockchain confirmation of another trade, if this continues the same, the exchanges will be much more than just 5.

I keep the 4 minimum orders on a ubuntu server.

![2020-03-16_0004](https://user-images.githubusercontent.com/42625753/76727609-1f4a6000-671a-11ea-8d6c-b9ee37f9c93c.png)

**Comment by luisantoniocrag** [comment]
fourth trade: 6PUEQN-66c1f38c-3713-4d70-a383-0bb930918083-125
started: Mar 16.
The trade lasted one day.

**Comment by luisantoniocrag** [comment]
fifth trade: 582780-20a0ddbb-3df8-4e3f-88a8-1d8207c16ac0-129
Started: Mar 16.
The trade lasted 4 hours.

objective accomplished, but this does not end here. we go for more trades and orders!

**Comment by luisantoniocrag** [comment]
sixth trade: MUXMCKCG-7fa0b012-2ac8-4504-94c0-6faa37b39eb2-127
Started: Mar 17.
The trade lasted 12 hours.

**Comment by luisantoniocrag** [comment]
seventh: WJWIF-630da6fc-23ea-483e-8979-6744818f84bb-127
Started: Mar 17.
The trade lasted 12 hours.

**Comment by luisantoniocrag** [comment]
![2020-03-17_2049](https://user-images.githubusercontent.com/42625753/76920475-32337080-6891-11ea-9d7a-6a2fc5408cee.png)
I'm keeping 4 operations and I am waiting for an eighth trade.

**Comment by luisantoniocrag** [comment]
Eighth trade: iql3swmb-92e86726-ffac-4943-8538-2b4db12af0ed-129
Started: Mar 17.
The trade lasted 19 hours.

**Comment by luisantoniocrag** [comment]
![2020-04-08_2019](https://user-images.githubusercontent.com/42625753/78848086-54269b80-79d6-11ea-81cd-7ef6b9a09fbd.png)
I still hold a minimum of 4 orders

### Tomorrow is a month since I started with the claim of the bounty.

I have a question. When and how can the call be scheduled?

**Comment by luisantoniocrag** [comment]
I want to report that there was another exchange on the  March 26th there was another exchange. But it wasn't mine.

![2020-04-08_2022](https://user-images.githubusercontent.com/42625753/78848257-d57e2e00-79d6-11ea-9c76-a41c1cd62af0.png)

**Comment by MwithM** [comment]
> I want to report that there was another trade on March 26th. But it wasn't mine.
> 
> ![2020-04-08_2022](https://user-images.githubusercontent.com/42625753/78848257-d57e2e00-79d6-11ea-9c76-a41c1cd62af0.png)

These are the best, it's not like you have to fulfill the whole MXN market!

**Comment by luisantoniocrag** [comment]
![2020-04-12_2311](https://user-images.githubusercontent.com/42625753/79091528-42653100-7d13-11ea-9063-1b3814b43fd9.png)
Today another trade was made and it was not mine.

Yeahhh! this is excellent.

**Comment by m52go** [comment]
This county was claimed successfully in https://github.com/bisq-network/compensation/issues/530, and bounty claimer @luisantoniocrag has moved on to a bigger growth effort in the Latin America region detailed in https://github.com/bisq-network/growth/issues/190.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/110244932-6a7c0500-7f61-11eb-8be3-1697e67c32ca.png)

It's nice to see that many months after this bounty was claimed, there is still activity in MXN/BTC. Increasing volumes even.
