### ISSUE TITLE
Solution for better liquidity

### ISSUE THREAD

**Issue by jt007** [bisq-network/growth#19]
This is a really great initiative! The primary challenge I see so far, is too low liquidity. This result in a big price difference between buyer and seller, which means a bad price compare to average market price for one or both traders. Sometimes there is also no seller or no buyer.

To solve this, I think there must be less alternatives when it comes to Fiat currencies. If you instead choose just 1 currency (EUR or USD etc), there will be more both buyers and sellers. This means it will be easier to buy and sell at a reasonable price. 

Although it will result in a minor currency exchange fee in the bank, this fee will be much smaller than what we lose on poor liquidity. With better liquidity it will also be easier to trust that I really will find a buyer or seller exactly when I need it, to a correct market price.

Better liquidity will also make far it easier to attract more people to the platform!
Is this possible to fix to enhance the liquidity?

**Comment by cbeams** [comment]
I don't see how reducing the number of fiat currencies available would increase the liquidity of any of the currencies that remain. I think you're suggesting that people would do bank transfers from their local currency, say, SEK into EUR, but this assumes that they are (a) using a payment method that makes this sort of currency exchange possible in the first place (some banks do, others don't) and (b) adds conceptual complexity to an already complex application that we would have to design for. In any case, I think this would be a non-optimal approach to solving the liquidity problem. It's an interesting thought, though, thanks for bringing it up. 

Please see issues in this repository labeled `liquidity` for details on our existing plans and ideas on this front, thanks. https://github.com/bisq-network/growth/issues?utf8=%E2%9C%93&q=label%3Aliquidity+

You can also join us in the #growth channel in Slack, and or join us for one of our upcoming weekly growth calls. See https://bisq.network/calendar for details. Cheers.
