### ISSUE TITLE
Start and growth LATAM market

### ISSUE THREAD

**Issue by luisantoniocrag** [bisq-network/growth#190]
## Summary

The core idea is to make support, content and relationship efforts focused to grow the Bisq markets on LATAM.

## What?

This idea is a continental effort in Latin America to grow Bisq brand awareness, presence, and adoption in the region. 
I will seek to create content and support for the community in Spanish.

This will be by stages and the countries with a central focus are Mexico, Argentina, Venezuela and Colombia.

It will be managed through the following "Bisq en Español" media:

[Facebook](https://www.facebook.com/bisqES/)
[Youtube](https://www.youtube.com/channel/UCVjZWgcbuhjqggKT_BOkstg)
[Telegram](https://t.me/bisqenespanol)
[Medium](https://medium.com/bisq-es)

It will also refer to [Twitter](https://twitter.com/BisqEs) account.

## Why

LATAM is truly a region where cryptocurrencies are booming due to mismanagement by banks and governments. Society is tired and is looking for real alternatives to current systems.

The main countries in LATAM where the use and exchange of cryptocurrencies (excluding Brazil) are:
Mexico, Argentina, Venezuela and Colombia.

## How

It really is a big job to do, and the goal is to make these markets start to have movement and grow, this also with the purpose of having collaborators and MM in the countries previously mentioned (Following the Bisq DAO decentralization mission). 

This first stage will consist of 3 months to evaluate the results (everything will include a monthly report of what has been done together with the evaluation comments)

Mexico will be the first objective (since it is where I currently live) and where I am already participating.

The second objective will be Argentina since I have many contacts from that country who are traders, market makers and even only use bitcoin to receive remittances.

These two objectives will be the priority in the next three months.

For Mexico, the goal is increment volume and for Argentina having someone claim the ARS / BTC
(#172 )  reward and then growing the market.

Everything will be achieved through the generation of content, translations and support in Spanish.

#### Facebook:

- Content creation, share Bisq news and events.
- Minimum two monthly broadcasts shared on Facebook groups (especially about trading and bitcoin) on how to exchange Bisq and/or frequently asked questions.

#### Youtube:
Weekly videos will be made
- Tutorials
- FAQs
- Announcements
- Relevant Bitcoin news (especially for LATAM).

#### Telegram:
- Support in Spanish
- Announcements are shared

#### Medium:
- Articles about Bisq news and 
experiences are written about the use of Bisq or participation in the DAO
- Medium is a good starting point for Blockchain media in Latin America to get informed and write articles about Bisq

`All future content can also be used on Spanish Twitter.`

Content will focus on users who really care about their privacy and want to buy/sell bitcoins safely.

Also for medium to long-term traders and MM.

## Who

I am willing to carry out this task, I have experience participating in the largest blockchain events in LATAM and I also have good communication with the main Crypto-Blockchain communities since I previously collaborated with a cryptocurrency in LATAM travelling to each country in this region ( excluding Brazil).

I have also collaborated with Bisq previously `(Writing articles, making videos and giving telegram support)`:
[Cycle 9](https://github.com/bisq-network/compensation/issues/469)
[Cycle 10](https://github.com/bisq-network/compensation/issues/496)
[Cycle 12](https://github.com/bisq-network/compensation/issues/530)

## Costs

Costs will depend on the monthly budget and the work done in each month.
I estimate:
max: `1000 USD`

At the end of the first three months, the results will be evaluated and decide whether it will continue or not.

**Comment by luisantoniocrag** [comment]
Brazil is not contemplated since the Spanish language is not the main language in that region.

Any questions, suggestions or feedback is welcome.

**Comment by m52go** [comment]
@luisantoniocrag thanks for writing this up. I think it would be great to see this market gain traction. ARS has already been mentioned by others as a [particularly attractive market](https://github.com/bisq-network/growth/issues/172#issuecomment-583787705).

Some questions:

1. it's a lot of work—will you be collaborating with others?
3. do you think there's any interest in altcoin trading in the region?
3. what would success look like to you at the end of 3 months?

Regarding (3), I know it's not easy to be precise, but I think agreeing on some kind of outcome will be important for evaluating your efforts in 3 months from now.

It might be helpful to see some of the [older issues](https://github.com/bisq-network/growth/issues/67) in this repository to see how EUR and USD markets were bootstrapped using liquidity days...seems like they worked fairly well.

**Comment by luisantoniocrag** [comment]
1.  In fact, the idea is to start alone and find more collaborators along the way.

2. Yes, in LATAM the interest in altcoin trading is increasing due to its good returns. They use Bitcoin as a medium of exchange and altcoins as trading.

3. I want to focus on the markets so the goal is to get users. In Mexico, it would be having a volume of at least 0.1 BTC per week.
In Argentina, we need to be the same.

I base myself on this because in the [MXN / BTC   bounty](#184) a volume of 0.3 BTC was achieved.

So it should be a little bit better and stable ending the 3 months.

**Comment by luisantoniocrag** [comment]
Something like this ([Bisq September Market Kick-Start Day](#67) ) clearly works.

I will also propose, I just have to finish some tutorials in Spanish in the first month because they have to know how to use the platform.

**Comment by m52go** [comment]
@luisantoniocrag most of this sounds good to me. I just noticed your budget is in BSQ...could you specify it in USD? BSQ price fluctuates a lot, and the Bisq budget is denominated in USD anyway. I think 1000 USD is the maximum we could do right now, which is about the 1700 BSQ you have right now at last cycle's rate of 0.56 BSQ/USD.

One other question—do you think it would be necessary to have a Spanish-speaking mediator for disputes?

**Comment by FKrauss** [comment]
Cool idea! For BR the pyramids and scams created a lot of interest in bisq. The telegram group really helps in onboarding and educating ppl. Have you created the group yet?

**Comment by FKrauss** [comment]
Do you know if the rest of latam(excl. Br) has the same problem of lack of fast payments?

I. E. In Brazil bank transfer is the only method.

Some folks actually found ways to go around that, which is by signing up for transferwise and using it as SEPA and Faster payments (but then tapping into GBP and EUR, not local currency). I wonder if that's also applicable to the rest of latam

**Comment by luisantoniocrag** [comment]
ok, a maximum of 1000 USD.

I think that a mediator who can provide support in English-Spanish will be necessary.
@m52go

**Comment by luisantoniocrag** [comment]
@FKrauss Yes, I have created the telegram group.
https://t.me/bisqenespanol

Yes, I think it is the same story.

For example, in Mexico there are multiple forms of payment, more private than others, but in the end as bank transfers.

We also have the option of https://transferwise.com/ with which we can send to multiple countries.

**Comment by m52go** [comment]
Looks like we'll have a mediator who speaks Spanish! He's not registered yet but should be within the next couple of weeks.

Wondering if @flix1 @mpolavieja @MwithM have any thoughts here before we begin? 

Timing is good since we're right at the beginning of a new cycle.

**Comment by clearwater-trust** [comment]
Of course, mediators are some kind of paid bureaucrat in the 2 of 2 system. They have no authority/power to do anything constructive. Nevertheless, the show must go on. Bisq is still my favorite. :heart:

**Comment by MwithM** [comment]
I proposed @luisantoniocrag  to open a facebook account specialized in LATAM after seeing the MXN bounty, his will to take on ARS bounty and the videos he created. The reason why I thought  Facebook was a good idea for LATAM market was that @mpolavieja saw that there were a lot of argentinians trying to perform some trades without guarantees.

The proposed it's a nice plan, but I wonder if it wouldn't be better to execute it step by step and focus for the moment just on the Facebook part, so we can see how it goes and then decide next steps.
Medium is a specialized media and only big announcements and articles (blogging) should be made there. Efforts need to be carefully calculated, and audience (current users) is still quite small.

Social network efforts for markets without almost any trading activity should prioritize into contact local people willing to start trading in their countries, detecting their needs and letting them know we are there if they need us.

**Comment by m52go** [comment]
I think @MwithM makes some good points. Makes sense for strategy to shift as audience changes.

@luisantoniocrag, looks like we should be ready to go. Would you mind posting updates here like you did for the market making bounties? Once a month, although a little more often might be helpful (up to you).

We're having [a call tomorrow](https://github.com/bisq-network/growth/issues/191) to discuss other growth-related items...would be cool if you could join (if you're around).

**Comment by luisantoniocrag** [comment]
new video:
https://www.youtube.com/watch?v=GPnxbJGa608
Some users asked me how to configure the MXN Nacional bank account in Bisq.

**Comment by luisantoniocrag** [comment]
I did an [article](https://medium.com/bisq-es/comprar-o-vender-bitcoin-de-forma-segura-en-m%C3%A9xico-a-trav%C3%A9s-de-transferencias-bancarias-dc6644795466?source=friends_link&sk=1bda0357b3bad663772ef4f0fa2ae90a
) about how to buy and sell BTC / MXN through bank transfers on Bisq.
For this article, I also did the translation of [Trading Rules](https://medium.com/bisq-es/reglas-del-comercio-y-disputas-en-bisq-2ba9a0a67d8f).

> After I'll migrate to the Spanish wiki.

**Comment by luisantoniocrag** [comment]
Hi, I publish a summary of the efforts.

any feed or comment is welcome.

https://github.com/bisq-network/compensation/issues/567

**Comment by luisantoniocrag** [comment]
Webinar (Bisq Introduction | Q&A  (Spanish) on May 29 

https://www.facebook.com/events/2595813257329925/

**Comment by ricardosaurio** [comment]
Im from Colombia and the single reason there is no COP movement is that there is NO payment method to buy from the regions with better volume.  All the offers I have posted, even with uphold, had spent weeks sitting there even at +5%. I have ideas to promote volumen through publicity, but they are expensive. Any sugestion to fix this i'm all ears

**Comment by Conza88** [comment]
SWIFT?
________________________________

**Comment by ricardosaurio** [comment]
extremelly expensive, cumbersome and slow (my banks states that it cant take 15 days), from my country to the exterior. Not so much for receiving.

**Comment by m52go** [comment]
@ricardosaurio is USD used in Colombia? Is it feasible to send/receive USD through bank accounts or money orders?

**Comment by ricardosaurio** [comment]
Not used at all, there are some banks that buy/sell USD but you cannot have an account in USD. What i have found is that its relatively easy to send money to an USD bank account through MoneyGram, but its extremely slow and expensive.

**Comment by luisantoniocrag** [comment]
The last Broadcast 
https://www.facebook.com/bisqES/videos/756028285138369/?eid=ARBDrduL3A68hPh2lgHsH6uIIV74qimqFtm2pUNjTIiKGQctDXJfFa_SfCcR5xxSFwG5eJcz-4RGP6Xe

And the last video on bisq en español channel
¿Qué son los BSQ? y ¿Cómo conseguirlos? - BISQ

**Comment by luisantoniocrag** [comment]
hey @ricardosaurio  join with us on Telegram 
https://t.me/BisqEs

let's talk about payments options in Colombia.

**Comment by luisantoniocrag** [comment]
**MXN volume increase initiative.**

Idea: On July 23, users will be able to place an order for one day and receive 10 BSQ as a reward.
Therefore, many users will place orders to grow orders in the MXN market.
It is expected to obtain at least 30 orders.

Upon completion of orders, the average number of orders and merchants is expected to grow.

Current MXN market:
- Total exchanges: 41
- 2020 Volume: 1.03BTC

The initiative will be shared with articles in the main Mexican media, Facebook trading groups and promotional videos and tutorials on YouTube.

Any feedback is welcome.

**Comment by ricardosaurio** [comment]
how would they claim the reward?

**Comment by luisantoniocrag** [comment]
@ricardosaurio  it will be something like this: [Market Kick-start](https://github.com/bisq-network/growth/issues/67)

User will claim reward in a compensation request.

**Comment by MwithM** [comment]
The way I see it, this kind of initiatives are risky for a privacy oriented platform, because sockpuppets could perform self trading just to claim their reward.
I see difficulties on having too many small compensation requests, on the side of voting them and also that mining fees could be more expensive than the reward.

Let's see what @flix1 thinks about it, as he did the market kick-start in the past.

**Comment by flix1** [comment]
> The way I see it, this kind of initiatives are risky for a privacy oriented platform, because sockpuppets could perform self trading just to claim their reward.
> I see difficulties on having too many small compensation requests, on the side of voting them and also that mining fees could be more expensive than the reward.
> 
> Let's see what @flix1 thinks about it, as he did the market kick-start in the past.

Previous experiments with small rewards were not very successful. Even for **liquidity days**, some of which worked well, almost nobody made compensation requests afterwards.

That being said, I'm happy to see anything new tried once. If it works we can replicate, if not we learn and try something else.

**Comment by sundaywar** [comment]
> 1. In fact, the idea is to start alone and find more collaborators along the way.
> 2. Yes, in LATAM the interest in altcoin trading is increasing due to its good returns. They use Bitcoin as a medium of exchange and altcoins as trading.
> 3. I want to focus on the markets so the goal is to get users. In Mexico, it would be having a volume of at least 0.1 BTC per week (as a minimum).
>    In Argentina, we need to be the same.
> 
> I base myself on this because in the [MXN / BTC bounty](#184) a volume of 0.3 BTC was achieved.
> 
> So it should be better and stable ending the 3 months.

Any update on this? I was the buyer if the 0.3 BTC, do I don’t think the Mexico market is active by any means. 1 buyer does not a market make.

**Comment by luisantoniocrag** [comment]
# Summary | Latam efforts 

Hello everyone, first of all I want to apologize, I was in very bad health and I interrupted my work status (not only in Bisq).

I want share to you a summary of the effort given and the cost it had for the DAO. I will also leave my plan to follow since I really want to continue participating until Mexico and LATAM use Bisq for the bitcoin exchange.

> The three months were not really worked, only two.
>
> MXN / BTC volume 2020
>
> April: 0.2544 BTC
> May: 0.1370 BTC (full)
> June: 0.1828 BTC
> 
> Total: 0.5742 BTC

- Created a Facebook page for Bisq in Spanish

https://www.facebook.com/bisqES/

- Live on Facebook with a Q&A section
https://www.facebook.com/bisqES/videos/756028285138369/

- Telegram group to give Spanish support 
https://bisq.network/en/

By the way @mwithm has helped me give support to many users especially from Spain who have had doubts about bisq.

- There were also 3 articles in Medium (Spanish)
https://medium.com/bisq-es

- 5 Videos on youtube
https://www.youtube.com/channel/UCVjZWgcbuhjqggKT_BOkstg

And a couple of strings converted to Spanish on transifex.

**The total DAO spend was: 507 BSQ or $320 at Cycle 14 rate.**

## Will I continue the effort for LATAM?

Of course!

I will continue to manage the Facebook page, Telegram, medium and make quality videos for youtube.

I will be collaborating with various users and @mwithm so that all content is of high quality.

I will look for more people from LATAM (Venezuela, Argentina and Colombia) to collaborate and help grow in bisq, since they are regions where bisq is suitable for the purchase and sell of bitcoin or other cryptocurrencies.

and I will be placing a couple of orders like MM per month.

### Cost?

I would really think about how much to charge depending on results, but I think the cost would be much less than expected.

Maybe ~150 to 200 USD per month until the market really grows.

It may even take a few months less than this, as I said depends on the results of each cycle.

Any feedback or comments are welcome.

**Comment by MwithM** [comment]
I'm happy you're back.
These three countries (Ven, Arg, Col) are ones where you already know people to work with? We're forgetting about Chile, which is a big and one of the most stable and rich countries in Latam. Maybe there's much potential for Chile, even if it's not as in trouble as Venezuela or Argentina. 
I have doubts about the potential of Bisq to trade with hyperinflated currencies, as settlement times can be very high. Everyday that buyer doesn't makes the payment is gaining something because of hyperinflation.

**Comment by m52go** [comment]
@luisantoniocrag glad you're back! You may want to consider hosting a call to see if any others would be interested in helping...it seems like there are a few people over the past few months who have expressed interested in helping with these markets.

Costs sound okay to me, as long as they're based on actual contributions (as usual).

**Comment by ricardosaurio** [comment]
> to see if any others would be interested in helping...

Im more than interested in helping out the Colombian market, but everyone in here uses Nequi and Daviplata as payment methods with COP. I do need those payment methods in Bisq to do some market making in COP or else my possible audience will just keep using localbitcoins.

**Comment by luisantoniocrag** [comment]
Hi @MwithM , sincerely I mentioned those three countries because where I did meetups in the past and met some crypto communities. But of course looking for someone to help in Chile is a great idea, it will be another priority market.

**Comment by luisantoniocrag** [comment]
@m52go, thanks!
Yeah, I'm available for this.

**Comment by m52go** [comment]
Closing as stalled. @luisantoniocrag thanks for your efforts while it lasted. If you'd like to help out again, please make a new initiative.

**Comment by ricardosaurio** [comment]
I would like this to be reopened. Im following closely this development so I cant try to help with the COP colombian peso market.
