### ISSUE TITLE
Add efecty as a payment method (Colombia users) 

### ISSUE THREAD

**Issue by ricardosaurio** [bisq-network/growth#192]
Name: Efecty https://www.efecty.com.co/

Description: Efecty is the main money transmitter here in Colombia, its widely used.

Type: Cash remittance.

Chargeback risk: Moderate. If the person reciving the Cash remittance doesnt cash it out quickly, the remitter could either ask for his money back or change the person receiving the remittance. After cashing out the money, its gone for good and no chargeback can occur.

Privacy protection: Low. You must provide your name and national ID number. When you cash out a remittance, they will also ask for your physical national ID card and your fingerprints.

Duration: Instant. After sending the money the other person can cash it out inmediatly.

Region: Colombia only. The only currency supported is the Colombian peso.

Fees: Variable fees. The highest fee is 2.99% after 500.000 COP (about 135$) https://www.efecty.com.co/calcula-tu-giro-lightbox

Trading limits: Maxium 3'000.000 COP (about 800 usd) per transaction, i couldnt find nowhere if there is a limit of the number of transactions you can do, but they do usually raise eyebrows for doing more than two trades a day. Also, large amounts of money cannot be withdrawn from most offices if they dont have the money with them (yes, 800 usd is a large amount here).

Fraud risk: Low, the sender and reciver will both get a receipt with a serial number (Numero de giro), a verification digit (VD) and national ID number that can be checked by anyone, including mediators and arbitrators. It also states if the money has ben cashed out. https://www.efecty.com.co/consulta-giros

Mandatory data: To either send or recive money, both parties would need to provide their physical ID card and biometric fingerprint.

Aditional notes: Im proposing this method because Efecty is very popular in Colombia and there is no COP volumen in Bisq and i will volunteer in anything needed to set this method. With risk of putting a bad name on Colombian people (im Colombian anyway), people tend to be dishonest and try to fraud if the oportunity appears. I would suggest at least a 30% collateral for the 2/2 multisig, and i wouldnt mind at all at 50%. Also, to kickstart this. I would ask for a signed account under this method and i would put small trades to sign other people.

**Comment by pazza83** [comment]
Efecty has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| ~~Very low risk of chargeback~~  | ~~No risk of chargeback~~  | **< very low risk of chargeback**  |
| ~~Way to verify the sender in the received payment~~ | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| **Trade time less than one week** | ~~Instant payment~~  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | ~~High usability and great user experience~~  | **< high amount usability**  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| ~~Low risk of scam attempts~~  | ~~Very low risk of scam attempts~~  | **< low risk of scam attempts** |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| **Minimum limit at least equal to at least account limits protocols**  | ~~No minimum limits~~  | ~~Minimum limit not able to achieve account limits protocols~~  |
| ~~Maximum limits equal to at least 0.01 BTC~~  | ~~Large payment limits up to 2 BTC~~  | **Maximum limit is less than 0.01 BTC**  |
| **Likely to increase liquidity**  | ~~Likely to increase liquidity and open markets for different countries and currencies~~  | ~~Likely to decrease liquidity~~  |
| ~~Low risk of mediation~~  | ~~Very low risk of mediation~~ | **< low risk of mediation**  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | ~~No fees for transactions~~ | **Fees will be a barrier to trading**  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 1/32
Percentage: 3.13%

Main problems with this are:

- Risk of chargeback
- High fees (2.7% for trades of 130 USD and, up to 10% for transactions below that amount).
- Max limit is 3,000,000 COP which is approx. $800 USD will soon be too low to reach required minimum of 0.01 BTC
- The chargeback issues would likely increase work for mediators and low transaction volumes would add not much in the way of fees.
