### ISSUE TITLE
Add Nequi as a payment method (Colombia users)

### ISSUE THREAD

**Issue by ricardosaurio** [bisq-network/growth#193]
Name: Nequi. https://www.nequi.com.co/

Description: Nequi is a fintech neobank that allows people to send money to anyone in any part of Colombia, and its very popular in here.

Type: Mobile.

Chargeback risk: None, once the money is send, its gone. Their support even states that if you have been scamed using Nequi, your only option is to inform the local authorities. https://comunidad.nequi.co/discussion/647/estafa

Privacy protection: High, to send money to someone else, you just need his phone number.

Duration: Instant from Nequi to Nequi, from payment processor (corresponsales bancolombia) to Nequi and instant from Bancolombia bank account to Nequi. About 1 to 2 working days from another bank to Nequi.

Region: Colombia only. The only currency supported is the Colombian peso.

Trading limits: For average joe user, Nequi will only allow you to trasact 7'000.000 COP, about 1800 USD, per month. I.e, if i´ve used Nequi for anything else, the maximun amount will decreaste. This will clear again back up to 7millon COP the next month. https://ayuda.nequi.com.co/hc/es/articles/115001872811-Quiero-saber-los-topes-de-mi-cuenta-Nequi

Fees: NONE. From another bank different from Bancolombia to Nequi, the initial bank migth charge something, but it varies from bank to bank. At least from Banco de Bogota to Nequi is less than 1$ in colombian pesos.

Fraud risk: Low. a Nequi user can do a man in the middle attack by using someone else's ID to open a Nequi account, since Nequi doesnt require you to show a physical ID to open an account, but i dont know how else could it help him to scam. Also, when you use Nequi, the app registers your money movement that gets ID'ed with a reference number, wich cannot be consulted from an outside source (mediator, arbitrator), its for internal use by Bancolombia. A screenshot can be taken but im not sure if there is a way to notarize a mobile screenshot.

Mandatory data: To open an account you will need an email, a phone number from Colombia and a national ID. Nequi also does biometrics with your face, but its for internal use. Opening an account its instant and they dont do any verification that would be requiered to be used in Bisq.

Aditional notes: Im proposing this method because Nequi is very popular on Colombia and there is no COP volumen in Bisq and i will volunteer in anything needed to set this method. With risk of putting a bad name on Colombian people (im Colombian anyway), people tend to be dishonest and try to fraud if the oportunity appears. I would suggest at least a 30% collateral for the 2/2 multisig, and i wouldnt mind at all at 50%. Also, to kickstart this. I would ask for a signed account under this method and i would put small trades to sign other people.

**Comment by ricardosaurio** [comment]
Dear Bisq devs, I just realized that neither Uphold, Revolut and AdvCash support funding from Colombian credit/debit cards. And binance and buda do support such cards. I belive that to attract LATAM users, we need payment methods accepted in these LATAM area. My 3 propossals only work in Colombia, but I can promise that these propossal are so widespread used, that I can raise awareness to kickstart Bisq trading in Colombia.

**Comment by ricardosaurio** [comment]
Hey Bisq devs,just so you know, Binance now added Daviplata, efecty and nequi to their P2P platform. This is outrageous, if there is something that Bisq should dominate the market is in the P2P options but binance has beaten us. I even have people willing to try out Bisq but they cant because lack of payment options for Colombian users.

**Comment by pazza83** [comment]
Hi @ricardosaurio thanks for all the information that is really useful.

Nequi sounds like a great payment option to be added to Bisq. It would be great if we could get it added to Bisq and you could start adding liquidity to the Columbian market 👍 

Please can you let me know the following:

1. Can the payment be made with description or reference information when the Bisq Trade ID can be added?
2. Would Nequi to Nequi transactions suffice as a payment method (sounds like this would be the most simple to add)
3. Can you include an example of a redacted screenshot to show what a user could provide in terms of providing proof of sent funds.

**Comment by ricardosaurio** [comment]
Hi @pazza83 ,  to answer your questions:
1- Yes, when you are sending money, you can add a text memo, i've tried counting and got tired at 200 characters, but thats enough for a bisq trade id. Unfortunately as far as I know, it cannot be notarized - I can show an arbitrator a screenshot that i send/recived the money with the tx-id, but there is no way for a third party to verify that. 
2- Yes, Nequi to Nequi is instant and free, it charges nothing to the sender or the reciver. Nequi can also send to other banks, but it wont be instant or free, except Bancolombia, wich as far as I know, its also instant, but not free.
3 typical nequi to nequi transaction,
![s1](https://user-images.githubusercontent.com/64046301/99006309-4149eb80-2510-11eb-9168-0218edd14aac.jpg)
- typical nequi to other bank transaction 
![s2](https://user-images.githubusercontent.com/64046301/99006349-53c42500-2510-11eb-9026-b05d04212761.jpg)

For all intents and purposes, we could assume that Nequi is for colombia what Swish is for sweden. But I should add that Nequi's service can be somehow unrealiable, as there can be hours where you cant just simply log in into your account, wich could requiere some retries. Altough not as popular as Nequi, Daviplata should be considered along with Nequi, because 1- Its a lot more realiable and 2- you can send physical cash to daviplata without having Daviplata even from overseas, wich would be a lot better for the intents and purposes of Bisq. As far as I know, you cant do that with Nequi, so I would strongly suggest to implement both apps.

P.D. Its Colombia, not Columbia. Not a patriotic or a grammar nazi, it just feels as wrong as bitconnect 2.0 XD

**Comment by pazza83** [comment]
Hi @ricardosaurio thanks for your speedy response 
> 1- Yes, when you are sending money, you can add a text memo, i've tried counting and got tired at 200 characters, but thats enough for a bisq trade id. 

That is great

> Unfortunately as far as I know, it cannot be notarized - I can show an arbitrator a screenshot that i send/received the money with the tx-id, but there is no way for a third party to verify that.

Is a mobile the only way you can access you Nequi account. No web version?

> 2- Yes, Nequi to Nequi is instant and free, it charges nothing to the sender or the reciver. Nequi can also send to other banks, but it wont be instant or free, except Bancolombia, wich as far as I know, its also instant, but not free.

Great I think Nequi to Nequi is the way to go. Would Nequi to Nequi be the most popular option for Nequi users?

> 3 typical nequi to nequi transaction,
Great even with my limited Spanish I can understand them 👍 

> For all intents and purposes, we could assume that Nequi is for colombia what Swish is for sweden. But I should add that Nequi's service can be somehow unrealiable, as there can be hours where you cant just simply log in into your account, wich could requiere some retries. 

Thanks what trading period would you suggest. For other instant payments it is 24 hours. Is this enough or is more needed?

> P.D. Its Colombia, not Columbia. Not a patriotic or a grammar nazi, it just feels as wrong as bitconnect 2.0 XD

Thanks, apologies!

> Altough not as popular as Nequi, Daviplata should be considered along with Nequi, because 1- Its a lot more realiable and 2- you can send physical cash to daviplata without having Daviplata even from overseas, wich would be a lot better for the intents and purposes of Bisq. As far as I know, you cant do that with Nequi, so I would strongly suggest to implement both apps.

Thanks for the info. Please can you open up an issue on https://github.com/bisq-network/growth/issues/ for Daviplata  and I will get right on it 👍

**Comment by chimp1984** [comment]
> it cannot be notarized - I can show an arbitrator a screenshot that i send/recived the money with the tx-id, but there is no way for a third party to verify that.

Do you have a https webpage access? If so PageSigner should work. Depends on the TLS version they use.

**Comment by ricardosaurio** [comment]
@pazza83  and @chimp1984  unfortunately is an APP only, and i have toutgh about accessing at least the transaction history to be notarized, but their own webpage redirects me to instructions on how to access the tx history through the APP.

@pazza83 yes, Nequi to Nequi would be the most popular option... and yes, 24h should be more than enough... If anything, as I said, since I cant find a way to notarize a transaction, and because im a colombian citizen and unfortunately i know a little bit about colombians, I would suggest the collateral to be -at least- 30%, or even better 50%.

**Comment by chimp1984** [comment]
If its only a phone app it has also the benefit to make it much harder to fake the app (a webpage could be easier faked with some proxy). so to make a video chat to the mediator and show the app screens should also be sufficient as i doubt that can be faked.
Sec. deposit can be set by maker, min is 15%, we do not code supporting diff. min. deposits per method, but i guess makers should know the risk and set it accordingly.

**Comment by pazza83** [comment]
Nequi has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| **Way to verify the sender in the received payment** | ~~Way to verify the sender in the received payment and ability to enter a reference~~  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| **Traders can provide evidence of payment / receipt**  | ~~Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar~~ | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| **Maximum limits equal to at least 0.01 BTC**  | ~~Large payment limits up to 2 BTC~~  | ~~Maximum limit is less than 0.01 BTC~~  |
| **Likely to increase liquidity**  | ~~Likely to increase liquidity and open markets for different countries and currencies~~  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | **No fees for transactions** | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 22/32
Percentage: 68.75%

**Comment by pazza83** [comment]
## Nequi - Proposed National Currency Payment Method

I am proposing that Nequi to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how Nequi will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: Nequi 

Required fields (eg)

@ricardosaurio please can you confirm what information is needed to make payment eg username, phone number or email

Signing required: No

Regions accepted: Colombia

Currencies accepted: COP

Bisq Limits: eg 0.03 BTC

App limits: 7'000.000 COP, about 1800 USD per month

Any relevant information for mediators / arbitrators: Verification might be via mobile screen recording if bank is app based.

Any relevant information for devs: Please can limit be set to 0.03 BTC

Any relevant information for users: Limit is 0.03 BTC per month and transaction.

Screenshot of expected GUI: TBC

**Comment by ricardosaurio** [comment]
To send money to someone you only need his/her phone number.

**Comment by pazza83** [comment]
Thanks for the quick response. I have updated the post above to include phone number. Many thanks looks like a promising payment method.

**Comment by pazza83** [comment]
Here is the XD for Nequi, it should be straight forward to add (main difference is buy/sell limit should be set to 0.03 BTC):

![Payment method - Nequi](https://user-images.githubusercontent.com/66367547/117579332-4caa5800-b0ea-11eb-8582-dc3184e3dde2.png)

**Comment by ricardosaurio** [comment]
Just out of curiosty, this 0.03 limit is the maximun limit or minimun limit?
I ask because rigth now , as i write this, 0.03 BTC are 6'540,411 COP wich is a lot of money here in colombia and people here usually trade lower ammounts.

**Comment by ricardosaurio** [comment]
Good to know it is the max limit, actually 0.03 btc is 6,151,288 cop. Average joe is limited to transact 7.268.208 cop per month with nequi, and do it for free, but non average joe is allowed to break this limit to infinite. Non average joe must go to a near bancolombia and fully identify himself and pay 15.000 cop to have this limit broken, and every transaction will have him charged with 0.4% of taxes (yeah, thats why Colombia is in a shaitstorm rigthnow). I think i should had mentioned this earlier, but average joe can still use nequi without this fee and without giving up an ID up to the aforementioned 7.628.208 limit.

**Comment by ricardosaurio** [comment]
There is no way for Bisq to differentiate non average from average joes. In the spirit of Bitcoin, meaning that anyone should be able to buy it, non average joes should have the prefference, as the app wont ask them for any private info (actually it does, but you can just lie about it). Now, seeing how the market is moving, im willing to bet that 0.03 BTC will soon be far away from the maximun trade limit and only non-average joes will be able to trade 0.03 BTC, so.... maybe it wouldnt be such a bad idea to increase the max limit?

**Comment by pazza83** [comment]
Ok, thanks for the inside info :)

I will up the maximum to 0.25 BTC, this is inline with most other fiat accounts.

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

Please make sure to include your phone number that matches your phone number from your Nequi account. 

When users set up a Nequi account payment limits are set to a maximum of ~ 7,000,000 COP that can be sent per month.

If you intend to trade amount of over 7,000,000 COP per trade you will need to complete KYC with Bancolombia and pay a fee of around 15,000 COP. After this all transactions will incur a 0.4% of tax. Please ensure you are aware of the latest taxes. 

Users should also be aware of account limits. Trades above Nequi account limits will likely have to be cancelled.

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only to phone number provided in the BTC Seller's Bisq account.

When users set up a Nequi account payment limits are set to a maximum of ~ 7,000,000 COP that can be sent per month.

If you intend to trade amount of over 7,000,000 COP per trade you will need to complete KYC with Bancolombia and pay a fee of around 15,000 COP. After this all transactions will incur a 0.4% of tax. Please ensure you are aware of the latest taxes. 

Users should also be aware of account limits. Trades above Nequi account limits will likely have to be cancelled.

### Special items to be aware about when receiving payments (for BTC Sellers):

Please checked that the payment received matches the pone number provided in the BTC Buyer's Bisq account.

When users set up a Nequi account payment limits are set to a maximum of ~ 7,000,000 COP that can be sent per month.

If you intend to trade amount of over 7,000,000 COP per trade you will need to complete KYC with Bancolombia and pay a fee of around 15,000 COP. After this all transactions will incur a 0.4% of tax. Please ensure you are aware of the latest taxes. 

Users should also be aware of account limits. Trades above Nequi account limits will likely have to be cancelled.

**Comment by ricardosaurio** [comment]
is there a way for the strings to be in spanish by default? I offer myself to do the translations.

**Comment by pazza83** [comment]
> is there a way for the strings to be in spanish by default? I offer myself to do the translations.

Not sure how the translation work. I assume when using Bisq with Spanish setting it will show in Spanish (once someone has translated it).

@jmacxx do you know if this is correct?

**Comment by jmacxx** [comment]
Correct.
https://bisq.wiki/Translation#How_to_contribute  
@mwithm coordinates translations.  https://github.com/bisq-network/roles/issues/20

**Comment by pazza83** [comment]
Completed wiki: https://bisq.wiki/Nequi
