### ISSUE TITLE
Add Daviplata as a payment method (Colombia users)

### ISSUE THREAD

**Issue by ricardosaurio** [bisq-network/growth#194]
Payment method: Daviplata https://daviplata.com

### Why

Daviplata is a neobank derived from banco davivienda, the transactions are instant and without chargebacks. Its widely used here in Colombia in e-commerces.

### Region

Only Colombian users, it only handles the colombian peso COP.

### Chargeback risk

No chargebacks are allowed. If you get scammed, their page states that all you can do its report to the bank and their insurance may pay-up if they belive a scam has occurred.

### Data requirements

To recive money with Daviplata, you will only need to provide your phone number.
The sender migth requiere to use his national ID card if he is going to send to Daviplata from a davivienda bank account or from a davivienda ATM that allows deposits. If he is sending from another Daviplata, he will not requiere his national ID.

### Verification

A sender can ask its daviplata app to send his transaction history to his email, wich can be notarized with TLSNotary. The transactions have an ID called "Numero de autorizacion" but these cannot be consulted by anyone, its for internal use by the bank. The email from where the transaction history is sent from is daviplata@davivienda.com.co

### Duration

From daviplata to daviplata, from davivienda bank account or from ATM deposit, the payments are instant. From other banks to Daviplata it can take up to 2 working days.

### Fees

From Daviplata to Daviplata, from davivienda bank account or from ATM deposit, there is no fee. There migth be variable feeds from an external bank to daviplata, but these vary upon the bank. My bank fees to Daviplata is less than 1$.

### Fraud risk

Man in the middle attack, to open a Daviplata account, you dont even need to give any personal data besides your phone number, but further from there, i dont think how it can be used to fraud a bitcoin seller.

### Trading limits

A maximun of 2.800.000 can be transferred to a Daviplata (about 750$) and this is also a monthly  limit for all your transactions. I.E. If i use daviplata for anything else, this limit will decrease, so you migth be limited to buy even less.

### Privacy protection:

High, to either send or recive  to Daviplata, i only need to provide my phone number. If im sending to daviplata from any other method, i migth need to provide my national ID, but the reciver wont know what my national ID is.

###Aditional notes:

Im proposing this method because Daviplata is very popular in Colombia and there is no COP volumen in Bisq and i will volunteer in anything needed to set this method. With risk of putting a bad name on Colombian people (im Colombian anyway), people tend to be dishonest and try to fraud if the oportunity appears. I would suggest at least a 30% collateral for the 2/2 multisig, and i wouldnt mind at all at 50%. Also, to kickstart this. I would ask for a signed account under this method and i would put small trades to sign other people.

**Comment by ricardosaurio** [comment]
An aditional note with this method, it doesnt have any kind of text or memo note during daviplata to daviplata transactions, it cannot store a transaction ID.

I dont know if this would rule out this method efectively, but its a shame if it would. Daviplata is not the most popular method in Colombia, but its by far the most realiable, fast and accesible for the average joe.

**Comment by pazza83** [comment]
Daviplata has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| **Way to verify the sender in the received payment** | ~~Way to verify the sender in the received payment and ability to enter a reference~~  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| ~~Maximum limits equal to at least 0.01 BTC~~  | ~~Large payment limits up to 2 BTC~~  | **Maximum limit is less than 0.01 BTC**  |
| ~~Likely to increase liquidity~~  | **Likely to increase liquidity and open markets for different countries and currencies**  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| **Fees should not be a barrier to trading**  | ~~No fees for transactions~~ | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 19/32
Percentage: 59.38%

Main problem with this is maximum amount is $2,800,000 COP about $750 USD, this will likely soon be lower than 0.01 BTC, this is also a monthly limit as opposed to a transaction limit.

**Comment by pazza83** [comment]
The above payment methods would be suitable if it were not for the low limits of around 0.01 BTC max transaction limit or under. I think this will likely cause issues in the months ahead and, therefore, these payment methods can be re-visited when the on chain miner fee problems have been reduced.

**Comment by ricardosaurio** [comment]
Agree, unfortunately 2'500.000 cop is a lot of money here but in BTC terms is, at this time, nothing. To make thing worse, this is a CUMmulative, i.e. if you use the 2.500.000 COP,  daviplata wont allow you to do any other transaction until the next month. Too bad, Daviplata is very popular and realiable.

**Comment by pazza83** [comment]
Thanks for the comments. Yes, it is not so much the 2,500,000 COP it is the percentage of the transaction that would be eaten by BTC fees that makes it unprofitable for buyers and sellers. It can be reviewed when there is an solution in place to reduce on-chain fees or fund an alternative.

[Nequi ](https://github.com/bisq-network/growth/issues/193)looks promising though :)
