### ISSUE TITLE
Dec 21st growth call

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#20]
- **Date:** Thu Dec 21st 
 - **Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
 - **Place:** Zoom conferencing, see Call Details below

If you want to help Bisq grow, then this is the meeting to attend!

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Note also that you can subscribe to the Bisq DAO Google Calendar to get notifications about this call and other Bisq events. See https://bisq.network/calendar.

## Agenda

You'll find the general agenda of our growth calls here: https://github.com/bisq-network/growth/blob/master/docs/growth-meeting.md

As decided on our first growth call (6th of Dec '17) we will focus all our efforts for the next two months on increasing liquidity on the Bisq network.

Before we can grow the number of overall traders on the Bisq network, we first need to make sure that we have plenty of liquidity available in major trading pairs, esp. EUR and USD.
 
This means that anyone who considers themselves a potential 'market maker' or 'liquidity provider' is especially welcome on this call, to help us brainstorm ways to make Bisq an attractive place to be for you. We already have a number of ideas, and are looking to get your feedback.
 
Note that while we're happy to have pro and semi-pro traders serve as liquidity providers, we're also looking for anyone who simply has a need to sell BTC on a regular basis, e.g. for basic cash flow purposes.

As we decided to wait for further growth activities until the next release (sometime in the next few days), we focused on preparations for contacting localbitcoins traders (https://github.com/bisq-network/growth/issues/7, https://docs.google.com/document/d/1E6bgZK25jQCmlOtvAYKzje5m-iQNzIJw6kRuY9HBq1M/edit)

## Call details
Join from PC, Mac, Linux, iOS or Android here: https://zoom.us/j/819505197

Or join with a touch on the iPhone : 
US:  +16699006833,,819505197#  or +16468769923,,819505197#  
Or join by phone： 
Dial in： 
US: +1 669 900 6833 or +1 646 876 9923 
Meeting-ID: 819 505 197 
International numbers available: https://zoom.us/zoomconference?m=5g8IvHLeIBIjeXlPhV3XWVE4cczQAtmu

## Comments welcome

Please add comments below with any questions you have or regarding any other topics you'd like to discuss on this call. See also the open issues in this repository.

Hope to see you there!

**Comment by csacher** [comment]
The notes for today's call: https://docs.google.com/document/d/15YyvPF95acFngfj5QSKcDgB6zNLmbNk2wmvA9i_mICI/edit?usp=sharing

**Comment by cbeams** [comment]
Thanks, @csacher. So glad you captured this, since I couldn't make the call.
