### ISSUE TITLE
New payment method from Brazil - PIX

### ISSUE THREAD

**Issue by felipeucc** [bisq-network/growth#208]
There is a new method of transferring securities available in Brazil called PIX. The recipient only needs to share a phone number, e-mail or Social Security Number. The advantage over the National Bank Transfer payment method is that the PIX works 24 hours a day, 7 days a week and the transfer takes place in a few minutes. To prevent users from creating orders in different ways with the intention of receiving through PIX (which would make it difficult to accept orders), I believe it would be important to create a PIX payment method where you only need to inform one field, which would be the link , a phone or email

### Why

_Why would Bisq benefit from adding this payment method? Is is popular in a particular region? More convenient? More safe?Is a payment method that works in the same way as National Bank Transfer for security, but uses a new protocol established by the Brazilian Central Bank and allows transfers to take place in a few minutes and works 24/7, which allows for faster negotiations

### Region

_Who can use this payment method?_
works throughout Brazil

### Chargeback risk

_How easy is it to cancel a payment once it's made? This is the most important characteristic of a payment method._
There is a possibility of chargeback if the payer disputes the payment at the Bank, as it is already done with National Bank Transfers. PIX follows the same rules, only uses a new protocol that works 24/7

### Data requirements

_What information **must** a user provide to a counterparty to accept a payment?_
the recipient needs to fill in a single field with the information he prefers (according to the registration made at PIX):
Social Security Number (called CPF in Brazil) OR
Phone number OR
Email
Only one of these 3 information is sufficient for payment to be made

### Verification

_How can payments be verified? Examples: TLSNotary is typically used for electronic payments, and receipt scans are typically used for money orders._
it is possible to generate a proof of transaction via internet banking

### Duration

_How long do payments take? Please provide a range, as the advertised best-case scenario rarely accounts for edge cases._
as PIX works 24/7 there is no need to worry about weekends for example. So I believe that 1 day is enough for the negotiation to be concluded

### Fees

_Does it cost anything to make a transfer using this payment method? If so, how much?_
There are no costs

### Fraud risk

_How easy or difficult is fraud with this payment method?_
it is possible for the recipient to inform a link in the field with the necessary data for payment (email, telephone or SSN described above). Link is also a valid possibility within the PIX protocol, but for the user's security within Bisq I believe that this option should not be used, because the link could be to a malicious destination. Outside this point, the risks are the same as for a National Bank Transfer

**Comment by pazza83** [comment]
Hi @felipeucc 

Thanks for all the info it looks great. Many thanks for taking the time to document the features. 

I will take a look at PIX and get back to you.

Is PIX the service from [NuBank](https://nubank.com.br/pix/ )?

**Comment by felipeucc** [comment]
> Hi @felipeucc
> 
> Thanks for all the info it looks great. Many thanks for taking the time to document the features.
> 
> I will take a look at PIX and get back to you.
> 
> Is PIX the service from [NuBank](https://nubank.com.br/pix/)?

No. Pix works in all banks in Brazil.
It was created by the Central Bank of Brazil (same as the FED)
https://www.bcb.gov.br/en/pressdetail/2361/nota

**Comment by lismanown** [comment]
Me and other people I've talked to are looking forward to adding this payment method on BISQ. Is there any way to contribute?

**Comment by pazza83** [comment]
Hi @lismanown thanks for the comments. To save myself and the devs time I am looking to batch up proposals for new payment methods for certain markets.

If you or other users would like other payment methods listed that can be used in Brazil please let me know any other payment methods you would like to add.

**Comment by lismanown** [comment]
Hello @pazza83, thanks for the reply. Apart from PIX nothing comes to mind. PIX is becoming the standard payment method in Brazil because its free, instant and all the banks support it. The current payment method on BISQ (namely TED transfers) you have to pay a fee to transfer between different banks, it only works on business hours, and also you have to provide your full name and social security number (namely CPF), which is really bad for privacy.

**Comment by pazza83** [comment]
Hi @lismanown thanks for the info I will get working on this.

**Comment by pazza83** [comment]
PIX has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| **Way to verify the sender in the received payment** | ~~Way to verify the sender in the received payment and ability to enter a reference~~  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| **Traders can provide evidence of payment / receipt**  | ~~Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar~~ | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| ~~Maximum limits equal to at least 0.01 BTC~~  | **Large payment limits up to 2 BTC**  | ~~Maximum limit is less than 0.01 BTC~~  |
| ~~Likely to increase liquidity~~  | **Likely to increase liquidity and open markets for different countries and currencies**  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | **No fees for transactions** | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 24/32
Percentage: 75%

**Comment by pazza83** [comment]
### PIX - Proposed National Currency Payment Method 

I am proposing that PIX to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how BitRefill will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

---


Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: PIX

Required fields (eg)
- Email OR Phone number

Maximum trade duration: 24 hours

Signing required: No

Regions accepted: Brazil

Currencies accepted: BRL

Bisq Limits: eg 0.25 BTC

Any relevant information for mediators / arbitrators: Verification might be via mobile screen recording if bank is app based.

Any relevant information for devs: No

Any relevant information for users: No

Screenshot of expected GUI: TBC

**Comment by lismanown** [comment]
Hi there, thanks for adding PIX

> Required fields (eg)
> 
>     * Email OR Phone number

Some banks also allow you to generate random keys instead of email or phone, which are uuid strings for example `123e4567-e89b-12d3-a456-426614174000` that is better for privacy

> **Way to verify the sender in the received payment**
> ~~Way to verify the sender in the received payment and ability to enter a reference~~

There is the ability to enter a reference when sending a transaction by using the "comments" field

**Comment by pazza83** [comment]
Hi @lismanown many thanks for the comments.

Are the random keys produced for each transaction or for any payment to your account. Essentially are they consistent enough to be included in the payment account setting on Bisq?

Thanks for the info about the comments. I will update the table / score to include this.

**Comment by lismanown** [comment]
> Are the random keys produced for each transaction or for any payment to your account. Essentially are they consistent enough to be included in the payment account setting on Bisq?

They are consistent, when you generate a random key you can use that key to receive as many payments as you want

Will "Email or Mobile no" enforce a specific format? Also how will the account signing work since there will be no signed accounts to sign other accounts?

**Comment by pazza83** [comment]
Hi @lismanown thanks for the information. Sorry for the late reply. That sounds great about the random keys, adds more privacy. I will include 'Your random PIX key' in the design so it can be used. 

> Will "Email or Mobile no" enforce a specific format? Also how will the account signing work since there will be no signed accounts to sign other accounts?

The accounts will not require signing (minimal risk of chargeback) so hopefully it will propagate pretty quickly as a payment method.

**Comment by mfilipe** [comment]
> Required fields (eg)
> 
> * Email OR Phone number

PIX can be a key referenced by SSN (called CPF), Phone, Email and UUID, so IMO it is better to require just a PIX key. The account owner decides which PIX key he wants to use.

**Comment by pazza83** [comment]
Hi @mfilipe thanks for the info. I will include this in the design.

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

Please make sure to include your chosen Pix Key. There are four types of keys: CPF (Natural Persons Register) or CNPJ (National Registry of Legal Entities), e-mail address, telephone number or a random key generated by the system called a universally unique identifier (UUID). A different key must be used for each Pix account your have. Individuals can create up to five keys for each account they own.

When trading on Bisq, BTC Buyers should use their Pix Keys as the payment description so that it is easy for the BTC Sellers to identify the payment as coming from themselves.

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only the Pix Key provided in the BTC Seller's Bisq account.

Please use your Pix Key as the payment reference so that it is easy for the BTC Seller to identify the payment as coming from yourself.

### Special items to be aware about when receiving payments (for BTC Sellers):

Please checked that the payment received description matches the Pix Key provided in the BTC Buyer's Bisq account.

**Comment by pazza83** [comment]
Hi @jmacxx as per @mfilipe's comments above please can the Email OR Phone No field be changed to:

Pix Key (CPF, CNPJ, Email, Phone number or UUID)

**Comment by pazza83** [comment]
Wiki completed: bisq.wiki/Pix
