### ISSUE TITLE
Bootstrap/Increase BTC_XMR (Monero) liquidity

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#21]
## Learning Goal/Objective
If we reach out to the Monero community and/or provide enough liquidity for the BTC/XMR order book, we bootstrap the market for organic growth.

## Hypothesis
If the experiment is successful, we predict to the total volume to grow by 25 percent.

## Experiment Design
We collect the most important channels for Monero and coordinate a marketing campaign by talking about Bisq and on the same time run a BTC/XMR liquidity week.
Every participant on the experiment tries to keep two offers (1 buy, 1 sell with low distance from market price) open all the time to provide liquidity.

## Resource Estimation and Probability
Low personal effort and High probability that it will succeed.

## Results
> _- What happened?_
> _- Did we succeed or fail?_
> _- What data did we collect?_
> _- Anything unexpected?_
> _- How close have we been to our prediction?_
> _- Why did we see the result that we did?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/47812852-b1321280-dd49-11e8-826c-a4537fa12542.png)

I don't know what we did, but it clearly worked. XMR volume is now consistently high. Maybe Bisq/Monero was just a perfect match...

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/58351102-1a08e580-7e68-11e9-947e-e3a3f06d9dd2.png)

This was hugely successful. I recommend closing this issue. @ripcurlx
