### ISSUE TITLE
Re-activating Bitcoinhackers.org account

### ISSUE THREAD

**Issue by stopfeds** [bisq-network/growth#216]
I hope this is the correct rep to talk about this topic. I have already asked this on Keybase but it seems like no one had an answer.

Due to the fact that a lot of Bitcoiners are moving over from Twitter to Mastodon (bitcoinhackers.org), it would be great to have an active account on this platform. Number of users & engagement is exploding on bitcoinhackers: https://the-federation.info/node/bitcoinhackers.org

I have seen that there are already two accounts but they haven't posted for years.
![image](https://user-images.githubusercontent.com/71401614/104238140-6cda4b00-5459-11eb-851b-7447869f68be.png)

For that reason, I wanted to ask who has access to these accounts? Maybe a bot that reposts from Twitter would be enough but it would be also great if someone could increase engagement on this platform.

This is definitely a good opportunity to grow.

**Comment by m52go** [comment]
I'm not sure who has access to those accounts...seems like community members. I don't recall any contributors mentioning it. Will try to find out.

Another idea: it would be cool to have a Bisq instance of some ActivityPub implementation that federates with bitcoinhackers.org. I've been a bit disappointed that everyone has defaulted to joining that one server.

**Comment by m52go** [comment]
If you or others could think of some kind of strategy or something to make a Bisq instance "special" in some way, such that people would have some reason to join it over bitcoinhackers.org, that might be nice. 

Or it could just be limited to contributors and known community members who ask to join...not sure. 

Or we could always just create an account on bitcoinhackers.org and call it a day.

**Comment by stopfeds** [comment]
I agree that everyone using the bitcoinhackers instance is not the best solution as NVK is in full control of the data and even private messages but tbh I'd rather trust him than Facebook, Reddit or Twitter. Right now, there is a much discussion going on about this topic and I think there will improvements from time to time.

What about starting with the existing account on Bitcoinhackers and try how this works out? I thought about standard content like news, updates, states of different markets, "Why Bisq?" etc. Similar to Twitter.

I think that most of the users on there are fully aware of the dangers of KYC and therefore already know (or even used) Bisq but getting awareness through engagement is never a bad idea. Users will get reminded that Bisq improves every single day and that the platform is still accessible for everyone.

Would be great if you can find out who is in control of these accounts, otherwise I am sure that NVK can help out.
If you guys don't have the capacity to manage this account I would be happy to help out and (test-wise) create content & manage it.

**Comment by Conza88** [comment]
Yep. I really don't like the name 😅.

Bitcoin hackers. Really? Woeful optics imo.

________________________________

**Comment by m52go** [comment]
Closing this issue, as it has been solved in a nominal sense—the @bisq@bitcoinhackers account is active and is controlled by a regular contributor.

Since the existence of bitcoinhackers.org itself seems to be in question, I think this might be the best we can do right now. 

Any further proposals such as making a new ActivityPub instance can be raised in new issues.
