### ISSUE TITLE
Add TransferWise-USD as a payment method

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#217]
## TransferWise-USD

Related issues: 

[Add Transferwise as new multi-currency payment method #243](https://github.com/bisq-network/proposals/issues/243)
[Improve Transferwise account ](https://github.com/bisq-network/bisq/issues/4931)

TransferWise info:

Due to what I assume is US banking regulation, Sending / receiving USD payments has more restrictions than most other currencies. This is the reason USD was not added to TW-TW payment method. For reference see:

- [Can I get USD account details?](https://transferwise.com/help/articles/2810318/why-cant-i-get-usd-account-details)
- [Sending US dollars to countries outside the US](https://transferwise.com/help/articles/2946451/sending-usd-to-countries-outside-the-us)
- [What countries can I send USD to?](https://transferwise.com/help/articles/2974947/what-countries-can-i-send-usd-to)
- [Can I send money to someone with only their email address?](https://transferwise.com/help/articles/2932105/can-i-send-money-to-someone-with-only-their-email-address)

### Background

TransferWise was added to Bisq a couple of months ago and is performing well. Unfortunately due to the reasons above USD was excluded from TW-TW payment method.

This proposal is to include 'TransferWise-USD' as a payment method for Bisq users to trade in USD. 

### Region

Anyone with a TransferWise account.

### Currencies

USD.

### Chargeback risk

Minimal 

### Size of user base

6 million worldwide customers in 2019

### Data requirements

Email address
*Account name
*Address 

*This info is required for USD transactions from accounts based in USA.

### Verification

TLSNotary

### Duration

Usually settlement is immediate if TW - TW where user send from available balance, debit or credit card (~80% of transactions)
If user chooses to fund via another payment method eg Wire Transfer then up to 4 days

### Fees

~0.25% if not funding using USD. 
~small fee of about $0.25 for all sending transactions

### Fraud risk

Low

### Payment amounts

Within 0.25 BTC limits as per other payment methods.

**Comment by Conza88** [comment]
Great! No easy way to access largest market in the world ATM. 

Interesting they might use SWIFT in certain instances sending USD to other countries lol.

**Comment by pazza83** [comment]
> Edit: I think this needs to be back burnered until other payment options are in e.g. SWIFT, given TW closing accounts recently

Let's wait until the trade ID issue is updated (if that is to happen) then reconsider.

**Comment by maltokyo** [comment]
Only USD?

**Comment by Conza88** [comment]
> Only USD?

Essentially the rest of the world is already added lol

**Comment by pazza83** [comment]
Yes pretty much everyone has access to TransferWise  at the moment on Bisq apart from users in Nigeria, Brazil and USA.

Nigeria and Brazil are not possible, but USA users can be catered for.

**Comment by pazza83** [comment]
TransferWise-USD has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~ | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| **No KYC required for sending and receiving payments** | ~~No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)~~ | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| ~~Maximum limits equal to at least 0.01 BTC~~  | **Large payment limits up to 2 BTC**  | ~~Maximum limit is less than 0.01 BTC~~  |
| ~~Likely to increase liquidity~~  | **Likely to increase liquidity and open markets for different countries and currencies**  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| **Fees should not be a barrier to trading**  | ~~No fees for transactions~~  | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 22/32
Percentage: 68.75%

**Comment by pazza83** [comment]
## TransferWise-USD - Proposed National Currency Payment Method

I am proposing that TransferWise-USD to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how ACH Transfer will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: TransferWise-USD

Required fields (eg)

Country: USA
Account owner full name
Account owner address
Email address linked to TransferWise

Signing required: No

Regions accepted: USA

Currencies accepted: USD

Trade window: 4 days

Bisq Limits: eg 0.25 BTC

Any relevant information for mediators / arbitrators: No

Any relevant information for devs: No

Any relevant information for users: No

Screenshot of expected GUI: TBC

**Comment by pazza83** [comment]
Here is the XD for TransferWise-USD, it should be straight forward to add:

![Payment method - TransferWise-USD](https://user-images.githubusercontent.com/66367547/117578999-e53fd880-b0e8-11eb-9431-7f8271351392.png)

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

Due US banking regulation, sending and receiving USD payments has more restrictions than most other currencies. For this reason USD was not added to Bisq TransferWise payment method. 

The TransferWise-USD payment method allows Bisq users to trade in USD.

Anyone with a Wise, formally TransferWise account, can add TransferWise-USD as a payment method in Bisq. This will allow them to buy and sell BTC with USD.

When trading on Bisq BTC Buyers should not use any reference for reason for payment. If reason for payment is required they should only use the full name of the TransferWise-USD account owner.

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only to the email address in the BTC Seller's Bisq TransferWise-USD account.
 
### Special items to be aware about when receiving payments (for BTC Sellers):

Please checked that the payment received matches the BTC Buyer's name of the TransferWise-USD account in Bisq.

**Comment by pazza83** [comment]
Wiki completed: https://bisq.wiki/TransferWise-USD

**Comment by stopfeds** [comment]
Transferwise rebranded to "Wise" at the beginning of the year: https://wise.com/gb/blog/world-meet-wise
Maybe we should update this, or at least show both names in-app.

What do you think?

**Comment by pazza83** [comment]
@stopfeds 

I agree. I have added this to my to do list :)
