### ISSUE TITLE
Add ACH Transfer - USA as payment method

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#219]
## ACH Transfer - USA

Reference: https://en.wikipedia.org/wiki/ACH_Network

### Background

For US users wanting to trade on Bisq using bank transfers (excluding thrid party methods like Zelle and Chase) they have two options:

- ACH 
- Wire

Currently neither of these payment methods can be added to Bisq.

There is a workaround where they can be added as 'National Bank Transfer' however this is not ideal due to differences in fees and trade times.

It is a bit like a EU user using National Bank Transfer for a SEPA transfer, or a UK user using Faster Payments transfer. It does work but it is a poorer user experience. 

I am proposing to add both Wire and ACH as separate payment methods in Bisq to improve user experience and hopefully increase trade volume. 

### Why

ACH Transfers are one of the two bank transfer payment method in the the US.

### Region

USA

### Currencies

USD

### Chargeback risk

Low

### Size of user base

300 million people have access to a bank account with Wire or ACH transfers.

### Data requirements

- Account name — your name as it appears on your bank account
- Account number
- Account type: Checking or Savings
- ACH routing number
- Local US address

### Verification

TLSNotary

### Duration

Up to 3 business days. Therefore, recommend 5 days as trade time.

### Fees

Anything from $0-3.

Users will be aware what it costs to send / receive an ACH transfer.

They are generally lower cost but slower than Wire Transfers.

### Fraud risk

Low

### Payment amounts

Within 0.25 BTC limit

**Comment by jimmyneutront** [comment]
I will be very interested in offering liquidity in the BTC/USD market if this payment method is implemented.

**Comment by pazza83** [comment]
ACH Transfer has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| **Way to verify the sender in the received payment**  | ~~Way to verify the sender in the received payment and ability to enter a reference~~  | ~~No way to verify the sender in the received payment~~  |
| **Trade time less than one week**  | ~~Instant payment~~  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| ~~Significant user base~~ | **Large user base**  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| **No KYC required for sending and receiving payments** | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)~~ | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| ~~Maximum limits equal to at least 0.01 BTC~~  | **Large payment limits up to 2 BTC**  | ~~Maximum limit is less than 0.01 BTC~~  |
| **Likely to increase liquidity**  | ~~Likely to increase liquidity and open markets for different countries and currencies~~  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| **Fees should not be a barrier to trading**  | ~~No fees for transactions~~  | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 22/32
Percentage: 68.75%

**Comment by pazza83** [comment]
## ACH Transfer - Proposed National Currency Payment Method

I am proposing that ACH Transfer to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how ACH Transfer will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: ACH Transfer

Required fields (eg)

Country: USA
Account owner full name
Account owner address
Bank name
Bank account number
ACH Routing number

Signing required: No

Regions accepted: USA

Currencies accepted: USD

Bisq Limits: eg 0.25 BTC

Any relevant information for mediators / arbitrators: No

Any relevant information for devs: No

Any relevant information for users: No

Screenshot of expected GUI: TBC

**Comment by pazza83** [comment]
Here is the XD for ACH, it should be straight forward to add:

![Uploading Payment method - ACH Transfer.png…]()

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx no additional information is required for the Bisq strings for ACH

**Comment by pazza83** [comment]
Wiki completed: https://bisq.wiki/ACH
