### ISSUE TITLE
Jan 18th growth call

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#22]
- **Date:** Thu Jan 18th 
 - **Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
 - **Place:** Zoom conferencing, see Call Details below

If you want to help Bisq grow, then this is the meeting to attend!

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Note also that you can subscribe to the Bisq DAO Google Calendar to get notifications about this call and other Bisq events. See https://bisq.network/calendar.

## Agenda

You'll find the general agenda of our growth calls here: https://github.com/bisq-network/growth/blob/master/docs/growth-meeting.md

As decided on our first growth call (6th of Dec '17) we will focus all our efforts for the next two months on increasing liquidity on the Bisq network.

Before we can grow the number of overall traders on the Bisq network, we first need to make sure that we have plenty of liquidity available in major trading pairs, esp. EUR and USD.
 
This means that anyone who considers themselves a potential 'market maker' or 'liquidity provider' is especially welcome on this call, to help us brainstorm ways to make Bisq an attractive place to be for you. We already have a number of ideas, and are looking to get your feedback.
 
Note that while we're happy to have pro and semi-pro traders serve as liquidity providers, we're also looking for anyone who simply has a need to sell BTC on a regular basis, e.g. for basic cash flow purposes.

**This week will be about:**
- How to bootstrap the USD/BTC market
- Discuss the possibility to use `$BSQ bounties` for new currencies (thanks @flix1 for bringing this up). What are the criterias for marking issues as `$BSQ bounties` in general?
- New markets and payment methods (e.g. CNY/BTC, Alipay,...)

Feel free to add any remarks below or points you want to discuss on this weeks growth call! 

## Call details
Join from PC, Mac, Linux, iOS or Android here: https://zoom.us/j/819505197

Or join with a touch on the iPhone : 
US:  +16699006833,,819505197#  or +16468769923,,819505197#  
Or join by phone： 
Dial in： 
US: +1 669 900 6833 or +1 646 876 9923 
Meeting-ID: 819 505 197 
International numbers available: https://zoom.us/zoomconference?m=5g8IvHLeIBIjeXlPhV3XWVE4cczQAtmu

## Comments welcome

Please add comments below with any questions you have or regarding any other topics you'd like to discuss on this call. See also the open issues in this repository.

Hope to see you there!

**Comment by cbeams** [comment]
@flix1 and I want to discuss criteria for marking issues as as a `$BSQ bounty`. This isn't strictly `growth`-related, so I'm happy to wait and see if we have time to discuss it. If not, @flix1 and I can do something 1:1 later.

**Comment by ripcurlx** [comment]
Updated agenda and fixed wrong date (thanks @flix1 for bringing this up)

**Comment by flix1** [comment]
My suggestion is that we offer bounties for first trades in a new currency... starting with a few strategic currencies that have never had a Bisq trade:

**NGN** - Nigerian Naira
**INR** - Indian Rupee
**RUB** - Russian Ruble
**ARS** - Argentinian Peso
**KRW**  - South Korean Won
**PHP** - Philippine Peso

The bounty need not be very large... maybe $BSQ 50-100 each. But doing the research and taking the risk definitely deserves an incentive.

**Comment by cbeams** [comment]
Closing as complete.

 - Video is up at https://youtu.be/f_E5PvxN_xk
 - Notes are at https://goo.gl/jakVqt (thanks, @csacher!)
 - Tweet announcing the above at https://twitter.com/bisq_network/status/955382152459321344

**Comment by csacher** [comment]
Notes of the call: https://docs.google.com/document/d/1GyuAjZ_Tz_D5bTMB8npjCu5mp6ESHCmBssT31g0vG4E/edit?usp=sharing
