### ISSUE TITLE
Add Venmo as a payment method

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#221]
## Venmo

Resources: 

- [Venmo Website](https://venmo.com/) 
- [Venmo Wiki](https://en.wikipedia.org/wiki/Venmo) 
- [Venmo help section](https://help.venmo.com/hc/en-us) 
- [Venmo T&Cs](https://venmo.com/legal/us-user-agreement/) 
- [Bisq community thread about previous issues](https://bisq.community/t/sellers-beware-heads-up-chargebacks-from-cashapp-venmo-venmo-account-frozen/5388/8)

### Why

Venmo is a popular payment service owned by PayPal. It is allows users to transfer funds to other users. 

Vemno was previously added to Bisq on around February 2018 and was discontinued in July 2018. It was suggested this could have been due to problems with the Bisq Trade ID. This is hopefully being addressed here  https://github.com/bisq-network/bisq/issues/2869

Therefore a number of Bisq users have suggested it be reconsidered for inclusion. 

There were a healthy number of trades in its short time on Bisq so I think it would be a popular option for USD trades.

### Region

Venmo is only available in the United States and only compatible with U.S. based bank accounts and phone numbers. You must also be able to send and receive SMS/text messages from short codes.

Required details are:

- Name
- Email
- Phone number
- Linked bank account
- Social Security Number
- ID Verification

[Venmo - Identity Verification](https://help.venmo.com/hc/en-us/articles/360027356113)

### Currencies

USD

### Chargeback risk

The cancel payment section looks promising: https://help.venmo.com/hc/en-us/articles/235171088-Cancel-Payment

>Venmo Support cannot reverse a payment at the sender’s request. 

But looking at the terms and conditions chargeback risk is higher than most payment methods. Due to a few of the familar Paypal buyer protection features:

See: [Venmo User Agreement](https://venmo.com/legal/us-user-agreement/)

Specifically sections on:

- Adding Money to and Transferring Money out of Your Venmo Account > Bank transfer reviews
- Refunds, Reversals and Chargebacks
- Restricted Activities
- Holds and Limitations

### Size of user base

65 million active accounts 

### Data requirements

I am not entirely sure. It seems you can make payment to your contacts. They are added by phone number or email address.

They can also be added by Facebook or their Personal "[Venmo Me](https://help.venmo.com/hc/en-us/articles/217532217-Adding-Removing-Friends-)" QR code 

### Verification

TLSNotary through web app.

### Duration

1-3 business days.*

*Transfer speeds vary and could take up to 3 business days to complete. Transfers are reviewed which may result in delays or funds being frozen or removed from your Venmo account. 

https://help.venmo.com/hc/en-us/articles/221083888-Bank-Transfer-Timeline

### Fees

$0 To sign up
$0 To send money*
$0 Monthly fees
1% Instant Transfers (with a minimum fee of $0.25 and a maximum fee of $10) I think this is to withdraw frunds to your own account.

*Venmo does not charge for sending money from a linked bank account, debit card, or your Venmo account. There is a 3% fee for sending money using a linked credit card.

[More fee info](https://venmo.com/resources/our-fees/)

### Fraud risk

Lots of documentation regarding scams, frozen accounts, chargebacks etc:

- [Payment in review](https://help.venmo.com/hc/en-us/articles/217532157-Payment-In-Review) 
- [Temporarily Frozen Account](https://help.venmo.com/hc/en-us/articles/217532077-Temporarily-Frozen-Account)
- [Frozen Account](https://help.venmo.com/hc/en-us/articles/210413707-Frozen-Account)
- [Common scams on Venmo](https://help.venmo.com/hc/en-us/articles/360048404533-Common-Scams-on-Venmo)

### Payment amounts

Unverified accounts: $299.99 per week
Verified accounts: $4,999.99 per week

[Payment Limits](https://help.venmo.com/hc/en-us/articles/221010968-Payment-Limits)

### Payment description

N/A if changed as per https://github.com/bisq-network/bisq/issues/2869

### Summary

Reading the documentation I think there are too many risks regarding chargeback for Venmo to be added to Bisq. I have never used it though so wanted to document all the above to allow for discussion.

My initial recommendation is not to add it.

**Comment by ripcurlx** [comment]
We also had Venmo integrated already in the past and had to remove it because of chargebacks.

**Comment by m52go** [comment]
Yes, as I noted [on the other thread](https://github.com/bisq-network/bisq/issues/4757#issuecomment-755860612), Venmo proactively blocks transactions it doesn't like. I think not bringing it back is the right call.

**Comment by pazza83** [comment]
Yes, these are my thoughts.

Does @RefundAgent have any comments as they suggested chargebacks where no longer possible?

**Comment by pazza83** [comment]
Closing as chargeback risk is too great.
