### ISSUE TITLE
Add Bizum as a new payment method (popular in Spain)

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#222]
## Bizum

Resources: 

[Bizum website](https://bizum.es/en/) 
[Bizum Wiki](https://es.wikipedia.org/wiki/Bizum)
[Bizum FAQs](https://bizum.es/en/frequently-asked-questions/)

Bizum is a mobile payment provider service based in Spain. Bizium is a result of the collaboration of almost all of the Spanish banks to create a system of instant payments between individuals and shopping in stores. 

### Region

Spain. You need is a bank account (IBAN) in Spain with any of the entities which offer the service and a mobile phone number.

The Bizum service is not yet available for bank accounts outside Spain. Insofar as the telephone is concerned, Bizum has no restrictions, reason why it would not be a problem to make a Bizum to foreign mobile phone numbers which have a Spanish bank account associated with those phone numbers

### Currencies

EUR

### Chargeback risk

Low

### Size of user base

13 million users

### Data requirements

The service allows payments between users using the mobile application and knowing only the recipient's phone number.

### Verification

TLSNotary can not be used as payment method is app based.  Screen recording / screenshots might be able to be used to provide payment proof.

### Duration

Instant payments, less than 10 seconds. 

When the user wants to send money, they will receive a verification text message that, along with a code, they will have to enter in the application. Once this is done, the transaction is done and the other user receives the funds instantly. The recipient also receives a text message confirming the receipt of the transferred funds.

### Fees

Free to send and receive

### Fraud risk

Low

### Payment amounts

Can be used for amounts between 0.50 and 1000 per payment

The maximum amount of transactions you can receive using Bizum is 2000 Euros per day.

- Minimum amount per operation: €0.50
- Maximum amount per operation: €1,000
- Amount of operations received per client per day: €2,000
- Number of operations issued and received by a client in a month: 150 operations
- Maximum number of recipients to be included in a multiple request/remittance: 30 recipients
- Duration of pending remittance to a Non-Client: 2 days
- Duration of the pending request to a Non-Client: 7 days

Each bank however may establish its own limits, within these limits, for its clients.

**Comment by flix1** [comment]
I can definitely confirm that this is the most widely used micro-payment method in Spain and is compatible with all banks.

**Comment by pazza83** [comment]
Bizum has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~ | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| **Traders can provide evidence of payment / receipt**  | ~~Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar~~ | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| **Maximum limits equal to at least 0.01 BTC**  | ~~Large payment limits up to 2 BTC~~  | ~~Maximum limit is less than 0.01 BTC~~  |
| **Likely to increase liquidity**  | ~~Likely to increase liquidity and open markets for different countries and currencies~~  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | **No fees for transactions** | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 23/32
Percentage: 71.88%

**Comment by pazza83** [comment]
### Bizum - Proposed National Currency Payment Method 

I am proposing that Bizum to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how Bizum will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

---


Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: Bizum

Required fields (eg)
- Account owner full name
- Phone number

Maximum trade duration: 24 hours

Signing required: No

Regions accepted: Spain

Currencies accepted: EUR

Bisq Limits: 0.04 BTC

Any relevant information for mediators / arbitrators: Verification might be via mobile screen recording if bank is app based.

Any relevant information for devs: No

Any relevant information for users: Account limits 2000 Euros per day, 1000 Euros per transaction

Screenshot of expected GUI: TBC

**Comment by pazza83** [comment]
Here is the XD for Bizum, it should be straight forward to add (main difference is buy/sell limit should be set to 0.04 BTC):

![Payment method - Bizum](https://user-images.githubusercontent.com/66367547/117579383-82e7d780-b0ea-11eb-937b-515cc932af51.png)

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

To use Bizum you need a bank account (IBAN) in Spain and to be registered for the service. 

Bizum can be used for trades between €0.50 and €1,000.

The maximum amount of transactions you can send/receive using Bizum is €2,000 Euros per day.

Bizum users can have a maximum of 150 operations per month.

Each bank however may establish its own limits, within the above limits, for its clients.

Traders on Bisq should be aware of their limits. If you trade over the above limits your trade might be cancelled and there could be a penalty.

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only to the BTC Seller's mobile phone number as provided in Bisq.

The maximum trade size is €1,000 maximum per payment. The maximum amount of transactions you can send using Bizum is €2,000 Euros per day.

If you trade over the above limits your trade might be cancelled and there could be a penalty.

### Special items to be aware about when receiving payments (for BTC Sellers):

Please make sure your payment is received from the BTC Buyer's mobile phone number as provided in Bisq.

The maximum trade size is €1,000 maximum per payment. The maximum amount of transactions you can receive using Bizum is €2,000 Euros per day.

If you trade over the above limits your trade might be cancelled and there could be a penalty.

**Comment by pazza83** [comment]
Wiki completed: https://bisq.wiki/Bizum
