### ISSUE TITLE
Add Unified Payments Interface (UPI) as a payment method (popular mobile payment service in India)

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#225]
## Unified Payments Interface (UPI) 

References:

- [Unified Payments Interface Wiki](https://en.wikipedia.org/wiki/Unified_Payments_Interface)
- [UPI video explainer](https://www.youtube.com/watch?v=6qlpG4V8jdc)
- [UPI limits](https://blog.cashfree.com/upi-transaction-limit-2020/#Bank_UPI_transaction_limit_by_amount)

### Why

India has the 5th largest economy in the world by GDP, yet Bisq does not have many options for people in India to trade. It would be good to give people in India more access to trading on Bisq.

UPI is an instant real-time payment system developed by National Payments Corporation of India facilitating inter-bank transactions. This is an umbrella organization for operating retail payments and settlement systems in India.

Around 2 Billion UPI transactions amounting to roughly $50 billion (USD) of transactions happen every month in India.

UPI is already included on almost all other P2P cryto exchanges.

### Region

India

### Currencies

INR

### Chargeback risk

Low.

Banks cannot reverse an UPI payments. According the UPI rules it is the responsibility of the sender to enter the correct beneficiary account number and other details while making payment.

### Size of user base

300 million people in India have access to a bank account and smart phone that can be registered for UPI. 2 billion transactions are sent a month.

### Data requirements

In order to make a payment or transfer funds through UPI, you must have at least one of the following details about the beneficiary:

Virtual Payment Address (VPA) also called UPI ID - The format is like an email ID: with the sign “@” in the middle. For example, your UPI ID could be “receiver’s_name@bank_name” or “phone_number@bank_name.”

To send money to someone with a UPI ID, you only need to have your receivers UPI ID. You do not need their account number, account type, bank name, or IFSC code etc.

### Verification

Payment is made on bank smart phone app. Screenshots / videos can be used for verification.

SMS messages are also sent to payer and payee to confirm payment.

### Duration

Payments are immediate. 24/7, 365 days a year.

Trade time should be set to 24 hours.

### Fees

Low. Either free or  no more then 5 INR ~ $0.07 USD per transaction.

### Fraud risk

Low

### Payment amounts

Maximum of 100,000 INR can be sent per transaction. This is approximately $1,350 USD.

Minimum payment is 1 INR ~ $0.01 USD

Some banks have different limits for their customers. The above maximums are set by the National Payments Corporation of India.

**Comment by pazza83** [comment]
See similar payment method IMPS proposal here: https://github.com/bisq-network/growth/issues/224

**Comment by pazza83** [comment]
See similar payment method PayTM proposal here: #226

**Comment by m52go** [comment]
@pazza83 might be good to prioritize this particular payment method.

![Screenshot from 2021-02-17 01-44-15](https://user-images.githubusercontent.com/735155/108166113-a0a93000-70eb-11eb-8e40-e5fdcbd9667f.png)

**Comment by pazza83** [comment]
@m52go Thanks, I agree, Indian and also Nigerian payment methods are important to develop.

Regulation on exchanges is likely to increase in the coming years. Bisq can help people a lots in these locations, and lessons learnt can be applied to future markets:

As well as UPI I have also proposed the following payment methods:

- [RTGS](https://github.com/bisq-network/growth/issues/237)
- [PayTM](https://github.com/bisq-network/growth/issues/226)
- [IMPS](https://github.com/bisq-network/growth/issues/224)
- [NEFT](https://github.com/bisq-network/growth/issues/236)

It would be great to get some feedback from users based in India. Please can you tweet a link to this issue and ask for feedback.

Cheers

**Comment by prayank23** [comment]
@pazza83 ACK for UPI and Paytm

However using gift cards can be better for users in case there is a ban in India and users are not allowed to trade bitcoin.

**Comment by pazza83** [comment]
Thanks for the info. Gift cards are a little hard to get right. Amazon eGift cards have been added but do not think they are available to purchase in India yet.

**Comment by prayank23** [comment]
> Amazon eGift cards have been added but do not think they are available to purchase in India yet.

Not sure about this. Bitrefill has giftcards that can be used here in India and you can pay with bitcoin. Paxful has gift cards as payment option.

**Comment by m52go** [comment]
> It would be great to get some feedback from users based in India.

Internet feedback is also pretty strongly in favor of prioritizing UPI.

https://twitter.com/bisq_network/status/1361941104686342146

**Comment by pazza83** [comment]
Thanks, I think it is a firm yes vote for UPI

**Comment by pazza83** [comment]
> > Amazon eGift cards have been added but do not think they are available to purchase in India yet.
> 
> Not sure about this. Bitrefill has giftcards that can be used here in India and you can pay with bitcoin. Paxful has gift cards as payment option.

I have discounted Bitrefill as a payment method as one would have to use BTC to buy BTC which seems a bit unintuitive.

Other gift cards are hard as it is not easy to verify funds. Plaxful has them, but also a lot of disputes come with them.

**Comment by prayank23** [comment]
> I have discounted Bitrefill as a payment method as one would have to use BTC to buy BTC which seems a bit unintuitive.

I mentioned Bitrefill because some traders can use it instead of selling BTC to INR. Paxful can be used to buy BTC with gift cards. So options are already available. 

> but also a lot of disputes come with them

Possible. Because lot of scammers also prefer gift cards.

**Comment by pazza83** [comment]
> I mentioned Bitrefill because some traders can use it instead of selling BTC to INR. Paxful can be used to buy BTC with gift cards. So options are already available.

Thanks, that is a usecase I had not considered. I will create an Bitrefill as a payment method for discussion.

**Comment by m52go** [comment]
From what I'm seeing this is one of the most-requested payment methods at the moment...potentially a big gateway for a big market. 

What work remains to get it implemented?

**Comment by pazza83** [comment]
Hi @m52go I have created issues for all the requested payment methods.  Just waiting for opportunity for all users to give feedback. I shared a post on Reddit, GitHub, Keybase and Bisq community forum: [New Payment Methods proposed for Bisq (Please comment on the ones you would like added)](https://bisq.community/t/new-payment-methods-proposed-for-bisq-please-comment-on-the-ones-you-would-like-added/10541) at the beginning of the month.

Idea was to get as much feedback as possible and then make propose which payment methods to add before giving the mediators and refund agents a chance to make any suggestions / objections.

UPI seems like the most popular payment method for users in India and got good feedback from your post on Twitter and my post on [Reddit](https://www.reddit.com/r/BitcoinIndia/comments/l3jru5/any_bisq_users_from_india_here/)

I would like to batch it with the other payment methods suitable for India deemed suitable for inclusion.

**Comment by m52go** [comment]
I think this payment method has gotten enough feedback to justify it being added. From a development standpoint, payment methods are not hard to add, so I'm not sure all this added time to gather feedback is worth it.

**Comment by pazza83** [comment]
Hi @m52go thanks I am keen to add UPI at the same time as other Indian payment methods see comment [here](https://github.com/bisq-network/bisq/discussions/5287#discussioncomment-622884).

Let me know if you think the current process of adding payment methods can be improved?

**Comment by pazza83** [comment]
UPI has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~  | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency** | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| ~~Significant user base~~  |  **Large user base**  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | ~~< high amount usability~~  |
| **No KYC required for sending and receiving payments** | ~~No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)~~ | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| **Traders can provide evidence of payment / receipt**  | ~~Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar~~ | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| **Maximum limits equal to at least 0.01 BTC**  | ~~Large payment limits up to 2 BTC~~  | ~~Maximum limit is less than 0.01 BTC~~  |
| ~~Likely to increase liquidity~~  | **Likely to increase liquidity and open markets for different countries and currencies**  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | **No fees for transactions**  | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 24/32
Percentage: 75%

**Comment by Aman-1412** [comment]
> Hi @m52go thanks I am keen to add UPI at the same time as other Indian payment methods see comment [here](https://github.com/bisq-network/bisq/discussions/5287#discussioncomment-622884).
> 
> Let me know if you think the current process of adding payment methods can be improved?

I'm not sure how straightforward it is to integrate new payment methods in Bisq. But when using a payment gateway like Razorpay, PayU, JusPay, etc. these allow to make payments via all of - UPI, IMPS, PayTM including Credit/Debit card and some other methods as well.

NEFT/RTGS may/may not be included in these payment gateways. However, NEFT/RTGS do amount for majority of the 'volume' transactions, given that UPI has a daily limit of 100,000 INR(fyi, 1 BTC = 411,000 INR). To have people transacting with higher amounts, NEFT/RTGS will definitely come into the play. But I agree that UPI is a great start with the lowest entry barrier for most people to start trading INR with BTC.


In March 2021, providers of unified payments interfaces (UPI) in India recorded a total of 2.7 billion digital payment transactions worth over 5 trillion INR.[1]

[1] - https://www.npci.org.in/statistics

**Comment by pazza83** [comment]
Hi @Aman-1412 thanks for the comments. Will take a look at Razorpay, PayU and JustPay once the current payment methods proposed for India have been added.

**Comment by pazza83** [comment]
## Unified Payments Interface (UPI) - Proposed National Currency Payment Method

I am proposing that Unified Payments Interface (UPI) to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how Unified Payments Interface (UPI) will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: Unified Payments Interface (UPI)

Required fields:

Country: India
Virtual Payment Address (VPA) / UPI ID

Signing required: No

Regions accepted: India

Currencies accepted: INR

Bisq Limits: eg 0.05 BTC

Maximum amount per transaction is 100,000 INR 

Trade window: 1 day

Any relevant information for mediators / arbitrators: No

Any relevant information for devs: Please set maximum limit to 0.05 BTC

Any relevant information for users: Maximum amount per transaction is 100,000 INR , payments above this will need to be sent as multiple transactions.

Screenshot of expected GUI: TBC

**Comment by pazza83** [comment]
Here is the XD for UPI, it should be straight forward to add (main difference is buy/sell limit should be set to 0.05 BTC):

![Payment method - UPI](https://user-images.githubusercontent.com/66367547/117579430-b0348580-b0ea-11eb-8be4-418d3495d854.png)

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

Please make sure to include your Virtual Payment Address (VPA) also called your UPI ID. The format for this is like an email ID: with the sign “@” in the middle. For example, your UPI ID could be “receiver’s_name@bank_name” or “phone_number@bank_name.”

For UPI there is a maximum limit of 100,000 INR that can be sent per transaction. 

If you intend to trade amount of over 100,000 INR per trade it is likely trades will have to take place over multiple transfers.

Please note some banks have different limits for their customers.

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only to the VPA / UPI ID provided in Bisq.

The maximum trade size is 100,000 INR per transaction.

If your trade is over 100,000 INR you will have to make multiple transfers.

Please note some banks have different limits for their customers.

### Special items to be aware about when receiving payments (for BTC Sellers):

If you intend to receive over 100,000 INR per trade you should expect the buyer to have to make multiple transfers.

Please note some banks have different limits for their customers.

**Comment by jmacxx** [comment]
Screenshots at https://gist.github.com/jmacxx/5d9dbdc80a7ad9e8b5847be548ed9b99#gistcomment-3902125

**Comment by pazza83** [comment]
wiki completed: https://bisq.wiki/UPI
