### ISSUE TITLE
Add PayTM as a payment method (popular mobile payment service in India)

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#226]
## PayTM 

References:

- [PayTM website](https://paytm.com/)
- [PayTM video explainer](https://www.youtube.com/watch?v=_twGGicE_OQ)
- [PayTM wallet blog post](https://blog.paytm.com/the-simple-incredible-paytm-wallet-79b2bb36d51f)
- [PayTM Wiki](https://en.wikipedia.org/wiki/Paytm)

### Why

India has the 5th largest economy in the world by GDP, yet Bisq does not have many options for people in India to trade. It would be good to give people in India more access to trading on Bisq.

Paytm is an Indian e-commerce payment system and financial technology company, based in India.

PayTM has around 350 million users. Users can send funds to each other via the PayTM wallet.

PayTM is already included on almost all other P2P cryto exchanges.

### Region

India

### Currencies

INR

### Chargeback risk

Low.

PayTM payments cannot be reversed.

### Size of user base

350 million users.

### Data requirements

In order to make a payment or transfer funds through PayTM, you just need your recipients PayTM registered email or phone number. No other information is needed.

### Verification

Payment is made on bank smart phone app. Screenshots / videos can be used for verification.

### Duration

Payments are immediate. 24/7, 365 days a year.

Trade time should be set to 24 hours.

### Fees

Free for personal use.

### Fraud risk

Low

### Payment amounts

With No KYC users are limited to 

- Maximum of 5,000 INR can be sent per transaction. This is approximately $67.5 USD.
- Maximum of 10,000 INR can be held in someone's PayTM wallet . This is approximately $135 USD.

With KYC users are limited to 

- Maximum of 100,000 INR can be sent per transaction. This is approximately $1,350 USD.
- Maximum of 100,000 INR can be held in someone's PayTM wallet . This is approximately $1,350 USD.

This means that for Bisq a KYC PayTM wallet will be practical for transactions. Users should also be aware of account limits.

**Comment by pazza83** [comment]
See similar payment method IMPS proposal here: #224

**Comment by pazza83** [comment]
See similar payment method UPI proposal here: #225

**Comment by pazza83** [comment]
PayTM has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~  | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~  | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency** | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| ~~Significant user base~~  |  **Large user base**  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | ~~< high amount usability~~  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| **Traders can provide evidence of payment / receipt**  | ~~Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar~~ | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| **Maximum limits equal to at least 0.01 BTC**  | ~~Large payment limits up to 2 BTC~~  | ~~Maximum limit is less than 0.01 BTC~~  |
| ~~Likely to increase liquidity~~  | **Likely to increase liquidity and open markets for different countries and currencies**  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | **No fees for transactions**  | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 25/32
Percentage: 78.13%

**Comment by pazza83** [comment]
## PayTM - Proposed National Currency Payment Method

I am proposing that PayTM be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how PayTM will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: PayTM

Required fields:

Country: India
Email or Phone number

Signing required: No

Regions accepted: India

Currencies accepted: INR

Bisq Limits: eg 0.05 BTC

Maximum amount per transaction is 100,000 INR 

Trade window: 1 day

Any relevant information for mediators / arbitrators: No

Any relevant information for devs: Please set maximum limit to 0.05 BTC

Any relevant information for users: Maximum amount per transaction is 100,000 INR , payments above this will need to be sent as multiple transactions.

Screenshot of expected GUI: TBC

**Comment by pazza83** [comment]
Here is the XD for PayTM, it should be straight forward to add (main difference is buy/sell limit should be set to 0.05 BTC):

![Payment method - PayTM](https://user-images.githubusercontent.com/66367547/117579402-97c46b00-b0ea-11eb-91e4-f39af9b58a1b.png)

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

Please make sure to include your email or phone number that matches your email or phone number is your PayTM account. 

When users set up a PayTM account with No KYC users are limited to:

- Maximum of 5,000 INR can be sent per transaction.
- Maximum of 10,000 INR can be held in someone's PayTM wallet.

If you intend to trade amount of over 5,000 INR per trade you will need to complete KYC with PayTM.  With KYC users are limited to:

- Maximum of 100,000 INR can be sent per transaction. This is approximately $1,350 USD.
- Maximum of 100,000 INR can be held in someone's PayTM wallet . This is approximately $1,350 USD.

Users should also be aware of account limits. Trades above PayTM account limits will likely have to take place over more than one day, or, be cancelled.

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only to the email address or phone number provided.

### Special items to be aware about when receiving payments (for BTC Sellers):

If you intend to trade amount of over 5,000 INR per trade you will need to complete KYC with PayTM.  With KYC users are limited to:

- Maximum of 100,000 INR can be sent per transaction.
- Maximum of 100,000 INR can be held in your PayTM wallet .

Users should also be aware of account limits. As a maximum of 100,000 INR can be held in your PayTM wallet please make sure you transfer out your INR regularly.

**Comment by jmacxx** [comment]
Screenshots at https://gist.github.com/jmacxx/2bcf95607373c821990e82bdcfa2c3fd#gistcomment-3902128

**Comment by pazza83** [comment]
Wiki completed: https://bisq.wiki/PayTM
