### ISSUE TITLE
Please support the cryptocurrency NANO

### ISSUE THREAD

**Issue by NigelBess** [bisq-network/growth#228]
## Learning Goal/Objective
To provide a decentralized means of liquidity for buyers and sellers of NANO.

## Hypothesis
If the experiment is successful, I believe it will significantly increase downloads and participation in the Bisq network, and increase liquidity volume across all Bisq markets by increasing its user base.

## Experiment Design
1. Create a NANO/BTC market
2. Examine the number of Bisq downloads, Bid-ask spreads across markets, and overall volume.

## Resource Estimation and Probability
This experiment would require the same amount of development effort as is required to support any other altcoin. It has a high probability of success

**Comment by m52go** [comment]
As of Cycle 9, adding new assets is on [indefinite hold](https://github.com/bisq-network/proposals/issues/166).
