### ISSUE TITLE
PostePay

### ISSUE THREAD

**Issue by PautassoEGiacomina** [bisq-network/growth#229]
### Why

I believe Bisq can implement this payment method because it is one of the most used in Italy. It is also true that in Italy cryptocurrencies are unfortunately not yet very popular, but this implementation, perhaps, could also help cryptocurrencies to acquire some users in my country.
It is very popular in Italy because it is cheap and is offered by the Italian postal company (the only one).

### Region

This payment method is in fact widely used in Italy, but it still allows you to send money to all parts of the world (that I know of).

### Currencies

Euro

### Chargeback risk

Chargeback, with this payment method, is possible (I'm reading it now because I didn't know it, and honestly I think few people know).
But I would like to point out that in Italy there is a disastrous problem of excessive bureaucracy. In fact, reading on the official website, I find that before a user is able to complete the chargeback procedure, and before some employee of this disastrous company actually confirms the entire procedure, the seller will have already had time to spend all the money arrived on your account € 1.00 at a time.

### Size of user base

A LOT of poor italians.

### Data requirements

To my knowledge, a user only needs to provide their IBAN.

### Verification

Unfortunately, I cannot answer this question. I'm sorry!

### Duration

This payment method is very fast when it comes to transferring to another PostePay account. While it has an average duration like a traditional bank, when it comes to transferring money to any account.

### Fees

I don't know the exact amount of fees, but it is a very used method in Italy, especially among the less well-off people, so I assume that it is very / quite cheap.

### Fraud risk

It is a payment method widely used by Italian scammers, because it is very difficult for a citizen to find out who is behind the IBAN of a card to which money has been sent without having anything in return. However, I believe that it is very difficult for the reverse situation to arise: that is, that someone manages to defraud someone else if the money left from his PostePay account.

### Payment amounts

Unfortunately, I don't know the minimum and maximum limits of this payment method, also because there are several account plans available. 

### Payment description

I believe there are, but I'm not 100% sure.

In case you have not understood, I cannot answer all the questions as I do not personally have this method of payment and this account.
But lately, many friends who have it and who are approaching cryptocurrencies for the first time, have asked me several times if it is possible with Bisq to use PostePay to be able to buy and sell Bitcoin.
So I hope that with this post of mine this Italian payment method can be implemented, so as to bring a lot of this beautiful country of shit closer to cryptocurrencies.

**Comment by pazza83** [comment]
Hi @PautassoEGiacomina 

Thanks for raising this issue.

The ability to chargeback would be a problem. The fact that it takes a while to complete a chargeback is not really a security benefit as PostePay could just take the funds from a future credit.

Can you add a link to the terms and conditions where it mentions anything to do with chargebacks or reversals.

Many thanks

**Comment by PautassoEGiacomina** [comment]
> Hi @PautassoEGiacomina
> 
> Thanks for raising this issue.
> 
> The ability to chargeback would be a problem. The fact that it takes a while to complete a chargeback is not really a security benefit as PostePay could just take the funds from a future credit.
> 
> Can you add a link to the terms and conditions where it mentions anything to do with chargebacks or reversals.
> 
> Many thanks

I searched their website for contractual terms and conditions, if there was anything specific about chargebacks, but I found nothing unfortunately. I fear that to get them you must necessarily go in person to the post office...

**Comment by pazza83** [comment]
is this the website? I was looking for information about chargebacks https://www.poste.it/disconoscimento-delle-operazione-di-pagamento.html

**Comment by PautassoEGiacomina** [comment]
> is this the website? I was looking for information about chargebacks https://www.poste.it/disconoscimento-delle-operazione-di-pagamento.html

Exactly, it is from this link that I had deduced the clear difficulty and the long procedure that the chargeback procedure would have involved. Now I understand, however, that this is not enough, precisely because future credits could in any case be charged.

**Comment by pazza83** [comment]
Yes, sorry I think due to the chargebacks it is not possible to add this as a payment option in Bisq
