### ISSUE TITLE
Complete the 1st trade in NGN/BTC

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#23]
Complete the first Bisq trade in Nigerian Naira (NGN/BTC) and report back with 3 lines of feedback here on the details of the trade (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

**Bounty: 50 $BSQ**

**Comment by flix1** [comment]
Most frequent payment system on Localbitcoins is **National Bank Transfer: Nigeria**. 
Volume is growing rapidly:
https://coin.dance/volume/localbitcoins/NGN

**Comment by flix1** [comment]
Traders to approach:
https://localbitcoins.com/accounts/profile/dekoma4u/
https://localbitcoins.com/accounts/profile/Zickie/
https://localbitcoins.com/accounts/profile/Terabits/

**Comment by flix1** [comment]
It was not claimed @takinbo. Feel free to do another trade and claim it.

We are also very interested in market makers in Nigeria... so if you can help or know anyone who can, there might be a bigger bounty available for that project.

**Comment by adibas03** [comment]
@takinbo are you interested in completing the trade?
We could trade have a trade between us.

**Comment by Olugbo** [comment]
working on this...

**Comment by Olugbo** [comment]
BTC sale to NGN trade added a few days ago. No takers yet

**Comment by adibas03** [comment]
@flix1 Getting an error trying to take the trade from **olugbo**
Error: security restrictions with trade created after march 1st 2019
![image](https://user-images.githubusercontent.com/6083241/64495265-b1ffd300-d28f-11e9-9a3b-2e48cc88c0b3.png)

**Comment by Olugbo** [comment]
not sure what to do now. I wasnt told there was any restriction when I set up the offer on my end

**Comment by flix1** [comment]
That restriction is supposed to be temporary and only affects some payment methods. 

I suggest you just cancel the offer and try a smaller one first, 0.01 should work.

**Comment by ripcurlx** [comment]
@adibas03 What payment method are you using? If it is a regular bank transfer than expect some changes with the upcoming release v1.1.6. With it the tmp. security limit of 0.01 BTC will only stay on major markets (EUR, USD, GBP, CAD, AUD, BRL).

**Comment by adibas03** [comment]
@ripcurlx Yea, it's a regular bank transfer.
@Olugbo have you set up a new trade?

**Comment by Olugbo** [comment]
I just setup a new trade for 0.01. Hope it works this time

**Comment by Olugbo** [comment]
@ripcurlx do you know when v1.1.6 is coming?

**Comment by ripcurlx** [comment]
I‘d say current prediction is next Monday.

**Comment by adibas03** [comment]
@Olugbo sorry for the delay.
I have initiated the trade.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/64683931-7aa64780-d484-11e9-9f3f-3801442eb85e.png)

https://bisq.network/markets/?currency=btc_ngn

Great!

**Comment by Olugbo** [comment]
> @Olugbo sorry for the delay.
> I have initiated the trade.

Thanks, I see it. Just waiting for payment to GTB

**Comment by flix1** [comment]
@adibas03 @Olugbo was this trade completed sucessfully?

Please give us some feedback on speed, problems, things Bisq can improve, etc...

Also, do you know how to claim the bounty? You have to create an issue in 
https://github.com/bisq-network/compensation/issues

**Comment by adibas03** [comment]
@flix1 
The transaction was completed successfully.

**Feedback**
*Payment method used:* National Bank transfer,
*problems encountered:* None,
*fees paid:* (Taker) 0.000078 btc / (Maker) 0.000026 btc,
*time it took to complete the trade:* about 2hr inclusive of confirmation times for payments
*suggestions for improvement:*
There needs to be more work to cover up advanced functionality except requested by an advanced user,to allow a less scary experience for a user who is not so technical, thereby opening up the service to more users.

**Comment by flix1** [comment]
Thank you @adibas03 

Are you interested in this, much bigger, bounty for Nigeria? #156

**Comment by Olugbo** [comment]
Yep

**Comment by adibas03** [comment]
@flix1 
I'd look into it

**Comment by flix1** [comment]
Bounty was successful. Closing this issue.

**Comment by Olugbo** [comment]
Hi @flix1 I dont recall if I ever made a compensation request for this. Is there a way to check? Is it too late? It's been 3 years
