### ISSUE TITLE
Add Jeton - Multi-currency payment method

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#234]
## Jeton - Multi-currency

[Jeton Website](https://www.jeton.com/)
[Jeton Fees](https://www.jeton.com/fees-limits)
[Jeton YouTube Channel](https://www.youtube.com/c/JetonWallet/videos?view=0&sort=p&flow=grid)
[Terms and conditions](https://www.jeton.com/terms-and-conditions)
[Jeton Twitter](https://twitter.com/jetonwallet)
[Jeton Blog](https://blog.jeton.com/)

### Background

From the website:

> Jeton Wallet says they are an FCA licensed e-wallet providing individuals and businesses secure and fast money transfers. Jeton provides local and global payment methods worldwide using a single platform, as well as virtual IBAN’s in select countries.
>
>Jeton’s products are designed to meet your needs whether it’s sending, receiving, or exchanging. You can manage all the activities from your phone.
>
>If you’re looking for local and global payment solutions in one account such as bank accounts, credit cards, and crypto get started with us today! 

From looking at other websites it appears that Jenton are a Cyprus / Turkish based payment provider to high risk industries such as online gambling.

### Why
Jeton seems to be an interesting small payment provider that combines multiple currencies and low fees and instant payments. They are also crypto friendly. 

### Region

Jenton say they operates in 100+ countries with 70+ payment methods including the following countries:

![Country-Site-Map1-2048x1396](https://user-images.githubusercontent.com/66367547/107891653-ee6d3f00-6f17-11eb-9103-ea5035bcea01.png)

It looks like it could offer more options to users in places like Brazil and Japan which would be great.

### Currencies
[Multiple currencies (50+)](https://blog.jeton.com/50-currencies)

![currency-symbols-list](https://user-images.githubusercontent.com/66367547/107891615-c382eb00-6f17-11eb-8246-aad6bd99d209.png)

and...

![Currencies-1024x678](https://user-images.githubusercontent.com/66367547/107891551-4d7e8400-6f17-11eb-8dcc-f28f82c9e680.png)

However on the website they also only give fees in EUR, GBP, TRY so not sure how much other currencies are supported.

### Chargeback risk
Low the terms states:

>Once the funds are credited to the recipient’s Jeton Wallet account, the transaction cannot be reversed and will be considered final.
>
>Once funds are credited to the recipient’s Jeton Account, the transaction becomes irreversible.
>
>We may suspend or terminate your Jeton Account at any time or refuse to execute or reverse a transaction if Jeton believes that you directly or indirectly use or have used your Jeton Account for or in connection with illegal gambling transactions. 
>
>You agree that in case of choosing a deposit method that is subject to a chargeback, You will not claim one unless the transaction in question was authorised without Your consent. You agree not to dispute any transactions if You have been negligent in protecting Your Account password and login details, or for reasons where La Orange Limited or Jeton has no liability (including but not limited to disputes with merchants). Jeton reserves the right to charge You a chargeback fee of up to 25 EUR as well additional fees in case Jeton has incurred any expenses in connection with such a chargeback.

### Size of user base

Jeton has over 500,000 users worldwide.

### Duration

Instant.

### Fees

It is free to deposit, withdraw funds.

Sending costs 2% of the transaction: https://www.jeton.com/fees-limits

Receiving is free for the first 6 transactions per month and then 2.5% per transaction after that.

More info about fees can be found here: https://www.jeton.com/fees-limits

### Fraud risk
Low

### How payments are made

To send money from your account to another Jeton wallet user; you can transfer any amount to another Jeton user by proving their UserID, phone number or email, amount you want to send and reference that you want the receiver to see (e.g. gift, dept, bill)

### How payments are received 

If you received a SMS, confirming that a Jeton Wallet user sent money to your account; 

- Log in to your account
- Click on Waiting Transactions section 
- Click on Accept the payment. 

*If you have enabled the 'Auto Accept' option, the amount will be directly credited to your relevant currency account. However, if you haven't got an account on that currency, it will be created automatically.

### Payment amounts

2000 Euro limit, or equivalent, per transaction.

**Comment by pazza83** [comment]
Jeton has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~  | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| ~~Singular Fiat currency~~  | **Multi-currency**  | ~~Not a payment method for fiat currency~~  |
| ~~Significant user base~~  |  ~~Large user base~~ | **No significant user base**  |
| **High usability**  | ~~High usability and great user experience~~  | ~~< high amount usability~~  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| **Maximum limits equal to at least 0.01 BTC**  | ~~Large payment limits up to 2 BTC~~ | ~~Maximum limit is less than 0.01 BTC~~  |
| **Likely to increase liquidity**  | ~~Likely to increase liquidity and open markets for different countries and currencies~~  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | ~~No fees for transactions~~  | **Fees will be a barrier to trading** |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 17/32
Percentage: 53.13%

**Comment by pazza83** [comment]
I am not recommending this payment method for addition to Bisq due to:

- Fees being a barrier to trading
- No significant user base

**Comment by asif8419** [comment]
All are well and allowed

**Comment by CAUSAGAMING23** [comment]
Please help I can’t exchange Euro to usdt 
Jeton
