### ISSUE TITLE
Add National Electronic Funds Transfer (NEFT) as a payment method (popular banking payment method in India)

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#236]
## National Electronic Funds Transfer (NEFT)

References:

- [National Electronic Funds Transfer Wiki](https://en.wikipedia.org/wiki/National_Electronic_Funds_Transfer)

### Why

India has the 5th largest economy in the world by GDP, yet Bisq does not have many options for people in India to trade. It would be good to give people in India more access to trading on Bisq.

NEFT is an electronic funds transfer system maintained by the Reserve Bank of India. NEFT enables bank customers in India to transfer funds for free between any two NEFT-enabled bank accounts.

Pretty much all bank accounts in India can make NEFT payments.

Also see: [Add Real-Time Gross Settlement (RTGS) as a payment method (popular banking payment method in India)
](https://github.com/bisq-network/growth/issues/237)

### Region

India

### Currencies

INR

### Chargeback risk

Low.
Banks cannot reverse a NEFT payments without approval from the beneficiary.  According the NEFT rules it is the responsibility of the sender to enter the correct beneficiary account number and other details while making payment.

### Size of user base

Over 600 million adults in India have access to a bank account.

### Data requirements

In order to make a payment or transfer funds through NEFT, you must have at least the following details about the beneficiary:

Name
Account number (beneficiary's unique number)
IFSC number (beneficiary's bank number)

### Verification

TLSNotary 

### Duration

Transactions are processed and settled in batches, at the end of the day including weekends and holidays.

Trade time should be set to 24 hours.

### Fees

Free to send and receive.

### Fraud risk

Low

### Payment amounts

Maximum amount limited to per transaction is Rs.50000 within India

Maximum of 50,000 INR can be sent per transaction. This is approximately $675 USD.

No minimum limit.

**Comment by pazza83** [comment]
NEFT has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~  | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| **Trade time less than one week**  | ~~Instant payment~~  | ~~Trade time more than one week~~  |
| **Singular Fiat currency** | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| ~~Significant user base~~  |  **Large user base**  | ~~No significant user base~~  |
| **High usability**  | ~~High usability and great user experience~~  | ~~< high amount usability~~  |
| **No KYC required for sending and receiving payments** | ~~No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)~~ | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| **Maximum limits equal to at least 0.01 BTC**  | ~~Large payment limits up to 2 BTC~~  | ~~Maximum limit is less than 0.01 BTC~~  |
| ~~Likely to increase liquidity~~  | **Likely to increase liquidity and open markets for different countries and currencies**  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | **No fees for transactions**  | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 23/32
Percentage: 71.86%

**Comment by pazza83** [comment]
## National Electronic Funds Transfer (NEFT) - Proposed National Currency Payment Method

I am proposing that National Electronic Funds Transfer (NEFT) to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how National Electronic Funds Transfer (NEFT) will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: National Electronic Funds Transfer (NEFT)

Required fields (eg)

Country: India
Name
Account number
IFSC number

Signing required: No

Regions accepted: India

Currencies accepted: INR

Bisq Limits: eg 0.02 BTC

Trade window: 1 day

Any relevant information for mediators / arbitrators: No

Any relevant information for devs: Please set limit to 0.02 BTC

Any relevant information for users: No

Screenshot of expected GUI: TBC

**Comment by pazza83** [comment]
Here is the XD for NEFT, it should be straight forward to add (main difference is buy/sell limit should be set to 0.02 BTC):

![Payment method - NEFT](https://user-images.githubusercontent.com/66367547/117579508-0dc8d200-b0eb-11eb-9a1b-765da6a5bf0d.png)

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

Please make sure to include your:

- Account owner full name
- Account number 
- IFSC number

These details should match your bank account that you will use for sending / receiving payments. 

Please be aware there is a maximum of 50,000 INR that can be sent per transaction. If you are trading over this amount multiple transactions will be needed.

Please note some banks have different limits for their customers.

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only to the account details provided in Bisq.

The maximum trade size is 50,000 INR per transaction.

If your trade is over 50,000 INR you will have to make multiple transfers.

Please note some banks have different limits for their customers.

### Special items to be aware about when receiving payments (for BTC Sellers):

If you intend to receive over 50,000 INR per trade you should expect the buyer to have to make multiple transfers.

Please note some banks have different limits for their customers.

**Comment by jmacxx** [comment]
Screenshots at https://gist.github.com/jmacxx/61df5ac79581bd4a6e8458a998762063#gistcomment-3902121

**Comment by pazza83** [comment]
wiki completed: https://bisq.wiki/NEFT
