### ISSUE TITLE
Add Real-Time Gross Settlement (RTGS) as a payment method (popular banking payment method in India)

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#237]
## Real-Time Gross Settlement (RTGS) 

References:

- [Real-Time Gross Settlement Wiki](https://en.wikipedia.org/wiki/Payment_and_settlement_systems_in_India#Real-time_gross_settlement)

### Why

India has the 5th largest economy in the world by GDP, yet Bisq does not have many options for people in India to trade. It would be good to give people in India more access to trading on Bisq.

RTGS is an electronic funds transfer system maintained by the Reserve Bank of India. RTGS payment enable immediate and large remittances (minimum of 200,000 INR ~$2,700 USD) by banking customers in India to transfer funds for between any two RTGS -enabled bank accounts.

Pretty much all bank accounts in India can make RTGS payments.

Also see: [Add National Electronic Funds Transfer (NEFT) as a payment method (popular banking payment method in India)
](https://github.com/bisq-network/growth/issues/236)

### Region

India

### Currencies

INR

### Chargeback risk

Low.
Banks cannot reverse a RTGS payments without approval from the beneficiary.  According the RTGS rules it is the responsibility of the sender to enter the correct beneficiary account number and other details while making payment.

### Size of user base

Over 600 million adults in India have access to a bank account.

### Data requirements

In order to make a payment or transfer funds through RTGS, you must have at least the following details about the beneficiary:

Name
Account number (beneficiary's unique number)
IFSC number (beneficiary's bank number)

### Verification

TLSNotary 

### Duration

Transactions are processed in real time. Settlement is immediate. 

Trade time should be set to 24 hours.

### Fees

Low, banks charge different fees but generally 25-50 rupees (~$0.35-0.70 USD) 

### Fraud risk

Low

### Payment amounts

Minimum amount per transaction is Rs.200,000 (~$2,700)

Maximum of 1,000,000 INR can be sent per day. This is approximately $13,500 USD.

**Comment by pazza83** [comment]
RTGS has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~  | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~  | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency** | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| ~~Significant user base~~  |  **Large user base**  | ~~No significant user base~~  |
| **High usability**  | ~~High usability and great user experience~~  | ~~< high amount usability~~  |
| **No KYC required for sending and receiving payments** | ~~No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)~~ | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | ~~No minimum limits~~  | **Minimum limit not able to achieve account limits protocols**  |
| ~~Maximum limits equal to at least 0.01 BTC~~  | **Large payment limits up to 2 BTC**  | ~~Maximum limit is less than 0.01 BTC~~  |
| ~~Likely to increase liquidity~~  | **Likely to increase liquidity and open markets for different countries and currencies**  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| **Fees should not be a barrier to trading**  | ~~No fees for transactions~~  | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 20/32
Percentage: 62.5%

**Comment by pazza83** [comment]
## Real-Time Gross Settlement (RTGS) - Proposed National Currency Payment Method

I am proposing that Real-Time Gross Settlement (RTGS) to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how Real-Time Gross Settlement (RTGS) will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

Date proposal being made: 01.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: Real-Time Gross Settlement (RTGS)

Required fields (eg)

Country: India
Name
Account number
IFSC number

Signing required: No

Regions accepted: India

Currencies accepted: INR

Bisq Limits: eg 0.05-0.25 BTC

Minimum amount per transaction is Rs.200,000 (~$2,700)

Maximum of 1,000,000 INR can be sent per day. This is approximately $13,500 USD.

Trade window: 1 day

Any relevant information for mediators / arbitrators: No

Any relevant information for devs: Please set minimum limit to 0.02 BTC, maximum limit to 0.25 BTC

Any relevant information for users: No

Screenshot of expected GUI: TBC

**Comment by pazza83** [comment]
Here is the XD for RTGS.

This one is a little different in terns of limits.

Please can MIN buy/sell limit should be set to 0.02 BTC, and a MAX buy/sell limit should be set to 0.25 BTC:

![Payment method - RTGS](https://user-images.githubusercontent.com/66367547/117579484-e5d96e80-b0ea-11eb-9968-81ffd1538f15.png)

**Comment by jmacxx** [comment]
> Please set minimum limit to 0.02 BTC

We currently do not have a way to specify a minimum limit per payment method.  Is the extra complication really necessary?  It might be better to handle that with a soft rule (in the rules/text popup).

**Comment by pazza83** [comment]
Hi @jmacxx soft rule sounds good. I will make sure the limit is specified in both the wiki and popups. I will complete them this weekend.

**Comment by m52go** [comment]
Curious, what's the reason for preferring the 0.02 BTC minimum?

Also is RTGS being prioritized over UPI?

**Comment by pazza83** [comment]
RTGS has a min transaction amount of Rs.200,000 (~$2,700).

I assume it is hard to fix a number, as BTC needs to be the constant.

I can explain in the wiki / pop-ups that the trade needs to be a min of Rs.200,000. If the trade is taken for less then Rs.200,000 than either the trade would get cancelled or both traders would have to agree on another payment method.

> Also is RTGS being prioritized over UPI?

It would be great to add all the payment methods together and then they can be promoted at once to bitcoin users of India. @jmacxx do you think that would be possible?

**Comment by timkfor69** [comment]
Has this been tested?  
Is this worth it?
And is this legit? 

Let me know im interested!! 

And have any other ideas hit me up...
Thanks 👍

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

RTGS is for payments of large trades of Rs. 200,000 or over.

When setting up your RTGS payment account please make sure to include your:

- Account owner full name
- Account number 
- IFSC number

These details should match your bank account that you will use for sending / receiving payments. 

Please be aware there is a minimum trade amount of Rs. 200,000 that can be sent per transaction. If you are trading under this amount either the trade would get cancelled or both traders would have to agree on another payment method (eg IMPS or UPI).

### Special items to be aware about when sending payments (for BTC Buyers):

Please send payment only to the account details provided in Bisq.

Please be aware there is a minimum trade amount of Rs. 200,000 that can be sent per transaction. If you are trading under this amount either the trade would get cancelled or both traders would have to agree on another payment method (eg IMPS or UPI).

### Special items to be aware about when receiving payments (for BTC Sellers):

Please be aware there is a minimum trade amount of Rs. 200,000 that can be sent per transaction. If you are trading under this amount either the trade would get cancelled or both traders would have to agree on another payment method (eg IMPS or UPI).

**Comment by jmacxx** [comment]
Screenshots at https://gist.github.com/jmacxx/0dab93fb6dcda158dd930c0ed4120290#gistcomment-3902123

**Comment by pazza83** [comment]
Wiki completed https://bisq.wiki/RTGS
