### ISSUE TITLE
Add ATH Móvil as a new payment method  (Popular payment service in Puerto Rico)

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#238]
Reopening the proposal for Add ATH Móvil as a new payment method  as discussed [previously](github.com/bisq-network/bisq/issues/1868) and rekindled by @btcpuertorico

##  ATH Móvil (Puerto Rico)

References: 

- [ATH Móvil website](portal.athmovil.com) 
- [ATH Móvil website 2](https://escaneaypaga.com/)
- [Participating banks](https://portal.athmovil.com/terminos)
- [Terms](https://portal.athmovil.com/downloads/evertec-inc-terminos-y-condiciones.pdf)
- [ATH Móvil Youtube](https://www.youtube.com/user/athpr)

ATH Móvil is a mobile payments application developed by [Evertec Inc](https://evertecinc.com/). It allowing users with bank accounts in Puerto Rico to send and receive money instantly to each other, for free. 

### Region / Currencies

ATH Móvil is currently only offered in Puerto Rico and only supports USD.

### Account verification

Users with accounts at any of the [listed banks](portal.athmovil.com/terminos) can open an account.

### Chargeback risk

Low.

It is not obvious on the terms but @btcpuertorico informs me it is extremely difficult, almost non existent and they they have not heard of any case of chargebacks.

### Size of user base

1 million users (third of the population of Puerto Rico)

### Prohibited Uses

Unknown

### Data requirements

You only need the phone number of the other person.

### Verification

Mobile app so screenshot / video will be needed.

You also receive confirmation email with name, phone number and amount transferred.

### Duration

Immediate.

### Fees

Free for individuals.

### Limits

$500 per day. 

This would make limits low at current prices <0.01 BTC not sure if this would be do-able on layer. Remains to be seen if miner fees will reduce back to levels to allow trading of less than 0.01 BTC being practical.

### Fraud risk

Low.

**Comment by btcpuertorico** [comment]
Thank you @pazza83 !
In terms of the $500 limit, I forgot to add that you can have multiple accounts defined from different banks or credit unions and the limit is enforced on each. So the sender could exceed the $500 limit by using other accounts on the app and perform multiple transactions on the same day.

**Comment by pazza83** [comment]
Thanks that is useful to know. $500 USD is about 0.01 BTC at the moment and it would be useful for payment methods to make payments for larger amounts of BTC.

**Comment by tonyox-ops** [comment]
This would help so much with bitcoin in Puerto Rico.  Used Ath movil in localbitcoins a few times in the past and no problems with it.  Currently buying in Bitcoin Atm to skip KYC

I was talking with my friends about the possibility of Ath movil joining bisq and they love the idea.

**Comment by pazza83** [comment]
Hi @tonyox-ops thanks for creating an account. It is great to get feedback.

One of the issues above is the limits.

Do ATH Móvil account holders generally have multiple bank accounts linked? 

A $500 USD limit is a little low for Bisq trades due to miner fees often eating into the trade amount.

What amount per trade do you think would be feasible for trades using ATH Móvil?

**Comment by pazza83** [comment]
ATH Móvil has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| ~~Way to verify the sender in the received payment~~ | **Way to verify the sender in the received payment and ability to enter a reference**  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| **No KYC required for sending and receiving payments** | ~~No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)~~ | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| **Traders can provide evidence of payment / receipt**  | ~~Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar~~ | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| ~~Maximum limits equal to at least 0.01 BTC~~  | ~~Large payment limits up to 2 BTC~~  | **Maximum limit is less than 0.01 BTC**  |
| **Likely to increase liquidity**  | ~~Likely to increase liquidity and open markets for different countries and currencies~~  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| ~~Fees should not be a barrier to trading~~  | **No fees for transactions**  | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 19/32
Percentage: 59.38%

**Comment by pazza83** [comment]
The above payment methods would be suitable if it were not for the low limits of around 0.01 BTC max transaction limit or under. I think this will likely cause issues in the months ahead and, therefore, these payment methods can be re-visited when the on chain miner fee problems have been reduced.

**Comment by cachicamo-blue** [comment]
tonyox-ops . [tonyox-ops](https://github.com/tonyox-ops) . 
You can use LNP2PBOT in Telegram to small buying of btc. I am using that option to adquire sats.
