### ISSUE TITLE
Complete the 1st trade in INR/BTC

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#24]
Complete the first Bisq trade in Indian Rupees (INR/BTC) and report back with 3 lines of feedback here on the details of the trade (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

**Bounty: 50 $BSQ**

**Comment by flix1** [comment]
Most Localbitcoin offers for India are with **IMPS Bank Transfer India**. 
Also used: 
-National Bank Transfer: India. 
-Neteller
-PayTM
-Skrill
-Tez (Phonepay)

Medium volume. Stable.
https://coin.dance/volume/localbitcoins/INR

**Comment by flix1** [comment]
Traders to approach:
https://localbitcoins.com/accounts/profile/zhaodong1982/
https://localbitcoins.com/accounts/profile/Pragyay/

**Comment by flix1** [comment]
First trade in INR has been completed.

**Comment by arjun2503** [comment]
Can we setup INR bank accounts with bisq?

**Comment by ManfredKarrer** [comment]
Yes you select national bank transfer as payment method and select India as country.

**Comment by flix1** [comment]
@arjun check out this tutotial on how to do that:

How to buy bitcoin with Indian Rupees using Bisq
https://youtu.be/dpoaGKZtLkk

**Comment by flix1** [comment]
It looks like we might get some trades in India soon:

https://twitter.com/flix1/status/1121365061837180930

![image](https://user-images.githubusercontent.com/4233784/56731307-7c33d500-675a-11e9-9568-3e8668d2cd3f.png)

Someone is making a market
https://bisq.network/markets/?currency=btc_inr

**Comment by flix1** [comment]
Chicken and egg problem again. Over the past month we've had several different users posting INR offers... but never at the same time. https://bisq.network/markets/?currency=btc_inr

It's always the same **coordination problem**. 

The only solution I can think of is contacting interested parties and doing a liquidity event to get them all to be there at the same time.

**Comment by huey735** [comment]
We need to advertise "busy hours" in order to coordinate and kick-start new markets. Let's assume most people are at their computer from 17h00 to 22h00, this should be the time-frame advertised to expect loads of offers. The idea that one has to leave their computer 24/7 to keep their offers online repels people from Bisq.
And I think this info should be advertised inside the software as it is the only place we can know for sure that all traders will look at. That and maybe bisq.network/markets

**Comment by HarryMacfinned** [comment]
I agree about providing such information.
But I'm not sure that the software is the good place (already well busy).

**Comment by flix1** [comment]
Bounty failed. No takers after 1 year.

Closing this issue.
