### ISSUE TITLE
conducting offline bisq demo events to acquire new users

### ISSUE THREAD

**Issue by VlVEK** [bisq-network/growth#257]
## Learning Goal/Objective

- bisq is a complex software for new users who don't self custody & haven't used bitcoin on-chain before but familiar with CEX's
- the first trade on bisq is the most difficult part for new users considering how we are programmed to handle money - making a security deposit, counterparty risk, loss of coins are the key issues to be addressed for new users
- our objective is to make the first trade for a new user risk free using an offline trust from a bisq contributor

## Hypothesis
- conducting offline demo events by a bisq contributor creates the necessary trust for new users to do their first trade
- each event should focus on getting at least 5 people to do minimum 5 trades on bisq at the demo event
- once the first trade is successfully completed on the blockchain the users tend to come back to bisq for repeat trades and also transfer their discovered trust to other people in their community

## Experiment Design
- selecting the right venue, time and the city with potential bisq users - this could be done through polls, past community events in that city, interest of potential users to travel to that city
- the contributor eligible to conduct these events must satisfy the criteria laid in the [this comprehensive handbook](https://cryptpad.fr/pad/#/2/pad/view/3Zp0c6z0P4gCUw3n0IzNYjXJT3C+Egbajtz2U7rGzC0/) for a comprehensive overview of tactics, strategies, and lessons from past efforts:
1. A local person must lead the project
2. The person must already be familiar with self custody of Bitcoin and on-chain transactions
3. The person must be sufficiently compensated for conducting these events and their time 
4. The person must have have done 5-10 *real money* trades on bisq across markets, currency and payment methods
5. Marketing and communication can help solve the coordination problem
- marketing and communication of the event and offering additional learning content about bitcoin apart from bisq
- the event should be either free or ticketed with a very small amount of less than $5 to enforce commitment
- there could be an optional distribution of bisq merchandise at these events

## Resource Estimation and Probability
- conducting these events at a smaller scale of 5-10 people & upto 50 people can be handled by one contributor
- pre-event activity - identifying the venue, marketing the event - social media / word of mouth / others, sending invites, reaching out to prior users who requested such help 
- the event activity - a brief about bisq, conducting a live trade and encouraging users to trade amongst themselves 
- post event activity - obtaining feedback from the users, monitoring growth of trades in the relevant currency market 
- the probability of offline demo events to get new users do their first trade is expected around 80% - 8 out 10 people who attend the event are expected to their first trade on bisq

## Results
> _- What happened?_
> _- Did we succeed or fail?_
> _- What data did we collect?_
> _- Anything unexpected?_
> _- How close have we been to our prediction?_
> _- Why did we see the result that we did?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by m52go** [comment]
This sounds quite thorough. I appreciate the thought and research you put into it!

You might find the following resources helpful:
- [this deck (conceptual)](https://docs.google.com/presentation/d/1rYeR64mML5VoTV_KgTTeTQJznuIFjC6_82qThuu22_Y/edit?usp=sharing) from [this thread](https://github.com/bisq-network/growth/issues/204)
- [this walk-through by BTC Sessions](https://www.youtube.com/watch?v=4LyEKA5Iq9I) (great, accessible overview)
- [this workshop](https://bitcointv.com/w/nykLUNPcQupxtKjSwzgNh7) (hands-on)
- [protocol and incentives](https://www.youtube.com/watch?v=slhHF1zoLd4) (excellent but more advanced)

Each item above takes a slightly different approach. In case you haven't already come across them, maybe they can help you with your approach.

Do you already have such an event planned? If you like, we have some Bisq t-shirts we could send.

**Comment by VlVEK** [comment]
Thank you for the appreciation @m52go
> This sounds quite thorough. I appreciate the thought and research you put into it!

The idea here is to create a template for offline events so that a contributor can quickly propose an event, estimate the compensation and conduct it in the relevant growth market

This deck is useful and cuts down a lot of required work, just some local customisation and good to go
> * [this deck (conceptual)](https://docs.google.com/presentation/d/1rYeR64mML5VoTV_KgTTeTQJznuIFjC6_82qThuu22_Y/edit?usp=sharing) from [this thread](https://github.com/bisq-network/growth/issues/204)

These are good ideas to perform the demo live at the event
> * [this walk-through by BTC Sessions](https://www.youtube.com/watch?v=4LyEKA5Iq9I) (great, accessible overview)
> * [this workshop](https://bitcointv.com/w/nykLUNPcQupxtKjSwzgNh7) (hands-on)

This part was interesting and it actually helped me understand the logic behind having mediation & arbitration
> * [protocol and incentives](https://www.youtube.com/watch?v=slhHF1zoLd4) (excellent but more advanced)

One thing that could be added to the demo is that the entire trade can be demonstrated on the blockchain, this gave me more confidence in using bisq
> Each item above takes a slightly different approach. In case you haven't already come across them, maybe they can help you with your approach.

I don't have an event currently planned but I'm considering conducting one in the BTC/INR market as people do write to me to explain how to trade on bisq. However the last time I had planned a casual coffee, few anons confirmed their participation but didn't turn up. Based on your experience, what format works the best & does it makes sense to have a small ticketed entry?
> Do you already have such an event planned? If you like, we have some Bisq t-shirts we could send.

Bisq T-shirts would be a good thing to promote. Would it be cheaper to send it to india or get it printed here?

For my own curiosity, do you have any deck or a video on how the Bisq DAO works?

**Comment by VlVEK** [comment]
i have planned a [bitcoiners meet-up event in Goa](https://bitly.com/bitcoingoa) on Dec 25 & 26, 2021 announced on [twitter](https://twitter.com/VlVEK/status/1467441134758629376) and have tried to make it sustainable with tickets

i'm expecting max 10 people at the event and will proceed even with 4-5 confirmations

there is an uncertainty in india regarding mandating KYC, penalising for self custody & using bitcoin as a means of payment  however no such bill has yet been presented or made into a law - the current session of the indian parliament ends on Dec 23

this is a good opportunity for us to conduct this event and create the BTC/INR market now before the possibility of an unfavourable outcome

i'm expecting the DAO to sponsor marketing materials for the event as follows:
1. Orange Puma caps with bisq logo - Qty 20 - INR 14,610 ($ 193)
![bisq cap](https://user-images.githubusercontent.com/9716633/145665733-0afe3e8d-a93c-4e18-9b99-6358782fdf36.jpg)

2. Laptop Skins with full bisq cat logo - Qty 20 - INR 2,800 ($ 37)
![laptop skin](https://user-images.githubusercontent.com/9716633/145665741-31a39e1b-98e8-4157-87c1-984c857aae2d.jpg)

3. Jute bags with full bisq cat logo & slogan - Qty 30 (min) - INR 5,374 ($ 71)
![jute bag](https://user-images.githubusercontent.com/9716633/145665745-7a445b27-19be-453f-8887-fca9eed84812.jpg)

4. Notepads with KYC is illicit activity banner - Qty 20 - INR 1,700 ($ 23)
![notepad](https://user-images.githubusercontent.com/9716633/145665747-1c8ed1ba-5473-44a1-aead-12343fc97fa7.jpg)

5. Pencils with bisq green logo & name - Qty 20 - INR 380 ( $ 5)
![pencil](https://user-images.githubusercontent.com/9716633/145665749-4d1be7c0-92e7-4a1c-9422-51775af3343f.jpg)

Total INR 24,864 ($ 329) - i'll place this order after the approval from the DAO
The left over materials can be used for future events

in terms of compensation i'm expecting the DAO to revise the [BTC INR bounty from 500 BSQ](bisq-network/growth/issues/175 ) to 1000 BSQ as has been awarded for other markets. I understand that the price of BSQ has gone up however it may go down too. INR market is much tougher and difficult to create but is more rewarding if we can get it started. This bounty would be payable only if we are successful in getting the BTC/INR market started post this event.

**Comment by pazza83** [comment]
I contacted r/bitcoinindia on Reddit and they have agreed with my request to feature the Bisq advert on their subreddit sidebar. It can bee seen here: https://www.reddit.com/r/BitcoinIndia/

Many thanks to them for agreeing to feature Bisq on their subreddit.

![bitcoin india](https://user-images.githubusercontent.com/66367547/145692298-bbdc531e-809a-4d98-be63-cff99f6d5940.png)

**Comment by VlVEK** [comment]
@pazza83 this is good but how does this translates to trades on bisq?

there's a chicken and egg problem with having either no sellers with a good stack or people not having enough bitcoin to pay the security deposit or some not even unable to understand the complex software interface
1.
<img src="https://user-images.githubusercontent.com/9716633/145718625-f29f9a52-ffa2-4427-a3b0-8e31fc5208a5.png" width="40%" height="40%">
2.
<img src="https://user-images.githubusercontent.com/9716633/145718711-a1370308-a72f-42ba-822f-e35c332fe5ab.png" width="40%" height="40%">
3.
<img src="https://user-images.githubusercontent.com/9716633/145718793-65157a1a-c980-40db-aa8e-4cd5da16b998.png" width="40%" height="40%">

my understanding is BTC/INR market won't start until you have 5-10 people in one room trading together & someone present to resolve their issues

i have already invested enough time, effort and sats to get the word out and trying to help in whatever way i can but i don't have more bandwidth left hence i'm withdrawing from this initiative

further i'm not comfortable in using the overseas market at present hence i would be back on bisq when there's an active BTC/INR market 

it was a good learning experience and keep going with your effort!

**Comment by m52go** [comment]
@VlVEK ah darn was so encouraged by your previous posts :(

Are you still having the event in Goa? Maybe seeing the process in-person will help some of these people.

The issues you mentioned are similar to what we heard from efforts in China, which is why that effort ultimately failed.
