### ISSUE TITLE
Bisq.eth

### ISSUE THREAD

**Issue by osemars** [bisq-network/growth#261]
Hi, I was lucky to acquire Bisq.eth and would like to hand it over to the team. Is there someone I can talk to?

**Comment by m52go** [comment]
@osemars appreciate it but not sure we have any use for it. But please take good care of it and don't let it be taken over by scammers!

**Comment by m52go** [comment]
@bisq-network/growth-maintainers this can probably be closed.

**Comment by osemars** [comment]
cool. Yh it can be closed. Thanks

**Comment by osemars** [comment]
Thanks for the response. Could you reach out to me via my email okojieose111@gmail.com. At some point I might be tempted to get rid of it. So I know who to talk to.

**Comment by osemars** [comment]
realistically I might want to sell if I get a good offer
