### ISSUE TITLE
Complete the 1st trade in GHS/BTC 

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#29]
Complete the first Bisq trade in Ghanaian Cedis (GHS/BTC) on Bisq.

Report back here with 3 lines of feedback on the details of the trade (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

**Bounty: 50 $BSQ**

**Comment by flix1** [comment]
Localbitcoins Ghana has a few offers, most with **Cash deposit: MTN Mobile money with Ghanaian Cedi (GHS)**. Low volume.

**Comment by flix1** [comment]
Potential traders to approach with trades in Ghana:
https://localbitcoins.com/accounts/profile/DHIGANE/
https://localbitcoins.com/accounts/profile/MasterBTC/
https://localbitcoins.com/accounts/profile/pixelGH/

**Comment by cbeams** [comment]
Thanks, @flix1. I just tweeted about this here: https://twitter.com/bisq_network/status/1053234000603570177

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/47647381-1b468e00-db77-11e8-829f-829f4cdef864.png)

18th and 19th October.
