### ISSUE TITLE
Produce "How to buy bitcoin with $XYZ using Bisq" videos

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#4]
... where $XYZ is a given fiat currency, e.g. $EUR, $USD, $INR, $NGN, etc.

Screencap
< 5m
"How to" 

Videos must be short (5m) and show real examples of use in screen capture format. Simultaneous narration of the steps taken onscreen can also be helpful.

---------------
A bounty is going to be put on each of these videos.

For a video to be acceptable to receive the bounty:
-It must be published on YouTube or Vimeo.
-Image and sound quality must be good, if not necessarily professional.
-It must NOT be longer than 5 minutes.
-Video creator must allow it to be published in Bisq's own Youtube channel (with credit to creator).
-Narration must be in English, clear voice, easily understandable.
-It must show a real trade from start to end. Time skips are allowed to keep it to 5 mins.

**Comment by ripcurlx** [comment]
As discussed on [Slack](https://bisq.network/slack-invite) this could be a great way to onboard pro and noob players alike.

I'm very in favor of this idea, as it would help us to find out, if videos are more convincing to try out Bisq than plain text - we might already know the outcome of this ;-)

Uploading it to Youtube or a similar video hosting provider it would also enable us to easily track any conversions coming from this channel. If the video is shared and embedded on different site, we still could include an encoded link within the video as annotation (if supported by video hosting provider)

At the moment the referral traffic from youtube is about 0.06%, so there is plenty of room to grow :-)

**Comment by ripcurlx** [comment]
Just for completeness I'm adding example content/titles for the screencasts (kudos to @flix1 ):

- "How to buy Bitcoin with Euros on Bisq"
- "How to buy Bitcoin with GBP on Bisq"
- "How to buy ETH with BTC on Bisq"...

**Comment by flix1** [comment]
A bounty is going to be put on each of these videos.

For a video to be acceptable to receive the bounty:
-It must be published on YouTube or Vimeo.
-Image and sound quality must be good, if not necessarily professional.
-It must NOT be longer than 5 minutes.
-Video creator must allow it to be published in Bisq's own Youtube channel (with credit to creator).
-Narration must be in English, clear voice, easily understandable.
-It must show a real trade from start to end. Time skips are allowed to keep it to 5 mins.

**Comment by cbeams** [comment]
Work on the first of these videos is being managed at bisq-network/youtube#1. Thanks @flix1 and @leomcy for taking this on!
