### ISSUE TITLE
BTC/GBP Bisq Liquidity Week (Apr 2-8)

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#42]
## Learning Goal/Objective
Provide enough liquidity for the BTC/GBP order book to bootstrap the market for organic growth. Lasting 1 week from **April 2nd to 8th 2018**.

Objective: 5 traders placing 10 offers on the BTC/GBP order book for a week.

## Hypothesis
If the experiment is successful, we predict to the total volume to grow by 30% compared to the previous week.

## Experiment Design
Every participant on the experiment tries to keep two offers (1 buy, 1 sell ) open all the time to provide liquidity.

## Bounty
Participants in the experiment who meet the above requirement (creating at least 2 offers during the week) will be rewarded with **20 $BSQ**.

## Resource Estimation and Probability
Low personal effort and High probability that it will succeed.

## Results
> _- What happened?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by flix1** [comment]
How to buy bitcoin with British pounds using Bisq
https://youtu.be/sh0_VuA0fmI

**Comment by tomatopeel** [comment]
Ah I can definitely participate in this, count me in :)

**Comment by flix1** [comment]
@ripcurlx please add dates to description and title. We will start to promote this.

**Comment by ripcurlx** [comment]
@flix1 Just updated the issue with the correct time frame.

**Comment by tomatopeel** [comment]
I've put two offers up, early I know. Let me know if there's anything I need to do to prove this or keep track of them in some way in case I need to prove it later.

**Comment by flix1** [comment]
A good start!
[https://files.slack.com/files-pri/T0336TYT4-FA0CW4Q8P/image.png](url)

**Comment by flix1** [comment]
17
![image](https://user-images.githubusercontent.com/4233784/38197284-bb7ebfa4-3687-11e8-85fe-2b7ed0207e0e.png)

**Comment by flix1** [comment]
https://coin.dance/volume/bisq/GBP

![image](https://user-images.githubusercontent.com/4233784/38490124-80eda0b0-3be8-11e8-9eb7-7c10b5346678.png)
