### ISSUE TITLE
BTC/CAD Bisq Liquidity Week (22nd - 28th May)

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#43]
## Learning Goal/Objective
Provide enough liquidity for the BTC/CAD order book to bootstrap the market for organic growth. Lasting 1 week from 22nd until 28th of May.

Objective: 5 traders placing 10 offers on the BTC/CAD order book for a week.

## Hypothesis
If the experiment is successful, we predict to the total volume to grow by 30% compared to the previous week.

## Experiment Design
Every participant on the experiment tries to keep two offers (1 buy, 1 sell ) open all the time to provide liquidity.

## Bounty
Participants in the experiment who meet the above requirement (creating at least 2 offers during the week) will be rewarded with **20 $BSQ**.

## Resource Estimation and Probability
Low personal effort and High probability that it will succeed.

## Results
> _- What happened?_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by j3ko** [comment]
I will be participating in this!

**Comment by dsbeasley** [comment]
Although I live in the US, I would be willing to obtain CAD to facilitate liquidity in this market. Thoughts?

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/39351735-be68e5ee-4a02-11e8-84bd-18702eb89c68.png)

CAD/BTC already looking great!

**Comment by ripcurlx** [comment]
@dsbeasley Most of the trades that took place so far in the BTC/CAD market are with Interac e-Transfer (http://www.interac.ca/en/interac-e-transfer-consumer.html). For that I think you need a canadian bank account, but I'm not sure if there are partner banks in the US you could also use to trade.

**Comment by flix1** [comment]
Revolut and OKPay also have CAD.

**Comment by flix1** [comment]
We have transmit the message that given current liquidity levels a handful of people can make a very big difference with very little effort.

**Comment by ripcurlx** [comment]
I just moved the date of the liquidity week for one day, because of a public holiday in Canada. Happy trading from now on!
