### ISSUE TITLE
Bisq September Market Kick-Start Day [September 20th]

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#67]
## What
On September 20th 2018 we will try to get as many people as possible to place offers on Bisq as a way to kick-start liquidity after the summer and also launch the newest release. 

## Objective
Reach maximum number of offers published during 1 day.

## Hypothesis
If we can reach 300 offers published on one day we will see a new high in number of trades.

## Experiment Design
**IF** offers >**300** 
**THEN**  trades > **50**

## Bounty
Participants in the experiment  (creating at least 1 offer on this day) will be rewarded with **10 $BSQ**.

Please add a 👍 below if you will participate!

**Comment by flix1** [comment]
To reach 300 offers we would need  60 users x 5 offers each. It won't be easy, but it can be done.

We should definitely use this day to do some live demos of trades for different currencies/payment methods and show the offer book live...

**Comment by flix1** [comment]
In think the key to reaching this goal will be to set the date with plenty of lead time and promote heavily, making sure to communicate to all current and potential Bisq users.

**Comment by ManfredKarrer** [comment]
Great initiative!

**Comment by flix1** [comment]
Things we can do as part of the Kick-start day (all ideas welcome):

*Communication*
-Post reminders 10, 5, 1 day before on all social media (Twitter, reddit, bitcointalk, etc).
-Live tweet on September 20th with how it's going.
-Live hangout with tutorials, demos. Showcase payment methods, etc.

*Recruit*
-Try to get at least 30 people to commit to participating in advance. Recruit from Slack, Reddit, Bitcointalk. Approach Localbitcoin traders.
-Ideally get them to post here saying that they are in.

-Recruit at least 2 participants from China. 
-Recruit at least 2 participants from Mexico.
-Recruit at least 2 participants from India.
-Recruit at least 2 participants from South Africa. 
-Recruit at least 2 participants from Russia.

**Comment by flix1** [comment]
So far 10 people have given the thumbs up indicating that they will participate!  

@ManfredKarrer @ripcurlx @alfsbs @meapistol @cryptagoras @m52go @blabno @yagamidev @MattNguyen @flix1 

Please try to find 2 friends each and help us get to 30!

**Comment by cadayton** [comment]
Make that 11.

**Comment by fedegrc** [comment]
I think that it could be usefull create a list of Issues and Pull requests that should be solved before September 20th. 
- https://github.com/bisq-network/bisq-desktop/issues/1525

**Comment by flix1** [comment]
16 people have already given a thumbs up! 

My confidence is growing that we can get to 30 participants by Sept 20th!

Please help get the word out.

**Comment by princeofeth** [comment]
Will be participating as well, will be doing buy and sell orders for aud/btc and xmr/btc. Question though, is there a specific time(UTC) this will be starting.

**Comment by flix1** [comment]
@pricenofeth Let's say from 0:00 GMT to 23:55 GMT. 

But in reality many of us will probably start placing offers from the previous day and leave them on for more than the 20th. But any effort is welcome. Even if you can only keep your offers on for a few hours on the 20th, that's better than nothing.

**Comment by flix1** [comment]
21!

Let's try to get to 30!

**Comment by cbeams** [comment]
FYI, I plan to start promoting this via Twitter on Monday the 10th—10 days out from the event.

**Comment by pfergi42** [comment]
Sounds good. I'm in. I'll help retweet on the twitterverse too.

**Comment by flix1** [comment]
A bit of publicity for September 20th:

P2P Exchange Bisq: “It Doesn’t Get More Decentralized Than This”
https://bitcoinnews.com/p2p-exchange-bisq-it-doesnt-get-more-decentralized-than-this/

Decentralized Exchange Bisq Launches Mobile App, Holds Market Kickstart Event
https://news.bitcoin.com/decentralized-exchange-bisq-launches-mobile-app-holds-market-kickstart-event/

How to Buy Bitcoin Without Disclosing Your Identity
https://news.bitcoin.com/how-to-buy-bitcoin-without-disclosing-your-identity/

**Comment by ManfredKarrer** [comment]
@flix1 Great to get the word out!

**Comment by flix1** [comment]
Only 7 days to go! 

Surely we can get to 30 thumbs ups....

**Comment by flix1** [comment]
3 days to go!

This is already looking great... let's give it a last push

**Comment by flix1** [comment]
Stickied in reddit:
https://www.reddit.com/r/Bitcoin/comments/9glgfq/bisq_the_decentralized_exchange/

**Comment by flix1** [comment]
1 day to go! 

We have 38 commitments. 

If we can reach 40 and each person places 5 offers that should get us to 200.

However if we each try to get one more person in these 24 hours we should be able to reach 300. Let's go for it!

**Comment by flix1** [comment]
Right now this is how the order book looks:

![image](https://user-images.githubusercontent.com/4233784/45739511-7f2e7c00-bbf3-11e8-9995-6212792d954a.png)

**Comment by cbeams** [comment]
We're already over 200 offers, a record as far as I know (I've personally never seen more than 197, IIRC).

![image](https://user-images.githubusercontent.com/301810/45808203-8cb43680-bcc5-11e8-8e4d-36c83f183ecc.png)

Please keep the offers rolling in, and here's a tweet targeted at new users that you can retweet: https://twitter.com/bisq_network/status/1042701314713640960

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/45814418-d1e06480-bcd5-11e8-81b4-242e35e4b257.png)

212 now...

**Comment by flix1** [comment]
Volume is also looking good!

![image](https://user-images.githubusercontent.com/4233784/45816430-e7588d00-bcdb-11e8-9b9c-26dc470dab65.png)

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/45823380-da449980-bced-11e8-84cb-963fa2b582ae.png)

237!

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/45841461-345b5400-bd1a-11e8-8e0d-2b6b44b02a2f.png)

261 offers!

**Comment by flix1** [comment]
75 trades so far...

![image](https://user-images.githubusercontent.com/4233784/45841504-4f2dc880-bd1a-11e8-9433-c7be6b3dc25b.png)

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/45877430-10d9ed00-bd9e-11e8-85e0-0f7f70fb6237.png)

Final tally was very positive! Over 100 trades and $300k, 50 BTC volume.

![image](https://user-images.githubusercontent.com/4233784/45877463-29e29e00-bd9e-11e8-8740-b32109ee423b.png)

**Comment by flix1** [comment]
Anyone who participated can claim the 10 $BSQ bounty by creating a compensation request here:
https://github.com/bisq-network/compensation/issues

Just copy the format of previous ones and make sure to title it "Kick Start day bounty"

**Comment by flix1** [comment]
Hey @ripcurlx feel free to close this issue. I don't think I can.

**Comment by ripcurlx** [comment]
Closing as complete.
