### ISSUE TITLE
2019.01.31 Growth call

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#89]
Details for the next growth call:
- **Date:** Thursday 31 January 2019
 - **Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
 - **Place:** YouTube Live Stream (see Call Details below)

If you want to help Bisq grow, this is the meeting to attend!

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Note also that you can subscribe to the Bisq DAO Google Calendar to get notifications about this call and other Bisq events. See https://bisq.network/calendar.

## Agenda

You'll find the general agenda of our growth calls here: 
https://github.com/bisq-network/growth/blob/master/docs/growth-meeting.md

As determined on our first growth call (06 Dec 2017) we will focus all our efforts for the next few months on increasing liquidity on the Bisq network.

Before we can grow the number of overall traders on the Bisq network, we first need to make sure that we have plenty of liquidity available in major trading pairs, especially EUR and USD.
 
This means that anyone who considers themselves a potential _market maker_ or _liquidity provider_ is especially welcome on this call, to help us brainstorm ways to make Bisq an attractive place to trade. We already have a number of ideas, and are looking to get your feedback.
 
Note that while we're happy to have pro and semi-pro traders serve as liquidity providers, we're also looking for anyone who simply has a need to sell BTC on a regular basis, e.g. for basic cash flow purposes.

**This week's agenda:**
- end-of-month market update
- GRIN de-listing
- brief update on India
- go through making DAO proposal (+ discuss having a special call series on the DAO)

Feel free to add any items you'd like to cover below!

## Call details
YouTube link (watch and comment in chat):
- https://youtu.be/d0Zgo-O546k

Hangouts link (participate in discussion:
- https://hangouts.google.com/hangouts/_/532ngwnyzrd3pbieic6yxxdzyye

## Comments welcome

Please add comments below with any questions you have or regarding any other topics you'd like to discuss on this call.

Hope to see you there!

**Comment by ripcurlx** [comment]
@m52go I could do the intro and market update this time and would hand over to @ManfredKarrer for the Grin de-listing. For the rest it would be great if you could take over. What do you think?

**Comment by m52go** [comment]
@ripcurlx sounds good.
