### ISSUE TITLE
2019.02.07 Growth call

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#91]
Details for the next growth call:
- **Date:** Thursday 07 February 2019
 - **Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
 - **Place:** YouTube Live Stream (see Call Details below)

If you want to help Bisq grow, this is the meeting to attend!

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Note also that you can subscribe to the Bisq DAO Google Calendar to get notifications about this call and other Bisq events. See https://bisq.network/calendar.

## Agenda

You'll find the general agenda of our growth calls here: 
https://github.com/bisq-network/growth/blob/master/docs/growth-meeting.md

As determined on our first growth call (06 Dec 2017) we will focus all our efforts for the next few months on increasing liquidity on the Bisq network.

Before we can grow the number of overall traders on the Bisq network, we first need to make sure that we have plenty of liquidity available in major trading pairs, especially EUR and USD.
 
This means that anyone who considers themselves a potential _market maker_ or _liquidity provider_ is especially welcome on this call, to help us brainstorm ways to make Bisq an attractive place to trade. We already have a number of ideas, and are looking to get your feedback.
 
Note that while we're happy to have pro and semi-pro traders serve as liquidity providers, we're also looking for anyone who simply has a need to sell BTC on a regular basis, e.g. for basic cash flow purposes.

**This week's agenda:**
* Market update
* Blogging initiative, call for bloggers
* Comments on upcoming release?
* Upcoming events

Feel free to add any items you'd like to cover below!

## Call details
YouTube link (watch and comment in chat):
* https://www.youtube.com/watch?v=Brg2Hc2Be9w

Hangouts link (participate in discussion):
* https://hangouts.google.com/hangouts/_/2qpzsn7eifbwnbyizeqa4ohfrae

## Comments welcome

Please add comments below with any questions you have or regarding any other topics you'd like to discuss on this call.

Hope to see you there!

**Comment by m52go** [comment]
@ripcurlx yessir.

**Comment by ripcurlx** [comment]
@m52go Thanks!

**Comment by m52go** [comment]
Proposed topics:
* Market update
* Blogging initiative, call for bloggers
* Comments on upcoming release?
