### ISSUE TITLE
Create DAO landing page

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#99]
Below are some suggestions for copy of the DAO landing page. I'm envisioning something that follows @pedromvpg's [XD prototype](https://xd.adobe.com/view/ea1d52de-ad37-457f-404c-68167278e9ce-9c2c/) design-wise...I think the blocks would look really good for the why/what/how section (assuming each item can get its own graphic).

Aesthetics are hard to convey with plain text so I used markdown to help. Pedro if you prefer any tools for making mock-ups, let me know.

The "BSQ does not raise capital" bit not might be unnecessary, but maximalist or not, everyone assumes tokens are for raising capital so I think it's important to make it 100% clear that it's not the case here.

----------------------------

# The Bisq DAO
### Bitcoin-style governance to make Bisq as unstoppable as Bitcoin itself.

Learn more ⇩

----------------------------

### WHY

Bisq trading is currently decentralized, but Bisq's funding and decision-making is not.

### WHAT

The DAO enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.

### HOW: DECISION-MAKING

With no CEO or central leadership team, DAO voting (social consensus) is what directs project strategy.

### HOW: FUNDING

With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors.

----------------------------

_BSQ does not raise capital! It's merely a tool to send trading fees directly to contributors without any central points of authority._

----------------------------

### Traders

When the DAO is live, you'll be able to pay trading fees with BSQ.

- by buying BSQ with BTC, you'll be paying Bisq contributors for their work
- BSQ trading fees are much lower than BTC trading fees
- you can still pay trading fees with plain BTC if you like

See more >

### Contributors

When the DAO is live, you'll receive BSQ for your work.

- do valuable work, request compensation, receive BSQ
- sell BSQ to traders for BTC to get paid
- do more work, grow the network, and do it all again!

See more >

----------------------------

### I'm not convinced a token is required.

Here's a post just for you >

----------------------------

### I want to learn more!

List of links >

**Comment by KanoczTomas** [comment]
I like the text a lot! It is short but to the point! 
Perhaps we should mentoin the process of burning BSQ by using it, so it is not like we are printing money for the dao. Something like its supply is governed by market forces, not defined by consensus (like other crypto currencies have a built in inflation by mining or other means). It is something that is also unique among tokens.

**Comment by ManfredKarrer** [comment]
Maybe we should add more text to the headlines:
> WHY
> Bisq trading is currently decentralized, but Bisq's funding and decision-making is not.

Suggestion: 
"Why does Bisq need a DAO? 
A decentralized exchange like Bisq requires to be censorship resistance in all aspects. The trade protocol and the P2P network have achieved that to a high degree. The way how contributors are compensated for their work and how decisions are made need to meet that criteria as well to ensure that Bisq can develop its full potential." (probably too long....)

> WHAT
> The DAO enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.

Suggestion: 
"What is the Bisq DAO? 
The Bisq DAO is the decentralized model to enable the transfer of revenue in form of the trading fees from the users of Bisq to those who build and maintain Bisq. Voting has a central function in the DAO not only for compensating contributors but also for decision making."

> HOW: DECISION-MAKING
> With no CEO or central leadership team, DAO voting (social consensus) is what directs project strategy.
> HOW: FUNDING
>  With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors

Maybe reduce it to one point

Suggestion: 
"How does the Bisq DAO work?
At the heart of the Bisq DAO is BSQ - a Bitcoin based colored coin token. The Bitcoin blockchain is used for notarizing meta data which is distributed over the Bisq P2P network. All Bisq applications are nodes in the Bisq DAO network and are validating the consensus rules."


Maybe we can add something with voting in the "Contributors" section? Thought not sure if that gets too much if not mentioned before? 

>Traders
>When the DAO is live, you'll be able to pay trading fees with BSQ.
>by buying BSQ with BTC, you'll be paying Bisq contributors for their work
>BSQ trading fees are much lower than BTC trading fees
>you can still pay trading fees with plain BTC if you like

Suggestion: 
"Traders:
When the DAO is live, you'll be able to pay trading fees with BSQ.
- if you pay trading fees in BSQ instead of BTC you get a hefty discount
- contributors are selling their BSQ on Bisq. By buying BSQ from them, you support the Bisq DAO
- Trade fees are distributed to all BSQ stakeholders by "uncoloring" BSQ back to BTC - thus all stakeholders will enjoy a value increase of their BSQ. Our way to distribute revenue.
- if you are not convinced yet, no worry you can stick with paying the fee in BTC 

> Contributors
> When the DAO is live, you'll receive BSQ for your work.
> do valuable work, request compensation, receive BSQ
> sell BSQ to traders for BTC to get paid
> do more work, grow the network, and do it all again!

Suggestion: 
"Contributors:
When the DAO is live, you'll earn BSQ for your work.
- do valuable work, request compensation in BSQ, sell BSQ to traders
- partizipate in voting about compensation requests of other contributors or any other open requests for making a decision about any change in Bisq
- enjoy the most permissionless, non hierarchical and global work place"

**Comment by m52go** [comment]
If this is too brief, I can certainly add more. Keep in mind illustrations will add more context to help explain.

I had the following impressions:
* landing page should be as brief as possible
* its job is to guide users to other pages for more details
* it shouldn't overwhelm users with implementation details

**Comment by KanoczTomas** [comment]
I too think that this is the case when less is more. The techy person can read about details from linked pages. We should keep it minimal and easily digestable.

**Comment by KanoczTomas** [comment]
> Maybe we should add more text to the headlines:
> 
> > WHY
> > Bisq trading is currently decentralized, but Bisq's funding and decision-making is not.
> 
> Suggestion:
> "Why does Bisq need a DAO?
> A decentralized exchange like Bisq requires to be censorship resistance in all aspects. The trade protocol and the P2P network have achieved that to a high degree. The way how contributors are compensated for their work and how decisions are made need to meet that criteria as well to ensure that Bisq can develop its full potential." (probably too long....)

I would keep Seve's minimal text, but add yours about full potential. Something like:
 Bisq trading is currently decentralized, but Bisq's funding and decision-making is not. Help develop its full potential.

> WHAT
> > The DAO enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.
> 
> Suggestion:
> "What is the Bisq DAO?
> The Bisq DAO is a socio-economic structure enabled by software and based on Bitcoin. It enables the transfer of revenue in form of the trading fees from the users of Bisq to those who build and maintain Bisq. Voting has a central function in the DAO for the process of compensating contributors and for decision making."

I would explain what the DAO acronym is.
A DAO is a decentralised autonomous organisation a new concept with a potential to replace classic corporations. (Then add Manfred's part) The Bisq DAO is a socio-economic structure enabled by software and based on Bitcoin. It enables the transfer of revenue in form of the trading fees from the users of Bisq to those who build and maintain Bisq. Voting has a central function in the DAO for the process of compensating contributors and for decision making. Then @m52go 's text: The DAO enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.
> > HOW: DECISION-MAKING
> > With no CEO or central leadership team, DAO voting (social consensus) is what directs project strategy.
> > HOW: FUNDING
> > With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors
> 
> Maybe reduce it to one point
> 
> Suggestion:
> "How does the Bisq DAO work?
> At the heart of the Bisq DAO is BSQ - a Bitcoin based colored coin token. The Bitcoin blockchain is used for notarizing meta data which is distributed over the Bisq P2P network. All Bisq applications are nodes in the Bisq DAO network and are validating the consensus rules. New BSQ are created when a contributor gets acceptance from the stakeholders by voting. BSQ is "uncolored" when a user pays trading fees. By that "uncoloring" process the value of each BSQ increases as the total supply gets reduced, thus making each stakeholder more whealty."

I would keep @m52go 's part mostly unchanged, but certainly add explanation of what is BSQ.

WHAT: A TOKEN?
At the heart of the Bisq DAO is BSQ - a Bitcoin based colored coin token. A colored coin lives on the bitcoin blockchain and inherits all Bitcoin's features and adds some new that are needed for the DAO like the ability to submit compensation requests on chain, vote, etc.(then would supply a link to the part of the docs where the structure of the BSQ transactions is defined) New BSQ is created when a contributor gets acceptance from the stakeholders by voting. BSQ is destroyed ("uncolored") when a user pays trading fees. This creates a unique market force governed supply of BSQ.

HOW: DECISION-MAKING
With no CEO or central leadership team, DAO voting (social consensus) is what directs project strategy.
HOW: FUNDING
With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors

> 
> > Traders
> > When the DAO is live, you'll be able to pay trading fees with BSQ.
> > by buying BSQ with BTC, you'll be paying Bisq contributors for their work
> > BSQ trading fees are much lower than BTC trading fees
> > you can still pay trading fees with plain BTC if you like
> 
> Suggestion:
> "Traders:
> When the DAO is live, you'll be able to pay trading fees with BSQ.
> 
> * if you pay trading fees in BSQ instead of BTC you get a hefty discount
> * contributors are selling their BSQ on Bisq. By buying BSQ from them, you support the Bisq DAO
> * Trade fees are distributed to all BSQ stakeholders by "uncoloring" BSQ back to BTC - thus all stakeholders will enjoy a value increase of their BSQ. A novel way to distribute revenue.
> * if you are not convinced yet, no worry you can stick with paying the fee in BTC
> 

I would keep @m52go 's wording in the traders part.
> > Contributors
> > When the DAO is live, you'll receive BSQ for your work.
> > do valuable work, request compensation, receive BSQ
> > sell BSQ to traders for BTC to get paid
> > do more work, grow the network, and do it all again!
> 
> Suggestion:
> "Contributors:
> When the DAO is live, you'll earn BSQ for your work.
> 
> * do valuable work, request compensation in BSQ, sell BSQ to traders
> * vote on compensation requests of other contributors
> * enjoy the most permissionless, non hierarchical and global way of working together for the alternative we want to see in the world"

> 
> Suggestion:
> "Contributors:
> 
> 
> * do valuable work, request compensation in BSQ, sell BSQ to traders
> * vote on compensation requests of other contributors
> * enjoy the most permissionless, non hierarchical and global way of working together for the alternative we want to see in the world"

I would merge the 2:
Contributors:
* When the DAO is live, you'll earn BSQ for your work. (I like the receive word replaced by earn!)
* do valuable work, request compensation, receive BSQ
* vote on compensation requests of other contributors
* sell BSQ to traders for BTC to get paid
* do more work, grow the network, and do it all again!


I would refrain from using superlatives like the most pemissionless, ICO's do that it could hit back ...

**Comment by ripcurlx** [comment]
Actually I think as well that we should stick to the shorter versions by @m52go. Putting too much information on this landingpage at the top, just stops people from reading until the end IMHO.

What about keeping the short versions by Steve with minor changes based on the suggestions above and add follow-up links below each section?

> > WHY
> Bisq trading is currently decentralized, but Bisq's funding and decision-making is not.
> 
> Suggestion:
> "Why does Bisq need a DAO?
> A decentralized exchange like Bisq requires to be censorship resistance in all aspects. The trade protocol and the P2P network have achieved that to a high degree. The way how contributors are compensated for their work and how decisions are made need to meet that criteria as well to ensure that Bisq can develop its full potential." (probably too long....)
> 

I think we should keep out the DAO term in this section and I'm not sure if we should add already a call to action "Help develop its full potential." at this first section.

> WHAT
The DAO enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.

I also think that we need to at least write out what DAO stands for.

The DAO, a decentralized autonomous organisation, enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.

- What is a DAO?

> > HOW: DECISION-MAKING
> > With no CEO or central leadership team, DAO voting (social consensus) is what directs project strategy.
> > HOW: FUNDING
> > With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors
> 
> Maybe reduce it to one point
> 
> Suggestion:
> "How does the Bisq DAO work?
> At the heart of the Bisq DAO is BSQ - a Bitcoin based colored coin token. The Bitcoin blockchain is used for notarizing meta data which is distributed over the Bisq P2P network. All Bisq applications are nodes in the Bisq DAO network and are validating the consensus rules. New BSQ are created when a contributor gets acceptance from the stakeholders by voting. BSQ is "uncolored" when a user pays trading fees. By that "uncoloring" process the value of each BSQ increases as the total supply gets reduced, thus making each stakeholder more whealty."

I'm not so 100% sure on the headlines, but I think it is easier to digest, having it separated in two blocks. Maybe we can add all this additional information in follow-up links that jump further down the page or on sub-pages.

HOW: DECISION-MAKING
With no CEO or central leadership team, DAO voting (social consensus) is what directs project strategy.
- How does the DAO voting work?

HOW: FUNDING
With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors
- What exactly is the BSQ token?

> > Traders
> > When the DAO is live, you'll be able to pay trading fees with BSQ.
> > by buying BSQ with BTC, you'll be paying Bisq contributors for their work
> > BSQ trading fees are much lower than BTC trading fees
> > you can still pay trading fees with plain BTC if you like
> 
> Suggestion:
> "Traders:
> When the DAO is live, you'll be able to pay trading fees with BSQ.
> 
> * if you pay trading fees in BSQ instead of BTC you get a hefty discount
> * contributors are selling their BSQ on Bisq. By buying BSQ from them, you support the Bisq DAO
> * Trade fees are distributed to all BSQ stakeholders by "uncoloring" BSQ back to BTC - thus all stakeholders will enjoy a value increase of their BSQ. A novel way to distribute revenue.
> * if you are not convinced yet, no worry you can stick with paying the fee in BTC

I also think the first point for traders should be the economic incentive to save money by using BSQ, before we go the support contributors part. From the wording I'm also more for Steve's version. 
Maybe we could put more emphasis on the personal viewpoint:

When the DAO is live, you'll be able to pay trading fees with BSQ.
- Save money by paying your trading fee with BSQ
- Support the continuous development of Bisq by buying BSQ from contributors
- Paying trading fees with BSQ ("uncoloring BSQ back to BTC") increases the value of BSQ for all stakeholders
- You can still pay trading fees with plain BTC if you like

> > > Contributors
> > > When the DAO is live, you'll receive BSQ for your work.
> > > do valuable work, request compensation, receive BSQ
> > > sell BSQ to traders for BTC to get paid
> > > do more work, grow the network, and do it all again!
> > 
> > 
> > Suggestion:
> > "Contributors:
> > When the DAO is live, you'll earn BSQ for your work.
> > 
> > * do valuable work, request compensation in BSQ, sell BSQ to traders
> > * vote on compensation requests of other contributors
> > * enjoy the most permissionless, non hierarchical and global way of working together for the alternative we want to see in the world"
> 
> > Suggestion:
> > "Contributors:
> > 
> > * do valuable work, request compensation in BSQ, sell BSQ to traders
> > * vote on compensation requests of other contributors
> > * enjoy the most permissionless, non hierarchical and global way of working together for the alternative we want to see in the world"
> 
> I would merge the 2:
> Contributors:
> 
> * When the DAO is live, you'll earn BSQ for your work. (I like the receive word replaced by earn!)
> * do valuable work, request compensation, receive BSQ
> * vote on compensation requests of other contributors
> * sell BSQ to traders for BTC to get paid
> * do more work, grow the network, and do it all again!

I also like the term earn more.

**Comment by ManfredKarrer** [comment]
Yes agree it should be shorter....
I just think we should write it for an audience as ourself. Too high level might be too "PR" like. I think most Bisq users are rather experienced and technical (?). Maybe there is a way to show 1 sentence and then have a bit more info on rollover a "read more" or the like? So that its not changing the page just inserts a bit more text (3 sentences more, just enough to cover the core idea)?
I think we have to avoid everything which comes near the ICO "PR" style.

**Comment by m52go** [comment]
Here's a mock-up. It integrates feedback from everyone so far.


For me a big part of ICO-style PR is aesthetic design...my unscientific heuristic for tokens is the more slick they look, the more likely they are a scam.

No matter what the exact text says, we should avoid fancy over-designed styling to maximize integrity.

**Comment by m52go** [comment]
Thanks everyone for the feedback so far.

I've added your suggestions with basic styling to de-emphasize non-essential details. Mock-ups are below (used free version of wireframe.cc, had to take screenshots).

---

### Notes

* if it turns out this new text is too much, maybe we can include toggles to show/hide details like Manfred suggested.
* once we finalize the level of detail we want to cover here, I will start doing mock-ups for the other pages: for traders, for contributors, and collection of DAO learning resources (assuming we want dedicated pages for all 3 of these items)
* DAO blog post for maximalists (which I 'linked' at the bottom of the mock-up) is 85% done with text from the PR I made, so it will be ready to go when this website is done

---

### Notes on feedback

> * Paying trading fees with BSQ ("uncoloring BSQ back to BTC") increases the value of BSQ for all stakeholders

This was a bullet point suggested for the Traders block (third page). I know that's something that might motivate traders to buy BSQ, but we don't mention the other side (creating BSQ). It comes across as incomplete and would raise more questions in my mind. I think explaining BSQ supply is best left to other places where we can cover it more completely.

> * vote on compensation requests of other contributors

This was a bullet point suggested for the Contributors block (third page). I added it, but I don't like it, because it implies a benefit for contributors only. That's not strictly true since traders could vote too if they really wanted.

> * enjoy the most permissionless, non hierarchical and global way of working together for the alternative we want to see in the world"

I really like this point so I made it a standalone page-break toward the bottom with slightly different wording.

---

### Mock-ups

![screenshot from 2019-02-06 19-13-03](https://user-images.githubusercontent.com/735155/52382539-a91df900-2a43-11e9-81af-bd458631a423.png)
![screenshot from 2019-02-06 19-13-23](https://user-images.githubusercontent.com/735155/52382544-ab805300-2a43-11e9-8ada-43a8ce1bc34f.png)
![screenshot from 2019-02-06 19-14-19](https://user-images.githubusercontent.com/735155/52382549-acb18000-2a43-11e9-8af7-815f364a0acd.png)

**Comment by pedromvpg** [comment]
Can I get this final version in a text format? google docs maybe?

**Comment by m52go** [comment]
@pedromvpg 

<details>
  <summary>text content of the screenshots above</summary>

# The Bisq dAO
### Bitcoin-style governance to make Bisq as unstoppable as Bitcoin itself.

---

WHY A DAO?

Bisq trading is currently decentralized, but its funding and decision-making is not.

It is critical that Bisq be resistant to censorship, and the trade protocol and P2P network achieve this—for traders.

What about Bisq's developers? Project decision-making and funding is still centralized, and this creates vulnerabilities.

---

WHAT IS THE BISQ DAO?

The Bisq DAO enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.

A DAO (decentralized autonomous organization) is just a generic term for a governance model sanctioned by software instead of a state.

Bisq's DAO is built on the Bitcoin network.

---

BISQ DAO DECISION-MAKING

With no CEO or central leadership team, DAO voting (social consensus) is what determines Bisq's project strategy.

Bisq stakeholders—traders and contributors—vote on proposals to determine Bisq strategy, compensation, and other policy.

This gives Bisq's users (like you!) influence in the direction of the project. Want to change the trade protocol? Adjust fees? Make a proposal. Voting takes place right in Bisq every month.

---

BISQ DAO FUNDING

With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors.

BSQ is colored bitcoin that contributors earn for their work on the Bisq project. Contributors sell BSQ to traders for BTC, which traders redeem for lower trading fees.

The BSQ token does NOT raise capital. It's merely a tool to redirect trading fees (that currently all go to one place) to all Bisq contributors without any central party to collect them first.

---

BSQ does not raise capital! It's merely a tool to send trading fees directly to contributors without any central points of authority.

---

### Traders

When the DAO is live, you'll be able to pay trading fees with BSQ.

* Save money by paying trading fees in BSQ instead of BTC
* Support the continuous development of Bisq by buying BSQ from contributors
* You can still pay trading fees with plain BTC if you like (but you'll miss out on the hefty discount of BSQ)

---

### Contributors

When the DAO is live, you'll earn BSQ for your work.

* Do valuable work, request compensation, receive BSQ
* Sell BSQ to traders to get paid
* Vote on compensation requests of other contributors
* Do more work, help grow the network, and do it all again!

---

The Bisq DAO implements the core values of Bitcoin into a human organization to deliver adecentralized, permissionless, sovereign, merit-based,andstatelessforce for good.

---

## Not convinced a token is required?

Tokens so far are useless because they're all issued by legal entities like companies and foundations. These entities could easily accomplish their goals without tokens.

However, when there is no entity, as in Bisq's case, things change. New tools are needed to collect revenue and make policy. Where can revenue be collected if there is no central wallet? Who determines policy if there is no leadership team?

---

## Want to learn more?

**Introduction to the Bisq DAO - Doc**

Plain-language description of the DAO and BSQ token, and how it enables decentralized funding and decision-making for the Bisq Network.

**Bisq DAO in Brief - Videos**

Short video series on what the Bisq DAO is, what it accomplishes, and why it's needed.

</details>

**Comment by pedromvpg** [comment]
Hi

Here's the link to un updated version of the design:
https://xd.adobe.com/view/ea1d52de-ad37-457f-404c-68167278e9ce-9c2c/

In my opinion I think the page is a little to dense with content. Specially the bottom part. Those ideas should have already been conveyed in the top and should be pretty clear by the time the user gets to the bottom.

Added comments and attaching the XD file below in case someone wants to play around with the text.



![bisq-dao-page](https://user-images.githubusercontent.com/807505/52392827-95898700-2a71-11e9-9b5e-0ffe72fb83e3.png)

[DAO-page.xd.zip](https://github.com/bisq-network/growth/files/2839449/DAO-page.xd.zip)
<img width="1674" alt="screen shot 2019-02-07 at 12 44 01 am" src="https://user-images.githubusercontent.com/807505/52392840-a1754900-2a71-11e9-802e-9bac247c4d8c.png">

**Comment by pedromvpg** [comment]
Ideas and feedback on the illustrations would be really helpful.

**Comment by pedromvpg** [comment]
updated XD

[DAO-page.xd.zip](https://github.com/bisq-network/growth/files/2839571/DAO-page.xd.zip)

**Comment by ripcurlx** [comment]
> Tokens so far are useless because they're all issued by legal entities

I'm not sure if we should put that much of an "opinion" here, as legit it might be.

**Comment by m52go** [comment]
> I'm not sure if we should put that much of an "opinion" here, as legit it might be.

ripcurlx you're right, that's harsh. Let's change it to:

> Many tokens seem to lack utility since they're issued by legal entities like companies and foundations. Often, these entities could accomplish their goals without tokens.

@pedromvpg you're right about density and details.

Maybe we need a different structure. I like what Blockstream does for [their Liquid page](https://blockstream.com/liquid/). One high-level block right at the top (i.e., _what_ is this in 20 words), then 4 discrete features (which could be our users/contributors blocks), benefits (i.e., what's in it for the user), and then at the bottom, details on how it all works.

How it all works is hardest to explain, which leads to complexity, which turns people away. If we put it at the bottom, we'll also have more freedom to include details.

I'll mock up something with this approach...will try Adobe XD but basic wireframe like before might be quicker.

**Comment by m52go** [comment]
I've shuffled some pieces around to ease into detail rather than forcing it all at the top. I purposely put _What_ before _Why_ to fit Blockstream's approach...does this work better?

Graphics not from Pedro are just rough ideas from me, not serious suggestions.

@pedromvpg graphics feedback:

* for the one showing the difference in BSQ and BTC trade fees, what do you think about something that says "Bisq trading fees" with a bold "90% off" badge? Or something like that. The graph seems like overkill to me to convey a rather simple idea.

*  for the voting one, what do you think about replacing the BSQ nodes with "Vote" text? That way it's just about P2P voting...proposals and votes. I know what you're trying to convey by including BSQ there, but I think for newcomers it might be confusing to see random quantities of a token mixed with proposals.

Text for this mock-up is collapsed at the bottom.

![screenshot from 2019-02-07 18-40-08-touched](https://user-images.githubusercontent.com/735155/52450485-31b29d00-2b09-11e9-84ae-912748924529.png)
![screenshot from 2019-02-07 18-40-16-touched](https://user-images.githubusercontent.com/735155/52450607-c9b08680-2b09-11e9-9e9a-d160efffb245.png)
![screenshot from 2019-02-07 18-40-35-touched](https://user-images.githubusercontent.com/735155/52451982-485bf280-2b0f-11e9-99f5-8f2581e3e966.png)
![screenshot from 2019-02-07 18-40-43-touched](https://user-images.githubusercontent.com/735155/52450806-96bac280-2b0a-11e9-964a-55ab05c6d997.png)
![screenshot from 2019-02-07 18-41-03-touched](https://user-images.githubusercontent.com/735155/52450935-15176480-2b0b-11e9-97d6-e4c7932554e3.png)
![screenshot from 2019-02-07 18-41-15](https://user-images.githubusercontent.com/735155/52450362-a6390c00-2b08-11e9-8321-19ad57706356.png)

<details>
  <summary>expand for text content of the screenshots above</summary>
  
# The Bisq DAO
### Bitcoin-style governance to make Bisq as unstoppable as Bitcoin itself.

---

## WHAT IS THE BISQ DAO?

The Bisq DAO enables Bisq to manage funding and decision-making without the confines of a corporation or other legal entity, keeping Bisq stateless & sovereign.

---

## WHAT THE BISQ DAO IS NOT

The Bisq DAO is NOT a tool to raise capital.

Bisq already makes revenue from trading fees. The Bisq DAO (and BSQ token) merely change the distribution of those trading fees.

Right now, they only go to arbitrators. With the DAO, they can be distributed to all project contributors, on merit, without any central authorities.

---

## Benefits

### Traders: Save Money

When the DAO is live, you'll be able to pay trading fees with BSQ.

* Save money by paying trading fees in BSQ instead of BTC
* Support the continuous development of Bisq by buying BSQ from contributors
* You can still pay trading fees with plain BTC if you like (but you'll miss out on the hefty discount of BSQ)

---

### Contributors: Earn Money

When the DAO is live, you'll earn BSQ for your work.

* Do valuable work, request compensation, receive BSQ
* Sell BSQ to traders to get paid
* Vote on compensation requests of other contributors
* Do more work, help grow the network, and do it all again!

---

## WHY?

Bisq trading is currently decentralized, but its funding and decision-making is not.

It is critical that Bisq be resistant to censorship, and the trade protocol and P2P network achieve this—for traders.

What about Bisq's developers? Project decision-making and funding is still centralized, and this creates vulnerabilities.

---

## HOW DOES IT WORK?

The Bisq DAO has 2 primary purposes: decision-making and funding.

### BISQ DAO DECISION-MAKING

With no CEO or central leadership team, DAO voting (social consensus) is what determines Bisq's project strategy.

Bisq stakeholders—traders and contributors—vote on proposals to determine Bisq strategy, compensation, and other policy.

This gives Bisq's users (like you!) influence in the direction of the project. Want to change the trade protocol? Adjust fees? Make a proposal. Voting takes place right in Bisq every month.

### BISQ DAO FUNDING

With no financial accounts to hold revenue, the BSQ token is what distributes value from traders to contributors.

BSQ is colored bitcoin that contributors earn for their work on the Bisq project. Contributors sell BSQ to traders for BTC, which traders redeem for lower trading fees.

The BSQ token does NOT raise capital. It's merely a tool to redirect trading fees (that currently all go to one place) to all Bisq contributors without any central party to collect them first.

---

The Bisq DAO implements the core values of Bitcoin into a human organization to deliver a decentralized, permissionless, sovereign, merit-based, and stateless force for good.

---

## Not convinced a token is required?

Tokens so far are useless because they're all issued by legal entities like companies and foundations. These entities could easily accomplish their goals without tokens.

However, when there is no entity, as in Bisq's case, things change. New tools are needed to collect revenue and make policy. Where can revenue be collected if there is no central wallet? Who determines policy if there is no leadership team?

---

## Want to learn more?

**Introduction to the Bisq DAO - Doc**

Plain-language description of the DAO and BSQ token, and how it enables decentralized funding and decision-making for the Bisq Network.

**Bisq DAO in Brief - Videos**

Short video series on what the Bisq DAO is, what it accomplishes, and why it's needed.

</details>

**Comment by ripcurlx** [comment]
> I've shuffled some pieces around to ease into detail rather than forcing it all at the top. I purposely put _What_ before _Why_ to fit Blockstream's approach..

I still think it is better to put the problem before the solution to guide the user through the same thinking process we've been through.

I agree that it make sense to put the additional information after the `Learn more` section.

**Comment by m52go** [comment]
Sure, let's move the _Why_ section to above the _What_ section.

Any other feedback?

@pedromvpg how should we proceed? If you'd like to finalize a design, I can write the markup. Or let me know what you'd prefer.

**Comment by pedromvpg** [comment]
Is the text finalized?
Can we do edits on google doc? I need a finalized text.

I can take a stab at constructing the template on jekkyl tomorrow and work on outstanding illustrations.

**Comment by m52go** [comment]
https://docs.google.com/document/d/1yXWobnrNyreIXtTXoPVZOyQwUuuGtQActZRuohSzJRc/edit?usp=sharing

**Comment by m52go** [comment]
@pedromvpg where are we with the website?

**Comment by pedromvpg** [comment]
Started on the implementation. Hope to have something tomorrow.

**Comment by pedromvpg** [comment]
Working version of the page here.
TODO:
- Fix layouts
- Fix styles
- Replace and finalize illustrations

**Comment by ripcurlx** [comment]
@pedromvpg We decided yesterday in the Dev call to do a codefreeze EOD, but will release next week. Probably Monday or Tuesday.

**Comment by pedromvpg** [comment]
Cool. Code freeze the client obviously. not the website right? That gives me some time to finish it. during the wknd.

**Comment by ripcurlx** [comment]
> Cool. Code freeze the client obviously. not the website right? That gives me some time to finish it. during the wknd.

Yes, only client code freeze.

**Comment by KanoczTomas** [comment]
FYI @m52go I added some comments to the googledocs. Nice job!

**Comment by m52go** [comment]
Completed with https://github.com/bisq-network/bisq-website/pull/121.
